// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "github.com/apimatic/go-core-runtime/https"
    "github.com/apimatic/go-core-runtime/utilities"
    "net/http"
    "shutterstockapiexplorer/models"
    "time"
)

// AudioController represents a controller struct.
type AudioController struct {
    baseController
}

// NewAudioController creates a new instance of AudioController.
// It takes a baseController as a parameter and returns a pointer to the AudioController.
func NewAudioController(baseController baseController) *AudioController {
    audioController := AudioController{baseController: baseController}
    return &audioController
}

// GetTrackList takes context, id, view, searchId as parameters and
// returns an models.ApiResponse with models.AudioDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists information about one or more audio tracks, including the description and publication date.
func (a *AudioController) GetTrackList(
    ctx context.Context,
    id []string,
    view *models.View1Enum,
    searchId *string) (
    models.ApiResponse[models.AudioDataList],
    error) {
    req := a.prepareRequest(ctx, "GET", "/v2/audio")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.QueryParam("id", id)
    if view != nil {
        req.QueryParam("view", *view)
    }
    if searchId != nil {
        req.QueryParam("search_id", *searchId)
    }
    var result models.AudioDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.AudioDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetTrackCollectionList takes context, page, perPage, embed as parameters and
// returns an models.ApiResponse with models.CollectionDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists your collections of audio tracks and their basic attributes.
func (a *AudioController) GetTrackCollectionList(
    ctx context.Context,
    page *int,
    perPage *int,
    embed []models.EmbedEnum) (
    models.ApiResponse[models.CollectionDataList],
    error) {
    req := a.prepareRequest(ctx, "GET", "/v2/audio/collections")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if embed != nil {
        req.QueryParam("embed", embed)
    }
    var result models.CollectionDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CollectionDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// CreateTrackCollection takes context, body as parameters and
// returns an models.ApiResponse with models.CollectionCreateResponse data and
// an error if there was an issue with the request or response.
// This endpoint creates one or more collections (soundboxes). To add tracks, use `POST /v2/audio/collections/{id}/items`.
func (a *AudioController) CreateTrackCollection(
    ctx context.Context,
    body models.CollectionCreateRequest) (
    models.ApiResponse[models.CollectionCreateResponse],
    error) {
    req := a.prepareRequest(ctx, "POST", "/v2/audio/collections")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    var result models.CollectionCreateResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CollectionCreateResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// DeleteTrackCollection takes context, id as parameters and
// returns an *Response and
// an error if there was an issue with the request or response.
// This endpoint deletes a collection.
func (a *AudioController) DeleteTrackCollection(
    ctx context.Context,
    id string) (
    *http.Response,
    error) {
    req := a.prepareRequest(ctx, "DELETE", "/v2/audio/collections/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    
    httpCtx, err := req.Call()
    if err != nil {
        return httpCtx.Response, err
    }
    return httpCtx.Response, err
}

// GetTrackCollection takes context, id, embed, shareCode as parameters and
// returns an models.ApiResponse with models.Collection data and
// an error if there was an issue with the request or response.
// This endpoint gets more detailed information about a collection, including the number of items in it and when it was last updated. To get the tracks in collections, use `GET /v2/audio/collections/{id}/items`.
func (a *AudioController) GetTrackCollection(
    ctx context.Context,
    id string,
    embed []models.EmbedEnum,
    shareCode *string) (
    models.ApiResponse[models.Collection],
    error) {
    req := a.prepareRequest(ctx, "GET", "/v2/audio/collections/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    if embed != nil {
        req.QueryParam("embed", embed)
    }
    if shareCode != nil {
        req.QueryParam("share_code", *shareCode)
    }
    
    var result models.Collection
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.Collection](decoder)
    return models.NewApiResponse(result, resp), err
}

// RenameTrackCollection takes context, id, body as parameters and
// returns an *Response and
// an error if there was an issue with the request or response.
// This endpoint sets a new name for a collection.
func (a *AudioController) RenameTrackCollection(
    ctx context.Context,
    id string,
    body models.CollectionUpdateRequest) (
    *http.Response,
    error) {
    req := a.prepareRequest(ctx, "POST", "/v2/audio/collections/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    
    httpCtx, err := req.Call()
    if err != nil {
        return httpCtx.Response, err
    }
    return httpCtx.Response, err
}

// DeleteTrackCollectionItems takes context, id, itemId as parameters and
// returns an *Response and
// an error if there was an issue with the request or response.
// This endpoint removes one or more tracks from a collection.
func (a *AudioController) DeleteTrackCollectionItems(
    ctx context.Context,
    id string,
    itemId []string) (
    *http.Response,
    error) {
    req := a.prepareRequest(ctx, "DELETE", "/v2/audio/collections/%v/items")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    if itemId != nil {
        req.QueryParam("item_id", itemId)
    }
    
    httpCtx, err := req.Call()
    if err != nil {
        return httpCtx.Response, err
    }
    return httpCtx.Response, err
}

// GetTrackCollectionItems takes context, id, page, perPage, shareCode, sort as parameters and
// returns an models.ApiResponse with models.CollectionItemDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists the IDs of tracks in a collection and the date that each was added.
func (a *AudioController) GetTrackCollectionItems(
    ctx context.Context,
    id string,
    page *int,
    perPage *int,
    shareCode *string,
    sort *models.Sort1Enum) (
    models.ApiResponse[models.CollectionItemDataList],
    error) {
    req := a.prepareRequest(ctx, "GET", "/v2/audio/collections/%v/items")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if shareCode != nil {
        req.QueryParam("share_code", *shareCode)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    
    var result models.CollectionItemDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CollectionItemDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// AddTrackCollectionItems takes context, id, body as parameters and
// returns an *Response and
// an error if there was an issue with the request or response.
// This endpoint adds one or more tracks to a collection by track IDs.
func (a *AudioController) AddTrackCollectionItems(
    ctx context.Context,
    id string,
    body models.CollectionItemRequest) (
    *http.Response,
    error) {
    req := a.prepareRequest(ctx, "POST", "/v2/audio/collections/%v/items")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    
    httpCtx, err := req.Call()
    if err != nil {
        return httpCtx.Response, err
    }
    return httpCtx.Response, err
}

// ListGenres takes context, language as parameters and
// returns an models.ApiResponse with models.GenreList data and
// an error if there was an issue with the request or response.
// This endpoint returns a list of all audio genres.
func (a *AudioController) ListGenres(
    ctx context.Context,
    language *string) (
    models.ApiResponse[models.GenreList],
    error) {
    req := a.prepareRequest(ctx, "GET", "/v2/audio/genres")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    if language != nil {
        req.QueryParam("language", *language)
    }
    var result models.GenreList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.GenreList](decoder)
    return models.NewApiResponse(result, resp), err
}

// ListInstruments takes context, language as parameters and
// returns an models.ApiResponse with models.InstrumentList data and
// an error if there was an issue with the request or response.
// This endpoint returns a list of all audio instruments.
func (a *AudioController) ListInstruments(
    ctx context.Context,
    language *string) (
    models.ApiResponse[models.InstrumentList],
    error) {
    req := a.prepareRequest(ctx, "GET", "/v2/audio/instruments")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    if language != nil {
        req.QueryParam("language", *language)
    }
    var result models.InstrumentList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.InstrumentList](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetTrackLicenseList takes context, audioId, license, page, perPage, sort, username, startDate, endDate, downloadAvailability, teamHistory as parameters and
// returns an models.ApiResponse with models.DownloadHistoryDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists existing licenses. You can filter the results according to the track ID to see if you have an existing license for a specific track.
func (a *AudioController) GetTrackLicenseList(
    ctx context.Context,
    audioId *string,
    license *string,
    page *int,
    perPage *int,
    sort *models.Sort1Enum,
    username *string,
    startDate *time.Time,
    endDate *time.Time,
    downloadAvailability *models.DownloadAvailabilityEnum,
    teamHistory *bool) (
    models.ApiResponse[models.DownloadHistoryDataList],
    error) {
    req := a.prepareRequest(ctx, "GET", "/v2/audio/licenses")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if audioId != nil {
        req.QueryParam("audio_id", *audioId)
    }
    if license != nil {
        req.QueryParam("license", *license)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if username != nil {
        req.QueryParam("username", *username)
    }
    if startDate != nil {
        req.QueryParam("start_date", startDate.Format(time.RFC3339))
    }
    if endDate != nil {
        req.QueryParam("end_date", endDate.Format(time.RFC3339))
    }
    if downloadAvailability != nil {
        req.QueryParam("download_availability", *downloadAvailability)
    }
    if teamHistory != nil {
        req.QueryParam("team_history", *teamHistory)
    }
    var result models.DownloadHistoryDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.DownloadHistoryDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// LicenseTrack takes context, body, license, searchId as parameters and
// returns an models.ApiResponse with models.LicenseAudioResultDataList data and
// an error if there was an issue with the request or response.
// This endpoint gets licenses for one or more tracks. The download links in the response are valid for 8 hours.
func (a *AudioController) LicenseTrack(
    ctx context.Context,
    body models.LicenseAudioRequest,
    license *models.License3Enum,
    searchId *string) (
    models.ApiResponse[models.LicenseAudioResultDataList],
    error) {
    req := a.prepareRequest(ctx, "POST", "/v2/audio/licenses")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.Header("Content-Type", "application/json")
    if license != nil {
        req.QueryParam("license", *license)
    }
    if searchId != nil {
        req.QueryParam("search_id", *searchId)
    }
    req.Json(&body)
    var result models.LicenseAudioResultDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.LicenseAudioResultDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// DownloadTracks takes context, id as parameters and
// returns an models.ApiResponse with models.AudioUrl data and
// an error if there was an issue with the request or response.
// This endpoint redownloads tracks that you have already received a license for. The download links in the response are valid for 8 hours.
func (a *AudioController) DownloadTracks(
    ctx context.Context,
    id string) (
    models.ApiResponse[models.AudioUrl],
    error) {
    req := a.prepareRequest(ctx, "POST", "/v2/audio/licenses/%v/downloads")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    
    var result models.AudioUrl
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.AudioUrl](decoder)
    return models.NewApiResponse(result, resp), err
}

// ListMoods takes context, language as parameters and
// returns an models.ApiResponse with models.MoodList data and
// an error if there was an issue with the request or response.
// This endpoint returns a list of all audio moods.
func (a *AudioController) ListMoods(
    ctx context.Context,
    language *string) (
    models.ApiResponse[models.MoodList],
    error) {
    req := a.prepareRequest(ctx, "GET", "/v2/audio/moods")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    if language != nil {
        req.QueryParam("language", *language)
    }
    var result models.MoodList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.MoodList](decoder)
    return models.NewApiResponse(result, resp), err
}

// SearchTracks takes context, artists, bpm, bpmFrom, bpmTo, duration, durationFrom, durationTo, genre, isInstrumental, instruments, moods, page, perPage, query, sort, sortOrder, vocalDescription, view, fields, library, language as parameters and
// returns an models.ApiResponse with models.AudioSearchResults data and
// an error if there was an issue with the request or response.
// This endpoint searches for tracks. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter.
func (a *AudioController) SearchTracks(
    ctx context.Context,
    artists []string,
    bpm *int,
    bpmFrom *int,
    bpmTo *int,
    duration *int,
    durationFrom *int,
    durationTo *int,
    genre []string,
    isInstrumental *bool,
    instruments []string,
    moods []string,
    page *int,
    perPage *int,
    query *string,
    sort *models.Sort3Enum,
    sortOrder *models.SortOrderEnum,
    vocalDescription *string,
    view *models.View1Enum,
    fields *string,
    library *models.LibraryEnum,
    language *string) (
    models.ApiResponse[models.AudioSearchResults],
    error) {
    req := a.prepareRequest(ctx, "GET", "/v2/audio/search")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if artists != nil {
        req.QueryParam("artists", artists)
    }
    if bpm != nil {
        req.QueryParam("bpm", *bpm)
    }
    if bpmFrom != nil {
        req.QueryParam("bpm_from", *bpmFrom)
    }
    if bpmTo != nil {
        req.QueryParam("bpm_to", *bpmTo)
    }
    if duration != nil {
        req.QueryParam("duration", *duration)
    }
    if durationFrom != nil {
        req.QueryParam("duration_from", *durationFrom)
    }
    if durationTo != nil {
        req.QueryParam("duration_to", *durationTo)
    }
    if genre != nil {
        req.QueryParam("genre", genre)
    }
    if isInstrumental != nil {
        req.QueryParam("is_instrumental", *isInstrumental)
    }
    if instruments != nil {
        req.QueryParam("instruments", instruments)
    }
    if moods != nil {
        req.QueryParam("moods", moods)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if query != nil {
        req.QueryParam("query", *query)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if sortOrder != nil {
        req.QueryParam("sort_order", *sortOrder)
    }
    if vocalDescription != nil {
        req.QueryParam("vocal_description", *vocalDescription)
    }
    if view != nil {
        req.QueryParam("view", *view)
    }
    if fields != nil {
        req.QueryParam("fields", *fields)
    }
    if library != nil {
        req.QueryParam("library", *library)
    }
    if language != nil {
        req.QueryParam("language", *language)
    }
    var result models.AudioSearchResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.AudioSearchResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetTrack takes context, id, view, searchId as parameters and
// returns an models.ApiResponse with models.Audio data and
// an error if there was an issue with the request or response.
// This endpoint shows information about a track, including its genres, instruments, and other attributes.
func (a *AudioController) GetTrack(
    ctx context.Context,
    id int,
    view *models.View1Enum,
    searchId *string) (
    models.ApiResponse[models.Audio],
    error) {
    req := a.prepareRequest(ctx, "GET", "/v2/audio/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if view != nil {
        req.QueryParam("view", *view)
    }
    if searchId != nil {
        req.QueryParam("search_id", *searchId)
    }
    
    var result models.Audio
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.Audio](decoder)
    return models.NewApiResponse(result, resp), err
}
