// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "encoding/json"
    "github.com/apimatic/go-core-runtime/testHelper"
    "shutterstockapiexplorer/models"
    "testing"
    "time"
)

// TestAudioControllerTestGetTrackList tests the behavior of the AudioController
func TestAudioControllerTestGetTrackList(t *testing.T) {
    ctx := context.Background()
    id := []string{ "442583","434750" }
    view := models.View1Enum("minimal")
    searchId := "00000000-0000-0000-0000-000000000000"
    apiResponse, err := audioController.GetTrackList(ctx, id, &view, &searchId)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/AudioDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestAudioControllerTestGetTrackCollectionList tests the behavior of the AudioController
func TestAudioControllerTestGetTrackCollectionList(t *testing.T) {
    ctx := context.Background()
    page := int(1)
    perPage := int(100)
    
    apiResponse, err := audioController.GetTrackCollectionList(ctx, &page, &perPage, nil)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/CollectionDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestAudioControllerTestDeleteTrackCollection tests the behavior of the AudioController
func TestAudioControllerTestDeleteTrackCollection(t *testing.T) {
    ctx := context.Background()
    id := "48433111"
    resp, err := audioController.DeleteTrackCollection(ctx, id)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, resp.StatusCode, 204)
}

// TestAudioControllerTestRenameTrackCollection tests the behavior of the AudioController
func TestAudioControllerTestRenameTrackCollection(t *testing.T) {
    ctx := context.Background()
    id := "48433107"
    var body models.CollectionUpdateRequest
    errBody := json.Unmarshal([]byte(`{"name":"Best rock music"}`), &body)
    if errBody != nil {
        t.Errorf("Cannot parse the model object.")
    }
    resp, err := audioController.RenameTrackCollection(ctx, id, body)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, resp.StatusCode, 204)
}

// TestAudioControllerTestDeleteTrackCollectionItems tests the behavior of the AudioController
func TestAudioControllerTestDeleteTrackCollectionItems(t *testing.T) {
    ctx := context.Background()
    id := "48433119"
    itemId := []string{ "76688182","40005859" }
    resp, err := audioController.DeleteTrackCollectionItems(ctx, id, itemId)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, resp.StatusCode, 204)
}

// TestAudioControllerTestGetTrackCollectionItems tests the behavior of the AudioController
func TestAudioControllerTestGetTrackCollectionItems(t *testing.T) {
    ctx := context.Background()
    id := "126351027"
    page := int(1)
    perPage := int(100)
    
    sort := models.Sort1Enum("oldest")
    apiResponse, err := audioController.GetTrackCollectionItems(ctx, id, &page, &perPage, nil, &sort)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"data":[{"added_time":"2016-08-18T18:52:59-04:00","id":"76688182","media_type":"audio"},{"added_time":"2016-08-18T18:52:59-04:00","id":"40005859","media_type":"audio"}],"page":1,"per_page":2}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestAudioControllerTestAddTrackCollectionItems tests the behavior of the AudioController
func TestAudioControllerTestAddTrackCollectionItems(t *testing.T) {
    ctx := context.Background()
    id := "48433115"
    var body models.CollectionItemRequest
    errBody := json.Unmarshal([]byte(`{"items":[{"id":"442583"},{"id":"7491192"}]}`), &body)
    if errBody != nil {
        t.Errorf("Cannot parse the model object.")
    }
    resp, err := audioController.AddTrackCollectionItems(ctx, id, body)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, resp.StatusCode, 204)
}

// TestAudioControllerTestGetTrackLicenseList tests the behavior of the AudioController
func TestAudioControllerTestGetTrackLicenseList(t *testing.T) {
    ctx := context.Background()
    audioId := "1"
    license := "48433107"
    page := int(1)
    perPage := int(20)
    sort := models.Sort1Enum("newest")
    username := "aUniqueUsername"
    startDate, errTime := time.Parse(time.RFC3339, "2021-03-29T13:25:13.521Z")
    if errTime != nil {
        t.Error(errTime)
    }
    endDate, errTime := time.Parse(time.RFC3339, "2021-03-29T13:25:13.521Z")
    if errTime != nil {
        t.Error(errTime)
    }
    downloadAvailability := models.DownloadAvailabilityEnum("all")
    teamHistory := bool(false)
    apiResponse, err := audioController.GetTrackLicenseList(ctx, &audioId, &license, &page, &perPage, &sort, &username, &startDate, &endDate, &downloadAvailability, &teamHistory)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"data":[{"audio":{"format":{"size":"clean_audio"},"id":"420298"},"download_time":"2020-11-11T16:15:20.000Z","id":"a10b7a7a5a02113a928f13e5ba196151d6","is_downloadable":true,"license":"premier_music_extended","metadata":{"purchase_order":"123"},"user":{"username":"jsmith"}}],"page":1,"per_page":20,"total_count":1}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestAudioControllerTestDownloadTracks tests the behavior of the AudioController
func TestAudioControllerTestDownloadTracks(t *testing.T) {
    ctx := context.Background()
    id := "e123"
    apiResponse, err := audioController.DownloadTracks(ctx, id)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"shorts_loops_stems":"http://download2.dev.shutterstock.com/gatekeeper/abc/original.zip","url":"http://download2.dev.shutterstock.com/gatekeeper/abc/original.wav"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}
