// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "github.com/apimatic/go-core-runtime/https"
    "github.com/apimatic/go-core-runtime/utilities"
    "net/http"
    "shutterstockapiexplorer/models"
)

// CatalogController represents a controller struct.
type CatalogController struct {
    baseController
}

// NewCatalogController creates a new instance of CatalogController.
// It takes a baseController as a parameter and returns a pointer to the CatalogController.
func NewCatalogController(baseController baseController) *CatalogController {
    catalogController := CatalogController{baseController: baseController}
    return &catalogController
}

// GetCollections takes context, page, perPage, sort, shared as parameters and
// returns an models.ApiResponse with models.CatalogCollectionDataList data and
// an error if there was an issue with the request or response.
// This endpoint returns a list of catalog collections.
func (c *CatalogController) GetCollections(
    ctx context.Context,
    page *int,
    perPage *int,
    sort *models.Sort1Enum,
    shared *bool) (
    models.ApiResponse[models.CatalogCollectionDataList],
    error) {
    req := c.prepareRequest(ctx, "GET", "/v2/catalog/collections")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Invalid status value"},
    })
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if shared != nil {
        req.QueryParam("shared", *shared)
    }
    var result models.CatalogCollectionDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CatalogCollectionDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// CreateCollection takes context, body as parameters and
// returns an models.ApiResponse with models.CatalogCollection data and
// an error if there was an issue with the request or response.
// This endpoint creates a catalog collection and optionally adds assets. To add assets to the collection later, use `PATCH /v2/catalog/collections/{collection_id}/items`.
func (c *CatalogController) CreateCollection(
    ctx context.Context,
    body models.CreateCatalogCollection) (
    models.ApiResponse[models.CatalogCollection],
    error) {
    req := c.prepareRequest(ctx, "POST", "/v2/catalog/collections")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    var result models.CatalogCollection
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CatalogCollection](decoder)
    return models.NewApiResponse(result, resp), err
}

// DeleteCollection takes context, collectionId as parameters and
// returns an *Response and
// an error if there was an issue with the request or response.
// This endpoint deletes a catalog collection. It does not remove the assets from the user's account's catalog.
func (c *CatalogController) DeleteCollection(
    ctx context.Context,
    collectionId string) (
    *http.Response,
    error) {
    req := c.prepareRequest(ctx, "DELETE", "/v2/catalog/collections/%v")
    req.AppendTemplateParams(collectionId)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "404": {Message: "Collection not found"},
    })
    
    httpCtx, err := req.Call()
    if err != nil {
        return httpCtx.Response, err
    }
    return httpCtx.Response, err
}

// UpdateCollection takes context, collectionId, body as parameters and
// returns an models.ApiResponse with models.CatalogCollection data and
// an error if there was an issue with the request or response.
// This endpoint updates the metadata of a catalog collection.
func (c *CatalogController) UpdateCollection(
    ctx context.Context,
    collectionId string,
    body models.UpdateCatalogCollection) (
    models.ApiResponse[models.CatalogCollection],
    error) {
    req := c.prepareRequest(ctx, "PATCH", "/v2/catalog/collections/%v")
    req.AppendTemplateParams(collectionId)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    
    var result models.CatalogCollection
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CatalogCollection](decoder)
    return models.NewApiResponse(result, resp), err
}

// DeleteFromCollection takes context, collectionId, body as parameters and
// returns an models.ApiResponse with models.CatalogCollection data and
// an error if there was an issue with the request or response.
// This endpoint removes assets from a catalog collection. It does not remove the assets from the user's account's catalog.
func (c *CatalogController) DeleteFromCollection(
    ctx context.Context,
    collectionId string,
    body models.RemoveCatalogCollectionItems) (
    models.ApiResponse[models.CatalogCollection],
    error) {
    req := c.prepareRequest(ctx, "DELETE", "/v2/catalog/collections/%v/items")
    req.AppendTemplateParams(collectionId)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    
    var result models.CatalogCollection
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CatalogCollection](decoder)
    return models.NewApiResponse(result, resp), err
}

// AddToCollection takes context, collectionId, body as parameters and
// returns an models.ApiResponse with models.CatalogCollection data and
// an error if there was an issue with the request or response.
// This endpoint adds assets to a catalog collection. It also automatically adds the assets to the user's account's catalog.
func (c *CatalogController) AddToCollection(
    ctx context.Context,
    collectionId string,
    body models.CreateCatalogCollectionItems) (
    models.ApiResponse[models.CatalogCollection],
    error) {
    req := c.prepareRequest(ctx, "POST", "/v2/catalog/collections/%v/items")
    req.AppendTemplateParams(collectionId)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    
    var result models.CatalogCollection
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CatalogCollection](decoder)
    return models.NewApiResponse(result, resp), err
}

// SearchCatalog takes context, sort, page, perPage, query, collectionId, assetType as parameters and
// returns an models.ApiResponse with models.CatalogCollectionItemDataList data and
// an error if there was an issue with the request or response.
// This endpoint searches for assets in the account's catalog. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter. You can also filter search terms out in the `query` parameter by prefixing the term with NOT.
func (c *CatalogController) SearchCatalog(
    ctx context.Context,
    sort *models.Sort1Enum,
    page *int,
    perPage *int,
    query *string,
    collectionId []string,
    assetType []models.AssetTypeEnum) (
    models.ApiResponse[models.CatalogCollectionItemDataList],
    error) {
    req := c.prepareRequest(ctx, "GET", "/v2/catalog/search")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if query != nil {
        req.QueryParam("query", *query)
    }
    if collectionId != nil {
        req.QueryParam("collection_id", collectionId)
    }
    if assetType != nil {
        req.QueryParam("asset_type", assetType)
    }
    var result models.CatalogCollectionItemDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CatalogCollectionItemDataList](decoder)
    return models.NewApiResponse(result, resp), err
}
