// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "github.com/apimatic/go-core-runtime/https"
    "net/http"
)

const UserAgent = "APIMATIC 3.0"
// Client is an interface representing the main client for accessing configuration and controllers.
type ClientInterface interface {
    Configuration() Configuration
    CloneWithConfiguration(options ...ConfigurationOptions) ClientInterface
    CustomMusicController() *CustomMusicController
    AudioController() *AudioController
    ImagesController() *ImagesController
    CatalogController() *CatalogController
    ContributorsController() *ContributorsController
    ComputerVisionController() *ComputerVisionController
    EditorialImagesController() *EditorialImagesController
    EditorialVideoController() *EditorialVideoController
    OauthController() *OauthController
    SoundEffectsController() *SoundEffectsController
    TestController() *TestController
    UsersController() *UsersController
    VideosController() *VideosController
    OAuthAuthorizationController() *OAuthAuthorizationController
    CustomerAccessCodeManager() *CustomerAccessCodeManager
}

// client is an implementation of the Client interface.
type client struct {
    callBuilderFactory           https.CallBuilderFactory
    configuration                Configuration
    customMusicController        CustomMusicController
    audioController              AudioController
    imagesController             ImagesController
    catalogController            CatalogController
    contributorsController       ContributorsController
    computerVisionController     ComputerVisionController
    editorialImagesController    EditorialImagesController
    editorialVideoController     EditorialVideoController
    oauthController              OauthController
    soundEffectsController       SoundEffectsController
    testController               TestController
    usersController              UsersController
    videosController             VideosController
    oAuthAuthorizationController OAuthAuthorizationController
    customerAccessCodeManager    CustomerAccessCodeManager
}

// NewClient is the constructor for creating a new client instance.
// It takes a Configuration object as a parameter and returns the Client interface.
func NewClient(configuration Configuration) ClientInterface {
    client := &client{
        configuration: configuration,
    }
    
    client.callBuilderFactory = callBuilderHandler(
    	func(server string) string {
    		if server == "" {
    			server = "default"
    		}
    		return getBaseUri(Server(server), client.configuration)
    	},
    	createAuthenticationFromConfig(configuration),
    	https.NewHttpClient(configuration.HttpConfiguration()),
    	configuration.httpConfiguration.RetryConfiguration(),
    	https.Indexed,
        withUserAgent(UserAgent),
    )
    
    baseController := NewBaseController(client)
    client.customMusicController = *NewCustomMusicController(*baseController)
    client.audioController = *NewAudioController(*baseController)
    client.imagesController = *NewImagesController(*baseController)
    client.catalogController = *NewCatalogController(*baseController)
    client.contributorsController = *NewContributorsController(*baseController)
    client.computerVisionController = *NewComputerVisionController(*baseController)
    client.editorialImagesController = *NewEditorialImagesController(*baseController)
    client.editorialVideoController = *NewEditorialVideoController(*baseController)
    client.oauthController = *NewOauthController(*baseController)
    client.soundEffectsController = *NewSoundEffectsController(*baseController)
    client.testController = *NewTestController(*baseController)
    client.usersController = *NewUsersController(*baseController)
    client.videosController = *NewVideosController(*baseController)
    client.oAuthAuthorizationController = *NewOAuthAuthorizationController(*baseController)
    client.customerAccessCodeManager = *newCustomerAccessCodeManager(configuration.customerAccessCodeCredentials, client.oAuthAuthorizationController, configuration)
    return client
}

// Configuration returns the configuration instance of the client.
func (c *client) Configuration() Configuration {
    return c.configuration
}

// CloneWithConfiguration returns a new copy with the provided options of the configuration instance of the client.
func (c *client) CloneWithConfiguration(options ...ConfigurationOptions) ClientInterface {
    return NewClient(c.configuration.cloneWithOptions(options...))
}

// CustomMusicController returns the customMusicController instance of the client.
func (c *client) CustomMusicController() *CustomMusicController {
    return &c.customMusicController
}

// AudioController returns the audioController instance of the client.
func (c *client) AudioController() *AudioController {
    return &c.audioController
}

// ImagesController returns the imagesController instance of the client.
func (c *client) ImagesController() *ImagesController {
    return &c.imagesController
}

// CatalogController returns the catalogController instance of the client.
func (c *client) CatalogController() *CatalogController {
    return &c.catalogController
}

// ContributorsController returns the contributorsController instance of the client.
func (c *client) ContributorsController() *ContributorsController {
    return &c.contributorsController
}

// ComputerVisionController returns the computerVisionController instance of the client.
func (c *client) ComputerVisionController() *ComputerVisionController {
    return &c.computerVisionController
}

// EditorialImagesController returns the editorialImagesController instance of the client.
func (c *client) EditorialImagesController() *EditorialImagesController {
    return &c.editorialImagesController
}

// EditorialVideoController returns the editorialVideoController instance of the client.
func (c *client) EditorialVideoController() *EditorialVideoController {
    return &c.editorialVideoController
}

// OauthController returns the oauthController instance of the client.
func (c *client) OauthController() *OauthController {
    return &c.oauthController
}

// SoundEffectsController returns the soundEffectsController instance of the client.
func (c *client) SoundEffectsController() *SoundEffectsController {
    return &c.soundEffectsController
}

// TestController returns the testController instance of the client.
func (c *client) TestController() *TestController {
    return &c.testController
}

// UsersController returns the usersController instance of the client.
func (c *client) UsersController() *UsersController {
    return &c.usersController
}

// VideosController returns the videosController instance of the client.
func (c *client) VideosController() *VideosController {
    return &c.videosController
}

// OAuthAuthorizationController returns the oAuthAuthorizationController instance of the client.
func (c *client) OAuthAuthorizationController() *OAuthAuthorizationController {
    return &c.oAuthAuthorizationController
}

// CustomerAccessCodeManager returns the customerAccessCodeManager instance of the client.
func (c *client) CustomerAccessCodeManager() *CustomerAccessCodeManager {
    return &c.customerAccessCodeManager
}

// GetCallBuilder returns the CallBuilderFactory used by the client.
func (c *client) GetCallBuilder() https.CallBuilderFactory {
    return c.callBuilderFactory
}

// getBaseUri returns the base URI based on the server and configuration.
func getBaseUri(
    server Server,
    configuration Configuration) string {
    if configuration.Environment() == Environment(PRODUCTION) {
        if server == Server(ENUMDEFAULT) {
            return "https://api.shutterstock.com"
        }
        if server == Server(AUTHSERVER) {
            return "https://accounts.shutterstock.com/oauth"
        }
    }
    if configuration.Environment() == Environment(ENVIRONMENT2) {
        if server == Server(ENUMDEFAULT) {
            return "https://api-sandbox.shutterstock.com"
        }
        if server == Server(AUTHSERVER) {
            return "https://accounts.shutterstock.com/oauth"
        }
    }
    return "TODO: Select a valid server."
}

// clientOptions is a function type representing options for the client.
type clientOptions func(cb https.CallBuilder)

// callBuilderHandler creates the call builder factory with various options.
func callBuilderHandler(
    baseUrlProvider func(server string) string,
    auth map[string]https.AuthInterface,
    httpClient https.HttpClient,
    retryConfig RetryConfiguration,
    arraySerializationOption https.ArraySerializationOption,
    opts ...clientOptions) https.CallBuilderFactory {
    callBuilderFactory := https.CreateCallBuilderFactory(baseUrlProvider, auth, httpClient, retryConfig, arraySerializationOption)
    return tap(callBuilderFactory, opts...)
}

// tap is a utility function to apply client options to the call builder factory.
func tap(
    callBuilderFactory https.CallBuilderFactory,
    opts ...clientOptions) https.CallBuilderFactory {
    return func(ctx context.Context, httpMethod, path string) https.CallBuilder {
    	callBuilder := callBuilderFactory(ctx, httpMethod, path)
    	for _, opt := range opts {
    		opt(callBuilder)
    	}
    	return callBuilder
    }
}

// withUserAgent is an option to add a user agent header to the HTTP request.
func withUserAgent(userAgent string) clientOptions {
    f := func(request *http.Request) *http.Request {
    	request.Header.Set("user-agent", userAgent)
    	return request
    }
    return func(cb https.CallBuilder) {
    	cb.InterceptRequest(f)
    }
}
