// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "os"
)

// ConfigurationOptions represents a function type that can be used to apply options to the Configuration struct.
type ConfigurationOptions func(*Configuration)

// Configuration holds configuration settings.
type Configuration struct {
    environment                   Environment
    httpConfiguration             HttpConfiguration
    basicCredentials              BasicCredentials
    customerAccessCodeCredentials CustomerAccessCodeCredentials
}

// newConfiguration creates a new Configuration with the provided options.
func newConfiguration(options ...ConfigurationOptions) Configuration {
    config := Configuration{}
    
    for _, option := range options {
        option(&config)
    }
    return config
}

// cloneWithOptions provides configuration with the provided options.
func (config Configuration) cloneWithOptions(options ...ConfigurationOptions) Configuration {
    for _, option := range options {
        option(&config)
    }
    return config
}

// WithEnvironment is an option that sets the Environment in the Configuration.
func WithEnvironment(environment Environment) ConfigurationOptions {
    return func(c *Configuration) {
        c.environment = environment
    }
}

// WithHttpConfiguration is an option that sets the HttpConfiguration in the Configuration.
func WithHttpConfiguration(httpConfiguration HttpConfiguration) ConfigurationOptions {
    return func(c *Configuration) {
        c.httpConfiguration = httpConfiguration
    }
}

// WithBasicCredentials is an option that sets the BasicCredentials in the Configuration.
func WithBasicCredentials(basicCredentials BasicCredentials) ConfigurationOptions {
    return func(c *Configuration) {
        c.basicCredentials = basicCredentials
    }
}

// WithCustomerAccessCodeCredentials is an option that sets the CustomerAccessCodeCredentials in the Configuration.
func WithCustomerAccessCodeCredentials(customerAccessCodeCredentials CustomerAccessCodeCredentials) ConfigurationOptions {
    return func(c *Configuration) {
        c.customerAccessCodeCredentials = customerAccessCodeCredentials
    }
}

// Environment returns the environment from the Configuration.
func (c Configuration) Environment() Environment {
    return c.environment
}

// HttpConfiguration returns the httpConfiguration from the Configuration.
func (c Configuration) HttpConfiguration() HttpConfiguration {
    return c.httpConfiguration
}

// BasicCredentials returns the basicCredentials from the Configuration.
func (c Configuration) BasicCredentials() BasicCredentials {
    return c.basicCredentials
}

// CustomerAccessCodeCredentials returns the customerAccessCodeCredentials from the Configuration.
func (c Configuration) CustomerAccessCodeCredentials() CustomerAccessCodeCredentials {
    return c.customerAccessCodeCredentials
}

// CreateConfigurationFromEnvironment creates a new Configuration with default settings.
// It also configures various Configuration options.
func CreateConfigurationFromEnvironment(options ...ConfigurationOptions) Configuration {
    config := DefaultConfiguration()
    
    environment := os.Getenv("SHUTTERSTOCKAPIEXPLORER_ENVIRONMENT")
    if environment != "" {
        config.environment = Environment(environment)
    }
    username := os.Getenv("SHUTTERSTOCKAPIEXPLORER_USERNAME")
    if username != "" {
        config.basicCredentials.username = username
    }
    password := os.Getenv("SHUTTERSTOCKAPIEXPLORER_PASSWORD")
    if password != "" {
        config.basicCredentials.password = password
    }
    oAuthClientId := os.Getenv("SHUTTERSTOCKAPIEXPLORER_O_AUTH_CLIENT_ID")
    if oAuthClientId != "" {
        config.customerAccessCodeCredentials.oAuthClientId = oAuthClientId
    }
    oAuthClientSecret := os.Getenv("SHUTTERSTOCKAPIEXPLORER_O_AUTH_CLIENT_SECRET")
    if oAuthClientSecret != "" {
        config.customerAccessCodeCredentials.oAuthClientSecret = oAuthClientSecret
    }
    oAuthRedirectUri := os.Getenv("SHUTTERSTOCKAPIEXPLORER_O_AUTH_REDIRECT_URI")
    if oAuthRedirectUri != "" {
        config.customerAccessCodeCredentials.oAuthRedirectUri = oAuthRedirectUri
    }
    for _, option := range options {
        option(&config)
    }
    return config
}

// Server represents available servers.
type Server string

const (
    ENUMDEFAULT Server = "default"
    AUTHSERVER  Server = "auth server"
)

// Environment represents available environments.
type Environment string

const (
    PRODUCTION   Environment = "production"
    ENVIRONMENT2 Environment = "environment2"
)

// CreateRetryConfiguration creates a new RetryConfiguration with the provided options.
func CreateRetryConfiguration(options ...RetryConfigurationOptions) RetryConfiguration {
    config := DefaultRetryConfiguration()
    
    for _, option := range options {
        option(&config)
    }
    return config
}

// CreateHttpConfiguration creates a new HttpConfiguration with the provided options.
func CreateHttpConfiguration(options ...HttpConfigurationOptions) HttpConfiguration {
    config := DefaultHttpConfiguration()
    
    for _, option := range options {
        option(&config)
    }
    return config
}

// CreateConfiguration creates a new Configuration with the provided options.
func CreateConfiguration(options ...ConfigurationOptions) Configuration {
    config := DefaultConfiguration()
    
    for _, option := range options {
        option(&config)
    }
    return config
}
