// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "github.com/apimatic/go-core-runtime/https"
    "github.com/apimatic/go-core-runtime/utilities"
    "shutterstockapiexplorer/models"
)

// CustomMusicController represents a controller struct.
type CustomMusicController struct {
    baseController
}

// NewCustomMusicController creates a new instance of CustomMusicController.
// It takes a baseController as a parameter and returns a pointer to the CustomMusicController.
func NewCustomMusicController(baseController baseController) *CustomMusicController {
    customMusicController := CustomMusicController{baseController: baseController}
    return &customMusicController
}

// ListCustomDescriptors takes context, renderSpeedOver, bandId, bandName, page, perPage, id, instrumentName, instrumentId, tempo, tempoTo, tempoFrom, name, tag as parameters and
// returns an models.ApiResponse with models.DescriptorsListResult data and
// an error if there was an issue with the request or response.
// This endpoint lists the descriptors that you can use in the audio regions in an audio render.
func (c *CustomMusicController) ListCustomDescriptors(
    ctx context.Context,
    renderSpeedOver *float64,
    bandId *string,
    bandName *string,
    page *int,
    perPage *int,
    id []string,
    instrumentName *string,
    instrumentId *string,
    tempo *float64,
    tempoTo *float64,
    tempoFrom *float64,
    name *string,
    tag *string) (
    models.ApiResponse[models.DescriptorsListResult],
    error) {
    req := c.prepareRequest(ctx, "GET", "/v2/ai/audio/descriptors")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Not Found"},
    })
    if renderSpeedOver != nil {
        req.QueryParam("render_speed_over", *renderSpeedOver)
    }
    if bandId != nil {
        req.QueryParam("band_id", *bandId)
    }
    if bandName != nil {
        req.QueryParam("band_name", *bandName)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if id != nil {
        req.QueryParam("id", id)
    }
    if instrumentName != nil {
        req.QueryParam("instrument_name", *instrumentName)
    }
    if instrumentId != nil {
        req.QueryParam("instrument_id", *instrumentId)
    }
    if tempo != nil {
        req.QueryParam("tempo", *tempo)
    }
    if tempoTo != nil {
        req.QueryParam("tempo_to", *tempoTo)
    }
    if tempoFrom != nil {
        req.QueryParam("tempo_from", *tempoFrom)
    }
    if name != nil {
        req.QueryParam("name", *name)
    }
    if tag != nil {
        req.QueryParam("tag", *tag)
    }
    var result models.DescriptorsListResult
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.DescriptorsListResult](decoder)
    return models.NewApiResponse(result, resp), err
}

// ListCustomInstruments takes context, id, perPage, page, name, tag as parameters and
// returns an models.ApiResponse with models.InstrumentsListResult data and
// an error if there was an issue with the request or response.
// This endpoint lists the instruments that you can include in computer audio. If you specify more than one search parameter, the API uses an AND condition.
func (c *CustomMusicController) ListCustomInstruments(
    ctx context.Context,
    id []string,
    perPage *int,
    page *int,
    name *string,
    tag *string) (
    models.ApiResponse[models.InstrumentsListResult],
    error) {
    req := c.prepareRequest(ctx, "GET", "/v2/ai/audio/instruments")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if id != nil {
        req.QueryParam("id", id)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if name != nil {
        req.QueryParam("name", *name)
    }
    if tag != nil {
        req.QueryParam("tag", *tag)
    }
    var result models.InstrumentsListResult
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.InstrumentsListResult](decoder)
    return models.NewApiResponse(result, resp), err
}

// FetchRenders takes context, id as parameters and
// returns an models.ApiResponse with models.AudioRendersListResults data and
// an error if there was an issue with the request or response.
// This endpoint shows the status of one or more audio renders, including download links for completed audio.
func (c *CustomMusicController) FetchRenders(
    ctx context.Context,
    id []string) (
    models.ApiResponse[models.AudioRendersListResults],
    error) {
    req := c.prepareRequest(ctx, "GET", "/v2/ai/audio/renders")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Not Found"},
    })
    req.QueryParam("id", id)
    var result models.AudioRendersListResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.AudioRendersListResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// CreateAudioRenders takes context, body as parameters and
// returns an models.ApiResponse with models.AudioRendersListResults data and
// an error if there was an issue with the request or response.
// This endpoint creates rendered audio from timeline data. It returns a render ID that you can use to download the finished audio when it is ready. The render ID is valid for up to 48 hours.
func (c *CustomMusicController) CreateAudioRenders(
    ctx context.Context,
    body models.CreateAudioRendersRequest) (
    models.ApiResponse[models.AudioRendersListResults],
    error) {
    req := c.prepareRequest(ctx, "POST", "/v2/ai/audio/renders")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    var result models.AudioRendersListResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.AudioRendersListResults](decoder)
    return models.NewApiResponse(result, resp), err
}
