// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "github.com/apimatic/go-core-runtime/testHelper"
    "shutterstockapiexplorer/models"
    "testing"
    "time"
)

// TestEditorialVideoControllerTestListEditorialVideoCategories tests the behavior of the EditorialVideoController
func TestEditorialVideoControllerTestListEditorialVideoCategories(t *testing.T) {
    ctx := context.Background()
    apiResponse, err := editorialVideoController.ListEditorialVideoCategories(ctx)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/EditorialVideoCategoryResults/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestEditorialVideoControllerTestGetEditorialVideoLicenseList tests the behavior of the EditorialVideoController
func TestEditorialVideoControllerTestGetEditorialVideoLicenseList(t *testing.T) {
    ctx := context.Background()
    videoId := "12345678"
    license := "premier_editorial_all_media"
    page := int(1)
    perPage := int(20)
    sort := models.Sort1Enum("newest")
    username := "aUniqueUsername"
    startDate, errTime := time.Parse(time.RFC3339, "2021-03-29T13:25:13.521Z")
    if errTime != nil {
        t.Error(errTime)
    }
    endDate, errTime := time.Parse(time.RFC3339, "2021-03-29T13:25:13.521Z")
    if errTime != nil {
        t.Error(errTime)
    }
    downloadAvailability := models.DownloadAvailabilityEnum("all")
    teamHistory := bool(false)
    apiResponse, err := editorialVideoController.GetEditorialVideoLicenseList(ctx, &videoId, &license, &page, &perPage, &sort, &username, &startDate, &endDate, &downloadAvailability, &teamHistory)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"data":[{"download_time":"2020-12-18T02:22:56.000Z","id":"e1dbb15d5384725d292cf64f793ac45062","is_downloadable":false,"license":"premier_editorial_all_digital","metadata":{"client":"Company A","job":"Important project","other":"Important media","purchase_order":"457234"},"subscription_id":"s12345678","user":{"username":"username1"},"video":{"format":{"size":"original"},"id":"11231389im"}},{"download_time":"2020-12-11T01:24:22.000Z","id":"e1dbb15d5384725d292cf64f793ac45114","is_downloadable":false,"license":"premier_editorial_all_digital","metadata":{"client":"Company B","job":"Important project","other":"Important image","purchase_order":"5583831"},"subscription_id":"s12345678","user":{"username":"username2"},"video":{"format":{"size":"original"},"id":"11231442aa"}}],"page":1,"per_page":2}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}
