// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "github.com/apimatic/go-core-runtime/https"
    "github.com/apimatic/go-core-runtime/utilities"
    "shutterstockapiexplorer/models"
    "time"
)

// EditorialImagesController represents a controller struct.
type EditorialImagesController struct {
    baseController
}

// NewEditorialImagesController creates a new instance of EditorialImagesController.
// It takes a baseController as a parameter and returns a pointer to the EditorialImagesController.
func NewEditorialImagesController(baseController baseController) *EditorialImagesController {
    editorialImagesController := EditorialImagesController{baseController: baseController}
    return &editorialImagesController
}

// GetEditorialCategories takes context as parameters and
// returns an models.ApiResponse with models.EditorialCategoryResults data and
// an error if there was an issue with the request or response.
// Deprecated: getEditorialCategories is deprecated
// Deprecated; use `GET /v2/editorial/images/categories` instead. This endpoint lists the categories that editorial images can belong to, which are separate from the categories that other types of assets can belong to.
func (e *EditorialImagesController) GetEditorialCategories(ctx context.Context) (
    models.ApiResponse[models.EditorialCategoryResults],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/categories")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    var result models.EditorialCategoryResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialCategoryResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// ListEditorialImageCategories takes context as parameters and
// returns an models.ApiResponse with models.EditorialImageCategoryResults data and
// an error if there was an issue with the request or response.
// This endpoint lists the categories that editorial images can belong to, which are separate from the categories that other types of assets can belong to.
func (e *EditorialImagesController) ListEditorialImageCategories(ctx context.Context) (
    models.ApiResponse[models.EditorialImageCategoryResults],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/images/categories")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    var result models.EditorialImageCategoryResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialImageCategoryResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetEditorialImageLicenseList takes context, imageId, license, page, perPage, sort, username, startDate, endDate, downloadAvailability, teamHistory as parameters and
// returns an models.ApiResponse with models.DownloadHistoryDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists existing editorial image licenses.
func (e *EditorialImagesController) GetEditorialImageLicenseList(
    ctx context.Context,
    imageId *string,
    license *string,
    page *int,
    perPage *int,
    sort *models.Sort1Enum,
    username *string,
    startDate *time.Time,
    endDate *time.Time,
    downloadAvailability *models.DownloadAvailabilityEnum,
    teamHistory *bool) (
    models.ApiResponse[models.DownloadHistoryDataList],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/images/licenses")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if imageId != nil {
        req.QueryParam("image_id", *imageId)
    }
    if license != nil {
        req.QueryParam("license", *license)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if username != nil {
        req.QueryParam("username", *username)
    }
    if startDate != nil {
        req.QueryParam("start_date", startDate.Format(time.RFC3339))
    }
    if endDate != nil {
        req.QueryParam("end_date", endDate.Format(time.RFC3339))
    }
    if downloadAvailability != nil {
        req.QueryParam("download_availability", *downloadAvailability)
    }
    if teamHistory != nil {
        req.QueryParam("team_history", *teamHistory)
    }
    var result models.DownloadHistoryDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.DownloadHistoryDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// LicenseEditorialImages takes context, body as parameters and
// returns an models.ApiResponse with models.LicenseEditorialContentResults data and
// an error if there was an issue with the request or response.
// This endpoint gets licenses for one or more editorial images. You must specify the country and one or more editorial images to license. The download links in the response are valid for 8 hours.
func (e *EditorialImagesController) LicenseEditorialImages(
    ctx context.Context,
    body models.LicenseEditorialContentRequest) (
    models.ApiResponse[models.LicenseEditorialContentResults],
    error) {
    req := e.prepareRequest(ctx, "POST", "/v2/editorial/images/licenses")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "406": {Message: "Not Acceptable"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    var result models.LicenseEditorialContentResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.LicenseEditorialContentResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetEditorialImageLivefeedList takes context, country, page, perPage as parameters and
// returns an models.ApiResponse with models.EditorialImageLivefeedList data and
// an error if there was an issue with the request or response.
func (e *EditorialImagesController) GetEditorialImageLivefeedList(
    ctx context.Context,
    country string,
    page *int,
    perPage *int) (
    models.ApiResponse[models.EditorialImageLivefeedList],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/images/livefeeds")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Not Found"},
    })
    req.QueryParam("country", country)
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    var result models.EditorialImageLivefeedList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialImageLivefeedList](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetEditorialImageLivefeed takes context, id, country as parameters and
// returns an models.ApiResponse with models.EditorialImageLivefeed data and
// an error if there was an issue with the request or response.
func (e *EditorialImagesController) GetEditorialImageLivefeed(
    ctx context.Context,
    id string,
    country string) (
    models.ApiResponse[models.EditorialImageLivefeed],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/images/livefeeds/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Not Found"},
    })
    req.QueryParam("country", country)
    
    var result models.EditorialImageLivefeed
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialImageLivefeed](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetEditorialImageLivefeedItems takes context, id, country as parameters and
// returns an models.ApiResponse with models.EditorialImageContentDataList data and
// an error if there was an issue with the request or response.
func (e *EditorialImagesController) GetEditorialImageLivefeedItems(
    ctx context.Context,
    id string,
    country string) (
    models.ApiResponse[models.EditorialImageContentDataList],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/images/livefeeds/%v/items")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Not Found"},
    })
    req.QueryParam("country", country)
    
    var result models.EditorialImageContentDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialImageContentDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// SearchEditorialImages takes context, country, query, sort, category, supplierCode, dateStart, dateEnd, perPage, cursor as parameters and
// returns an models.ApiResponse with models.EditorialSearchResults data and
// an error if there was an issue with the request or response.
// This endpoint searches for editorial images. If you specify more than one search parameter, the API uses an AND condition. For example, if you set the `category` parameter to "Alone,Performing" and also specify a `query` parameter, the results include only images that match the query and are in both the Alone and Performing categories. You can also filter search terms out in the `query` parameter by prefixing the term with NOT.
func (e *EditorialImagesController) SearchEditorialImages(
    ctx context.Context,
    country string,
    query *string,
    sort *models.Sort10Enum,
    category *string,
    supplierCode []string,
    dateStart *time.Time,
    dateEnd *time.Time,
    perPage *int,
    cursor *string) (
    models.ApiResponse[models.EditorialSearchResults],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/images/search")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "406": {Message: "Not Acceptable"},
    })
    req.QueryParam("country", country)
    if query != nil {
        req.QueryParam("query", *query)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if category != nil {
        req.QueryParam("category", *category)
    }
    if supplierCode != nil {
        req.QueryParam("supplier_code", supplierCode)
    }
    if dateStart != nil {
        req.QueryParam("date_start", dateStart.Format(models.DEFAULT_DATE))
    }
    if dateEnd != nil {
        req.QueryParam("date_end", dateEnd.Format(models.DEFAULT_DATE))
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if cursor != nil {
        req.QueryParam("cursor", *cursor)
    }
    var result models.EditorialSearchResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialSearchResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetUpdatedEditorialImages takes context, mType, dateUpdatedStart, dateUpdatedEnd, country, dateTakenStart, dateTakenEnd, cursor, sort, supplierCode, perPage as parameters and
// returns an models.ApiResponse with models.EditorialUpdatedResults data and
// an error if there was an issue with the request or response.
// This endpoint lists editorial images that have been updated in the specified time period to update content management systems (CMS) or digital asset management (DAM) systems. In most cases, use the date_updated_start and date_updated_end parameters to specify a range updates based on when the updates happened. You can also use the date_taken_start and date_taken_end parameters to specify a range of updates based on when the image was taken.
func (e *EditorialImagesController) GetUpdatedEditorialImages(
    ctx context.Context,
    mType models.Type2Enum,
    dateUpdatedStart time.Time,
    dateUpdatedEnd time.Time,
    country string,
    dateTakenStart *time.Time,
    dateTakenEnd *time.Time,
    cursor *string,
    sort *models.Sort1Enum,
    supplierCode []string,
    perPage *int) (
    models.ApiResponse[models.EditorialUpdatedResults],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/images/updated")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "406": {Message: "Not Acceptable"},
    })
    req.QueryParam("type", mType)
    req.QueryParam("date_updated_start", dateUpdatedStart.Format(time.RFC3339))
    req.QueryParam("date_updated_end", dateUpdatedEnd.Format(time.RFC3339))
    req.QueryParam("country", country)
    if dateTakenStart != nil {
        req.QueryParam("date_taken_start", dateTakenStart.Format(models.DEFAULT_DATE))
    }
    if dateTakenEnd != nil {
        req.QueryParam("date_taken_end", dateTakenEnd.Format(models.DEFAULT_DATE))
    }
    if cursor != nil {
        req.QueryParam("cursor", *cursor)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if supplierCode != nil {
        req.QueryParam("supplier_code", supplierCode)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    var result models.EditorialUpdatedResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialUpdatedResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetEditorialImage takes context, id, country as parameters and
// returns an models.ApiResponse with models.EditorialContent data and
// an error if there was an issue with the request or response.
// This endpoint shows information about an editorial image, including a URL to a preview image and the sizes that it is available in.
func (e *EditorialImagesController) GetEditorialImage(
    ctx context.Context,
    id string,
    country string) (
    models.ApiResponse[models.EditorialContent],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/images/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Not Found"},
    })
    req.QueryParam("country", country)
    
    var result models.EditorialContent
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialContent](decoder)
    return models.NewApiResponse(result, resp), err
}

// LicenseEditorialImage takes context, body as parameters and
// returns an models.ApiResponse with models.LicenseEditorialContentResults data and
// an error if there was an issue with the request or response.
// Deprecated: licenseEditorialImage is deprecated
// Deprecated; use `POST /v2/editorial/images/licenses` instead to get licenses for one or more editorial images. You must specify the country and one or more editorial images to license. The download links in the response are valid for 8 hours.
func (e *EditorialImagesController) LicenseEditorialImage(
    ctx context.Context,
    body models.LicenseEditorialContentRequest) (
    models.ApiResponse[models.LicenseEditorialContentResults],
    error) {
    req := e.prepareRequest(ctx, "POST", "/v2/editorial/licenses")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "406": {Message: "Not Acceptable"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    var result models.LicenseEditorialContentResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.LicenseEditorialContentResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetEditorialLivefeedList takes context, country, page, perPage as parameters and
// returns an models.ApiResponse with models.EditorialLivefeedList data and
// an error if there was an issue with the request or response.
// Deprecated: getEditorialLivefeedList is deprecated
// Deprecated; use `GET /v2/editorial/images/livefeeds` instead to get a list of editorial livefeeds.
func (e *EditorialImagesController) GetEditorialLivefeedList(
    ctx context.Context,
    country string,
    page *int,
    perPage *int) (
    models.ApiResponse[models.EditorialLivefeedList],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/livefeeds")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "406": {Message: "Not Acceptable"},
    })
    req.QueryParam("country", country)
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    var result models.EditorialLivefeedList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialLivefeedList](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetEditorialLivefeed takes context, id, country as parameters and
// returns an models.ApiResponse with models.EditorialLivefeed data and
// an error if there was an issue with the request or response.
// Deprecated: getEditorialLivefeed is deprecated
// Deprecated: use `GET /v2/editorial/images/livefeeds/{id}` instead to get an editorial livefeed.
func (e *EditorialImagesController) GetEditorialLivefeed(
    ctx context.Context,
    id string,
    country string) (
    models.ApiResponse[models.EditorialLivefeed],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/livefeeds/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "406": {Message: "Not Acceptable"},
    })
    req.QueryParam("country", country)
    
    var result models.EditorialLivefeed
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialLivefeed](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetEditorialLivefeedItems takes context, id, country as parameters and
// returns an models.ApiResponse with models.EditorialContentDataList data and
// an error if there was an issue with the request or response.
// Deprecated: getEditorialLivefeedItems is deprecated
// Deprecated; use `GET /v2/editorial/images/livefeeds/{id}/items` instead to get editorial livefeed items.
func (e *EditorialImagesController) GetEditorialLivefeedItems(
    ctx context.Context,
    id string,
    country string) (
    models.ApiResponse[models.EditorialContentDataList],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/livefeeds/%v/items")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "406": {Message: "Not Acceptable"},
    })
    req.QueryParam("country", country)
    
    var result models.EditorialContentDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialContentDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// SearchEditorial takes context, country, query, sort, category, supplierCode, dateStart, dateEnd, perPage, cursor as parameters and
// returns an models.ApiResponse with models.EditorialSearchResults data and
// an error if there was an issue with the request or response.
// Deprecated: searchEditorial is deprecated
// Deprecated; use `GET /v2/editorial/images/search` instead to search for editorial images.
func (e *EditorialImagesController) SearchEditorial(
    ctx context.Context,
    country string,
    query *string,
    sort *models.Sort10Enum,
    category *string,
    supplierCode []string,
    dateStart *time.Time,
    dateEnd *time.Time,
    perPage *int,
    cursor *string) (
    models.ApiResponse[models.EditorialSearchResults],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/search")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "406": {Message: "Not Acceptable"},
    })
    req.QueryParam("country", country)
    if query != nil {
        req.QueryParam("query", *query)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if category != nil {
        req.QueryParam("category", *category)
    }
    if supplierCode != nil {
        req.QueryParam("supplier_code", supplierCode)
    }
    if dateStart != nil {
        req.QueryParam("date_start", dateStart.Format(models.DEFAULT_DATE))
    }
    if dateEnd != nil {
        req.QueryParam("date_end", dateEnd.Format(models.DEFAULT_DATE))
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if cursor != nil {
        req.QueryParam("cursor", *cursor)
    }
    var result models.EditorialSearchResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialSearchResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetUpdatedEditorialImage takes context, mType, dateUpdatedStart, dateUpdatedEnd, country, dateTakenStart, dateTakenEnd, cursor, sort, supplierCode, perPage as parameters and
// returns an models.ApiResponse with models.EditorialUpdatedResults data and
// an error if there was an issue with the request or response.
// Deprecated: getUpdatedEditorialImage is deprecated
// Deprecated; use `GET /v2/editorial/images/updated` instead to get recently updated items.
func (e *EditorialImagesController) GetUpdatedEditorialImage(
    ctx context.Context,
    mType models.Type2Enum,
    dateUpdatedStart time.Time,
    dateUpdatedEnd time.Time,
    country string,
    dateTakenStart *time.Time,
    dateTakenEnd *time.Time,
    cursor *string,
    sort *models.Sort1Enum,
    supplierCode []string,
    perPage *int) (
    models.ApiResponse[models.EditorialUpdatedResults],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/updated")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "406": {Message: "Not Acceptable"},
    })
    req.QueryParam("type", mType)
    req.QueryParam("date_updated_start", dateUpdatedStart.Format(time.RFC3339))
    req.QueryParam("date_updated_end", dateUpdatedEnd.Format(time.RFC3339))
    req.QueryParam("country", country)
    if dateTakenStart != nil {
        req.QueryParam("date_taken_start", dateTakenStart.Format(models.DEFAULT_DATE))
    }
    if dateTakenEnd != nil {
        req.QueryParam("date_taken_end", dateTakenEnd.Format(models.DEFAULT_DATE))
    }
    if cursor != nil {
        req.QueryParam("cursor", *cursor)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if supplierCode != nil {
        req.QueryParam("supplier_code", supplierCode)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    var result models.EditorialUpdatedResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialUpdatedResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// DeprecatedGetEditorialContentDetails takes context, id, country, searchId as parameters and
// returns an models.ApiResponse with models.EditorialContent data and
// an error if there was an issue with the request or response.
// Deprecated: (Deprecated) Get editorial content details is deprecated
// Deprecated; use `GET /v2/editorial/images/{id}` instead to show information about an editorial image, including a URL to a preview image and the sizes that it is available in.
func (e *EditorialImagesController) DeprecatedGetEditorialContentDetails(
    ctx context.Context,
    id string,
    country string,
    searchId *string) (
    models.ApiResponse[models.EditorialContent],
    error) {
    req := e.prepareRequest(ctx, "GET", "/v2/editorial/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Not Found"},
    })
    req.QueryParam("country", country)
    if searchId != nil {
        req.QueryParam("search_id", *searchId)
    }
    
    var result models.EditorialContent
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.EditorialContent](decoder)
    return models.NewApiResponse(result, resp), err
}
