// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "github.com/apimatic/go-core-runtime/testHelper"
    "shutterstockapiexplorer/models"
    "testing"
    "time"
)

// TestEditorialImagesControllerTestGetEditorialCategories tests the behavior of the EditorialImagesController
func TestEditorialImagesControllerTestGetEditorialCategories(t *testing.T) {
    ctx := context.Background()
    apiResponse, err := editorialImagesController.GetEditorialCategories(ctx)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/EditorialCategoryResults/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestEditorialImagesControllerTestListEditorialImageCategories tests the behavior of the EditorialImagesController
func TestEditorialImagesControllerTestListEditorialImageCategories(t *testing.T) {
    ctx := context.Background()
    apiResponse, err := editorialImagesController.ListEditorialImageCategories(ctx)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/EditorialImageCategoryResults/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestEditorialImagesControllerTestGetEditorialImageLicenseList tests the behavior of the EditorialImagesController
func TestEditorialImagesControllerTestGetEditorialImageLicenseList(t *testing.T) {
    ctx := context.Background()
    imageId := "12345678"
    license := "premier_editorial_all_digital"
    page := int(1)
    perPage := int(20)
    sort := models.Sort1Enum("newest")
    username := "aUniqueUsername"
    startDate, errTime := time.Parse(time.RFC3339, "2021-03-29T13:25:13.521Z")
    if errTime != nil {
        t.Error(errTime)
    }
    endDate, errTime := time.Parse(time.RFC3339, "2021-03-29T13:25:13.521Z")
    if errTime != nil {
        t.Error(errTime)
    }
    downloadAvailability := models.DownloadAvailabilityEnum("all")
    teamHistory := bool(false)
    apiResponse, err := editorialImagesController.GetEditorialImageLicenseList(ctx, &imageId, &license, &page, &perPage, &sort, &username, &startDate, &endDate, &downloadAvailability, &teamHistory)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/DownloadHistoryDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestEditorialImagesControllerTestGetEditorialImageLivefeedItems tests the behavior of the EditorialImagesController
func TestEditorialImagesControllerTestGetEditorialImageLivefeedItems(t *testing.T) {
    ctx := context.Background()
    id := "2018%2F10%2F15%2FWomen%20of%20the%20Year%20Lunch%20%26%20Awards%2C%20London"
    country := "USA"
    apiResponse, err := editorialImagesController.GetEditorialImageLivefeedItems(ctx, id, country)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/EditorialImageContentDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestEditorialImagesControllerTestGetEditorialLivefeedItems tests the behavior of the EditorialImagesController
func TestEditorialImagesControllerTestGetEditorialLivefeedItems(t *testing.T) {
    ctx := context.Background()
    id := "2018%2F10%2F15%2FWomen%20of%20the%20Year%20Lunch%20%26%20Awards%2C%20London"
    country := "USA"
    apiResponse, err := editorialImagesController.GetEditorialLivefeedItems(ctx, id, country)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/EditorialContentDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}
