// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "encoding/json"
    "github.com/apimatic/go-core-runtime/testHelper"
    "shutterstockapiexplorer/models"
    "testing"
    "time"
)

// TestImagesControllerTestGetImageList tests the behavior of the ImagesController
func TestImagesControllerTestGetImageList(t *testing.T) {
    ctx := context.Background()
    id := []string{ "1110335168","465011609" }
    view := models.View1Enum("minimal")
    searchId := "00000000-0000-0000-0000-000000000000"
    apiResponse, err := imagesController.GetImageList(ctx, id, &view, &searchId)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/ImageDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestImagesControllerTestListImageCategories tests the behavior of the ImagesController
func TestImagesControllerTestListImageCategories(t *testing.T) {
    ctx := context.Background()
    language := models.LanguageEnum("es")
    apiResponse, err := imagesController.ListImageCategories(ctx, &language)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/CategoryDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestImagesControllerTestGetImageCollectionList tests the behavior of the ImagesController
func TestImagesControllerTestGetImageCollectionList(t *testing.T) {
    ctx := context.Background()
    
    page := int(1)
    perPage := int(100)
    apiResponse, err := imagesController.GetImageCollectionList(ctx, nil, &page, &perPage)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/CollectionDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestImagesControllerTestGetFeaturedImageCollectionList tests the behavior of the ImagesController
func TestImagesControllerTestGetFeaturedImageCollectionList(t *testing.T) {
    ctx := context.Background()
    embed := models.Embed3Enum("share_url")
    mType := []models.Type4Enum{ "photo" }
    assetHint := models.AssetHintEnum("1x")
    apiResponse, err := imagesController.GetFeaturedImageCollectionList(ctx, &embed, mType, &assetHint)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/FeaturedCollectionDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestImagesControllerTestGetFeaturedImageCollectionItems tests the behavior of the ImagesController
func TestImagesControllerTestGetFeaturedImageCollectionItems(t *testing.T) {
    ctx := context.Background()
    id := "136351027"
    page := int(1)
    perPage := int(100)
    apiResponse, err := imagesController.GetFeaturedImageCollectionItems(ctx, id, &page, &perPage)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/CollectionItemDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestImagesControllerTestDeleteImageCollection tests the behavior of the ImagesController
func TestImagesControllerTestDeleteImageCollection(t *testing.T) {
    ctx := context.Background()
    id := "136351027"
    resp, err := imagesController.DeleteImageCollection(ctx, id)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, resp.StatusCode, 204)
}

// TestImagesControllerTestDeleteImageCollectionItems tests the behavior of the ImagesController
func TestImagesControllerTestDeleteImageCollectionItems(t *testing.T) {
    ctx := context.Background()
    id := "126351027"
    
    resp, err := imagesController.DeleteImageCollectionItems(ctx, id, nil)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, resp.StatusCode, 204)
}

// TestImagesControllerTestGetImageCollectionItems tests the behavior of the ImagesController
func TestImagesControllerTestGetImageCollectionItems(t *testing.T) {
    ctx := context.Background()
    id := "126351027"
    page := int(1)
    perPage := int(100)
    
    sort := models.Sort1Enum("oldest")
    apiResponse, err := imagesController.GetImageCollectionItems(ctx, id, &page, &perPage, nil, &sort)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/CollectionItemDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestImagesControllerTestAddImageCollectionItems tests the behavior of the ImagesController
func TestImagesControllerTestAddImageCollectionItems(t *testing.T) {
    ctx := context.Background()
    id := "126351027"
    var body models.CollectionItemRequest
    errBody := json.Unmarshal([]byte(`{"items":[{"id":"49572945"}]}`), &body)
    if errBody != nil {
        t.Errorf("Cannot parse the model object.")
    }
    resp, err := imagesController.AddImageCollectionItems(ctx, id, body)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, resp.StatusCode, 204)
}

// TestImagesControllerTestGetImageLicenseList tests the behavior of the ImagesController
func TestImagesControllerTestGetImageLicenseList(t *testing.T) {
    ctx := context.Background()
    imageId := "12345678"
    license := "standard"
    page := int(1)
    perPage := int(20)
    sort := models.Sort1Enum("newest")
    username := "aUniqueUsername"
    startDate, errTime := time.Parse(time.RFC3339, "2021-03-29T13:25:13.521Z")
    if errTime != nil {
        t.Error(errTime)
    }
    endDate, errTime := time.Parse(time.RFC3339, "2021-03-29T13:25:13.521Z")
    if errTime != nil {
        t.Error(errTime)
    }
    downloadAvailability := models.DownloadAvailabilityEnum("all")
    teamHistory := bool(false)
    apiResponse, err := imagesController.GetImageLicenseList(ctx, &imageId, &license, &page, &perPage, &sort, &username, &startDate, &endDate, &downloadAvailability, &teamHistory)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/DownloadHistoryDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestImagesControllerTestGetImageRecommendations tests the behavior of the ImagesController
func TestImagesControllerTestGetImageRecommendations(t *testing.T) {
    ctx := context.Background()
    id := []string{ 465011609 }
    maxItems := int(20)
    safe := bool(true)
    apiResponse, err := imagesController.GetImageRecommendations(ctx, id, &maxItems, &safe)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/RecommendationDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestImagesControllerTestGetImageSuggestions tests the behavior of the ImagesController
func TestImagesControllerTestGetImageSuggestions(t *testing.T) {
    ctx := context.Background()
    query := "cats"
    limit := int(10)
    apiResponse, err := imagesController.GetImageSuggestions(ctx, query, &limit)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/Suggestions/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}

// TestImagesControllerTestGetUpdatedImages tests the behavior of the ImagesController
func TestImagesControllerTestGetUpdatedImages(t *testing.T) {
    ctx := context.Background()
    
    startDate, errTime := time.Parse(models.DEFAULT_DATE, "2021-03-29")
    if errTime != nil {
        t.Error(errTime)
    }
    endDate, errTime := time.Parse(models.DEFAULT_DATE, "2021-03-29")
    if errTime != nil {
        t.Error(errTime)
    }
    interval := "1 HOUR"
    page := int(1)
    perPage := int(100)
    sort := models.Sort1Enum("newest")
    apiResponse, err := imagesController.GetUpdatedImages(ctx, nil, &startDate, &endDate, &interval, &page, &perPage, &sort)
    if err != nil {
        t.Errorf("Endpoint call failed: %v", err)
    }
    testHelper.CheckResponseStatusCode(t, apiResponse.Response.StatusCode, 200)
    expectedHeaders:= []testHelper.TestHeader{
        testHelper.NewTestHeader(true,"Content-Type","application/json"),
    }
    testHelper.CheckResponseHeaders(t, apiResponse.Response.Header, expectedHeaders, true)
    expected := `{"$ref":"#/components/schemas/UpdatedMediaDataList/example"}`
    testHelper.KeysBodyMatcher(t, expected, apiResponse.Response.Body, false, false)
}
