// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "github.com/apimatic/go-core-runtime/https"
    "github.com/apimatic/go-core-runtime/utilities"
    "net/http"
    "shutterstockapiexplorer/models"
    "time"
)

// ImagesController represents a controller struct.
type ImagesController struct {
    baseController
}

// NewImagesController creates a new instance of ImagesController.
// It takes a baseController as a parameter and returns a pointer to the ImagesController.
func NewImagesController(baseController baseController) *ImagesController {
    imagesController := ImagesController{baseController: baseController}
    return &imagesController
}

// BulkSearchImages takes context, body, addedDate, addedDateStart, aspectRatioMin, aspectRatioMax, aspectRatio, addedDateEnd, category, color, contributor, contributorCountry, fields, height, heightFrom, heightTo, imageType, keywordSafeSearch, language, license, model, orientation, page, perPage, peopleModelReleased, peopleAge, peopleEthnicity, peopleGender, peopleNumber, region, safe, sort, spellcheckQuery, view, width, widthFrom, widthTo as parameters and
// returns an models.ApiResponse with models.BulkImageSearchResults data and
// an error if there was an issue with the request or response.
// This endpoint runs up to 5 image searches in a single request and returns up to 20 results per search. You can provide global search parameters in the query parameters and override them for each search in the body parameter. The query and body parameters are the same as in the `GET /v2/images/search` endpoint.
func (i *ImagesController) BulkSearchImages(
    ctx context.Context,
    body []models.SearchImage,
    addedDate *time.Time,
    addedDateStart *time.Time,
    aspectRatioMin *float64,
    aspectRatioMax *float64,
    aspectRatio *float64,
    addedDateEnd *time.Time,
    category *string,
    color *string,
    contributor []string,
    contributorCountry *models.BulkSearchImagesContributorCountry,
    fields *string,
    height *int,
    heightFrom *int,
    heightTo *int,
    imageType []models.ImageType1Enum,
    keywordSafeSearch *bool,
    language *models.LanguageEnum,
    license []models.LicenseEnum,
    model []string,
    orientation *models.Orientation1Enum,
    page *int,
    perPage *int,
    peopleModelReleased *bool,
    peopleAge *models.PeopleAge1Enum,
    peopleEthnicity []models.PeopleEthnicity1Enum,
    peopleGender *models.PeopleGender1Enum,
    peopleNumber *int,
    region *models.BulkSearchImagesRegion,
    safe *bool,
    sort *models.Sort4Enum,
    spellcheckQuery *bool,
    view *models.View1Enum,
    width *int,
    widthFrom *int,
    widthTo *int) (
    models.ApiResponse[models.BulkImageSearchResults],
    error) {
    req := i.prepareRequest(ctx, "POST", "/v2/bulk_search/images")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.Header("Content-Type", "application/json")
    if addedDate != nil {
        req.QueryParam("added_date", addedDate.Format(models.DEFAULT_DATE))
    }
    if addedDateStart != nil {
        req.QueryParam("added_date_start", addedDateStart.Format(models.DEFAULT_DATE))
    }
    if aspectRatioMin != nil {
        req.QueryParam("aspect_ratio_min", *aspectRatioMin)
    }
    if aspectRatioMax != nil {
        req.QueryParam("aspect_ratio_max", *aspectRatioMax)
    }
    if aspectRatio != nil {
        req.QueryParam("aspect_ratio", *aspectRatio)
    }
    if addedDateEnd != nil {
        req.QueryParam("added_date_end", addedDateEnd.Format(models.DEFAULT_DATE))
    }
    if category != nil {
        req.QueryParam("category", *category)
    }
    if color != nil {
        req.QueryParam("color", *color)
    }
    if contributor != nil {
        req.QueryParam("contributor", contributor)
    }
    if contributorCountry != nil {
        req.QueryParam("contributor_country", *contributorCountry)
    }
    if fields != nil {
        req.QueryParam("fields", *fields)
    }
    if height != nil {
        req.QueryParam("height", *height)
    }
    if heightFrom != nil {
        req.QueryParam("height_from", *heightFrom)
    }
    if heightTo != nil {
        req.QueryParam("height_to", *heightTo)
    }
    if imageType != nil {
        req.QueryParam("image_type", imageType)
    }
    if keywordSafeSearch != nil {
        req.QueryParam("keyword_safe_search", *keywordSafeSearch)
    }
    if language != nil {
        req.QueryParam("language", *language)
    }
    if license != nil {
        req.QueryParam("license", license)
    }
    if model != nil {
        req.QueryParam("model", model)
    }
    if orientation != nil {
        req.QueryParam("orientation", *orientation)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if peopleModelReleased != nil {
        req.QueryParam("people_model_released", *peopleModelReleased)
    }
    if peopleAge != nil {
        req.QueryParam("people_age", *peopleAge)
    }
    if peopleEthnicity != nil {
        req.QueryParam("people_ethnicity", peopleEthnicity)
    }
    if peopleGender != nil {
        req.QueryParam("people_gender", *peopleGender)
    }
    if peopleNumber != nil {
        req.QueryParam("people_number", *peopleNumber)
    }
    if region != nil {
        req.QueryParam("region", *region)
    }
    if safe != nil {
        req.QueryParam("safe", *safe)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if spellcheckQuery != nil {
        req.QueryParam("spellcheck_query", *spellcheckQuery)
    }
    if view != nil {
        req.QueryParam("view", *view)
    }
    if width != nil {
        req.QueryParam("width", *width)
    }
    if widthFrom != nil {
        req.QueryParam("width_from", *widthFrom)
    }
    if widthTo != nil {
        req.QueryParam("width_to", *widthTo)
    }
    req.Json(&body)
    var result models.BulkImageSearchResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.BulkImageSearchResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetImageList takes context, id, view, searchId as parameters and
// returns an models.ApiResponse with models.ImageDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists information about one or more images, including the available sizes.
func (i *ImagesController) GetImageList(
    ctx context.Context,
    id []string,
    view *models.View1Enum,
    searchId *string) (
    models.ApiResponse[models.ImageDataList],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.QueryParam("id", id)
    if view != nil {
        req.QueryParam("view", *view)
    }
    if searchId != nil {
        req.QueryParam("search_id", *searchId)
    }
    var result models.ImageDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.ImageDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// ListImageCategories takes context, language as parameters and
// returns an models.ApiResponse with models.CategoryDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists the categories (Shutterstock-assigned genres) that images can belong to.
func (i *ImagesController) ListImageCategories(
    ctx context.Context,
    language *models.LanguageEnum) (
    models.ApiResponse[models.CategoryDataList],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/categories")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if language != nil {
        req.QueryParam("language", *language)
    }
    var result models.CategoryDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CategoryDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetImageCollectionList takes context, embed, page, perPage as parameters and
// returns an models.ApiResponse with models.CollectionDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists your collections of images and their basic attributes.
func (i *ImagesController) GetImageCollectionList(
    ctx context.Context,
    embed []models.EmbedEnum,
    page *int,
    perPage *int) (
    models.ApiResponse[models.CollectionDataList],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/collections")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if embed != nil {
        req.QueryParam("embed", embed)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    var result models.CollectionDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CollectionDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// CreateImageCollection takes context, body as parameters and
// returns an models.ApiResponse with models.CollectionCreateResponse data and
// an error if there was an issue with the request or response.
// This endpoint creates one or more image collections (lightboxes). To add images to the collections, use `POST /v2/images/collections/{id}/items`.
func (i *ImagesController) CreateImageCollection(
    ctx context.Context,
    body models.CollectionCreateRequest) (
    models.ApiResponse[models.CollectionCreateResponse],
    error) {
    req := i.prepareRequest(ctx, "POST", "/v2/images/collections")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    var result models.CollectionCreateResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CollectionCreateResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetFeaturedImageCollectionList takes context, embed, mType, assetHint as parameters and
// returns an models.ApiResponse with models.FeaturedCollectionDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists featured collections of specific types and a name and cover image for each collection.
func (i *ImagesController) GetFeaturedImageCollectionList(
    ctx context.Context,
    embed *models.Embed3Enum,
    mType []models.Type4Enum,
    assetHint *models.AssetHintEnum) (
    models.ApiResponse[models.FeaturedCollectionDataList],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/collections/featured")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if embed != nil {
        req.QueryParam("embed", *embed)
    }
    if mType != nil {
        req.QueryParam("type", mType)
    }
    if assetHint != nil {
        req.QueryParam("asset_hint", *assetHint)
    }
    var result models.FeaturedCollectionDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.FeaturedCollectionDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetFeaturedImageCollection takes context, id, embed, assetHint as parameters and
// returns an models.ApiResponse with models.FeaturedCollection data and
// an error if there was an issue with the request or response.
// This endpoint gets more detailed information about a featured collection, including its cover image and timestamps for its creation and most recent update. To get the images, use `GET /v2/images/collections/featured/{id}/items`.
func (i *ImagesController) GetFeaturedImageCollection(
    ctx context.Context,
    id string,
    embed *models.Embed3Enum,
    assetHint *models.AssetHintEnum) (
    models.ApiResponse[models.FeaturedCollection],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/collections/featured/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Featured collection not found"},
    })
    if embed != nil {
        req.QueryParam("embed", *embed)
    }
    if assetHint != nil {
        req.QueryParam("asset_hint", *assetHint)
    }
    
    var result models.FeaturedCollection
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.FeaturedCollection](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetFeaturedImageCollectionItems takes context, id, page, perPage as parameters and
// returns an models.ApiResponse with models.CollectionItemDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists the IDs of images in a featured collection and the date that each was added.
func (i *ImagesController) GetFeaturedImageCollectionItems(
    ctx context.Context,
    id string,
    page *int,
    perPage *int) (
    models.ApiResponse[models.CollectionItemDataList],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/collections/featured/%v/items")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Featured collection not found"},
    })
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    
    var result models.CollectionItemDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CollectionItemDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// DeleteImageCollection takes context, id as parameters and
// returns an *Response and
// an error if there was an issue with the request or response.
// This endpoint deletes an image collection.
func (i *ImagesController) DeleteImageCollection(
    ctx context.Context,
    id string) (
    *http.Response,
    error) {
    req := i.prepareRequest(ctx, "DELETE", "/v2/images/collections/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    
    httpCtx, err := req.Call()
    if err != nil {
        return httpCtx.Response, err
    }
    return httpCtx.Response, err
}

// GetImageCollection takes context, id, embed, shareCode as parameters and
// returns an models.ApiResponse with models.Collection data and
// an error if there was an issue with the request or response.
// This endpoint gets more detailed information about a collection, including its cover image and timestamps for its creation and most recent update. To get the images in collections, use `GET /v2/images/collections/{id}/items`.
func (i *ImagesController) GetImageCollection(
    ctx context.Context,
    id string,
    embed []models.EmbedEnum,
    shareCode *string) (
    models.ApiResponse[models.Collection],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/collections/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    if embed != nil {
        req.QueryParam("embed", embed)
    }
    if shareCode != nil {
        req.QueryParam("share_code", *shareCode)
    }
    
    var result models.Collection
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.Collection](decoder)
    return models.NewApiResponse(result, resp), err
}

// RenameImageCollection takes context, id, body as parameters and
// returns an *Response and
// an error if there was an issue with the request or response.
// This endpoint sets a new name for an image collection.
func (i *ImagesController) RenameImageCollection(
    ctx context.Context,
    id string,
    body models.CollectionUpdateRequest) (
    *http.Response,
    error) {
    req := i.prepareRequest(ctx, "POST", "/v2/images/collections/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    
    httpCtx, err := req.Call()
    if err != nil {
        return httpCtx.Response, err
    }
    return httpCtx.Response, err
}

// DeleteImageCollectionItems takes context, id, itemId as parameters and
// returns an *Response and
// an error if there was an issue with the request or response.
// This endpoint removes one or more images from a collection.
func (i *ImagesController) DeleteImageCollectionItems(
    ctx context.Context,
    id string,
    itemId []string) (
    *http.Response,
    error) {
    req := i.prepareRequest(ctx, "DELETE", "/v2/images/collections/%v/items")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    if itemId != nil {
        req.QueryParam("item_id", itemId)
    }
    
    httpCtx, err := req.Call()
    if err != nil {
        return httpCtx.Response, err
    }
    return httpCtx.Response, err
}

// GetImageCollectionItems takes context, id, page, perPage, shareCode, sort as parameters and
// returns an models.ApiResponse with models.CollectionItemDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists the IDs of images in a collection and the date that each was added.
func (i *ImagesController) GetImageCollectionItems(
    ctx context.Context,
    id string,
    page *int,
    perPage *int,
    shareCode *string,
    sort *models.Sort1Enum) (
    models.ApiResponse[models.CollectionItemDataList],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/collections/%v/items")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if shareCode != nil {
        req.QueryParam("share_code", *shareCode)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    
    var result models.CollectionItemDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.CollectionItemDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// AddImageCollectionItems takes context, id, body as parameters and
// returns an *Response and
// an error if there was an issue with the request or response.
// This endpoint adds one or more images to a collection by image IDs.
func (i *ImagesController) AddImageCollectionItems(
    ctx context.Context,
    id string,
    body models.CollectionItemRequest) (
    *http.Response,
    error) {
    req := i.prepareRequest(ctx, "POST", "/v2/images/collections/%v/items")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
        "404": {Message: "Collection not found"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    
    httpCtx, err := req.Call()
    if err != nil {
        return httpCtx.Response, err
    }
    return httpCtx.Response, err
}

// GetImageLicenseList takes context, imageId, license, page, perPage, sort, username, startDate, endDate, downloadAvailability, teamHistory as parameters and
// returns an models.ApiResponse with models.DownloadHistoryDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists existing licenses.
func (i *ImagesController) GetImageLicenseList(
    ctx context.Context,
    imageId *string,
    license *string,
    page *int,
    perPage *int,
    sort *models.Sort1Enum,
    username *string,
    startDate *time.Time,
    endDate *time.Time,
    downloadAvailability *models.DownloadAvailabilityEnum,
    teamHistory *bool) (
    models.ApiResponse[models.DownloadHistoryDataList],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/licenses")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if imageId != nil {
        req.QueryParam("image_id", *imageId)
    }
    if license != nil {
        req.QueryParam("license", *license)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if username != nil {
        req.QueryParam("username", *username)
    }
    if startDate != nil {
        req.QueryParam("start_date", startDate.Format(time.RFC3339))
    }
    if endDate != nil {
        req.QueryParam("end_date", endDate.Format(time.RFC3339))
    }
    if downloadAvailability != nil {
        req.QueryParam("download_availability", *downloadAvailability)
    }
    if teamHistory != nil {
        req.QueryParam("team_history", *teamHistory)
    }
    var result models.DownloadHistoryDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.DownloadHistoryDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// LicenseImages takes context, body, subscriptionId, format, size, searchId as parameters and
// returns an models.ApiResponse with models.LicenseImageResultDataList data and
// an error if there was an issue with the request or response.
// This endpoint gets licenses for one or more images. You must specify the image IDs in the body parameter and other details like the format, size, and subscription ID either in the query parameter or with each image ID in the body parameter. Values in the body parameter override values in the query parameters. The download links in the response are valid for 8 hours.
func (i *ImagesController) LicenseImages(
    ctx context.Context,
    body models.LicenseImageRequest,
    subscriptionId *string,
    format *models.Format4Enum,
    size *models.Size8Enum,
    searchId *string) (
    models.ApiResponse[models.LicenseImageResultDataList],
    error) {
    req := i.prepareRequest(ctx, "POST", "/v2/images/licenses")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.Header("Content-Type", "application/json")
    if subscriptionId != nil {
        req.QueryParam("subscription_id", *subscriptionId)
    }
    if format != nil {
        req.QueryParam("format", *format)
    }
    if size != nil {
        req.QueryParam("size", *size)
    }
    if searchId != nil {
        req.QueryParam("search_id", *searchId)
    }
    req.Json(&body)
    var result models.LicenseImageResultDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.LicenseImageResultDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// DownloadImage takes context, id, body as parameters and
// returns an models.ApiResponse with models.Url data and
// an error if there was an issue with the request or response.
// This endpoint redownloads images that you have already received a license for. The download links in the response are valid for 8 hours.
func (i *ImagesController) DownloadImage(
    ctx context.Context,
    id string,
    body models.RedownloadImage) (
    models.ApiResponse[models.Url],
    error) {
    req := i.prepareRequest(ctx, "POST", "/v2/images/licenses/%v/downloads")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    
    var result models.Url
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.Url](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetImageRecommendations takes context, id, maxItems, safe as parameters and
// returns an models.ApiResponse with models.RecommendationDataList data and
// an error if there was an issue with the request or response.
// This endpoint returns images that customers put in the same collection as the specified image IDs.
func (i *ImagesController) GetImageRecommendations(
    ctx context.Context,
    id []string,
    maxItems *int,
    safe *bool) (
    models.ApiResponse[models.RecommendationDataList],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/recommendations")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.QueryParam("id", id)
    if maxItems != nil {
        req.QueryParam("max_items", *maxItems)
    }
    if safe != nil {
        req.QueryParam("safe", *safe)
    }
    var result models.RecommendationDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.RecommendationDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// SearchImages takes context, addedDate, addedDateStart, aspectRatioMin, aspectRatioMax, aspectRatio, aiSearch, aiLabelsLimit, aiIndustry, aiObjective, addedDateEnd, category, color, contributor, contributorCountry, fields, height, heightFrom, heightTo, imageType, keywordSafeSearch, language, license, model, orientation, page, perPage, peopleModelReleased, peopleAge, peopleEthnicity, peopleGender, peopleNumber, query, region, safe, sort, spellcheckQuery, view, width, widthFrom, widthTo as parameters and
// returns an models.ApiResponse with models.ImageSearchResults data and
// an error if there was an issue with the request or response.
// This endpoint searches for images. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter. You can also filter search terms out in the `query` parameter by prefixing the term with NOT. Free API accounts show results only from a limited library of media, not the full Shutterstock media library. Also, the number of search fields they can use in a request is limited.
func (i *ImagesController) SearchImages(
    ctx context.Context,
    addedDate *time.Time,
    addedDateStart *time.Time,
    aspectRatioMin *float64,
    aspectRatioMax *float64,
    aspectRatio *float64,
    aiSearch *bool,
    aiLabelsLimit *int,
    aiIndustry *models.AiIndustryEnum,
    aiObjective *models.AiObjectiveEnum,
    addedDateEnd *time.Time,
    category *string,
    color *string,
    contributor []string,
    contributorCountry *models.SearchImagesContributorCountry,
    fields *string,
    height *int,
    heightFrom *int,
    heightTo *int,
    imageType []models.ImageType1Enum,
    keywordSafeSearch *bool,
    language *models.LanguageEnum,
    license []models.LicenseEnum,
    model []string,
    orientation *models.Orientation1Enum,
    page *int,
    perPage *int,
    peopleModelReleased *bool,
    peopleAge *models.PeopleAge1Enum,
    peopleEthnicity []models.PeopleEthnicity1Enum,
    peopleGender *models.PeopleGender1Enum,
    peopleNumber *int,
    query *string,
    region *models.SearchImagesRegion,
    safe *bool,
    sort *models.Sort4Enum,
    spellcheckQuery *bool,
    view *models.View1Enum,
    width *int,
    widthFrom *int,
    widthTo *int) (
    models.ApiResponse[models.ImageSearchResults],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/search")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if addedDate != nil {
        req.QueryParam("added_date", addedDate.Format(models.DEFAULT_DATE))
    }
    if addedDateStart != nil {
        req.QueryParam("added_date_start", addedDateStart.Format(models.DEFAULT_DATE))
    }
    if aspectRatioMin != nil {
        req.QueryParam("aspect_ratio_min", *aspectRatioMin)
    }
    if aspectRatioMax != nil {
        req.QueryParam("aspect_ratio_max", *aspectRatioMax)
    }
    if aspectRatio != nil {
        req.QueryParam("aspect_ratio", *aspectRatio)
    }
    if aiSearch != nil {
        req.QueryParam("ai_search", *aiSearch)
    }
    if aiLabelsLimit != nil {
        req.QueryParam("ai_labels_limit", *aiLabelsLimit)
    }
    if aiIndustry != nil {
        req.QueryParam("ai_industry", *aiIndustry)
    }
    if aiObjective != nil {
        req.QueryParam("ai_objective", *aiObjective)
    }
    if addedDateEnd != nil {
        req.QueryParam("added_date_end", addedDateEnd.Format(models.DEFAULT_DATE))
    }
    if category != nil {
        req.QueryParam("category", *category)
    }
    if color != nil {
        req.QueryParam("color", *color)
    }
    if contributor != nil {
        req.QueryParam("contributor", contributor)
    }
    if contributorCountry != nil {
        req.QueryParam("contributor_country", *contributorCountry)
    }
    if fields != nil {
        req.QueryParam("fields", *fields)
    }
    if height != nil {
        req.QueryParam("height", *height)
    }
    if heightFrom != nil {
        req.QueryParam("height_from", *heightFrom)
    }
    if heightTo != nil {
        req.QueryParam("height_to", *heightTo)
    }
    if imageType != nil {
        req.QueryParam("image_type", imageType)
    }
    if keywordSafeSearch != nil {
        req.QueryParam("keyword_safe_search", *keywordSafeSearch)
    }
    if language != nil {
        req.QueryParam("language", *language)
    }
    if license != nil {
        req.QueryParam("license", license)
    }
    if model != nil {
        req.QueryParam("model", model)
    }
    if orientation != nil {
        req.QueryParam("orientation", *orientation)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if peopleModelReleased != nil {
        req.QueryParam("people_model_released", *peopleModelReleased)
    }
    if peopleAge != nil {
        req.QueryParam("people_age", *peopleAge)
    }
    if peopleEthnicity != nil {
        req.QueryParam("people_ethnicity", peopleEthnicity)
    }
    if peopleGender != nil {
        req.QueryParam("people_gender", *peopleGender)
    }
    if peopleNumber != nil {
        req.QueryParam("people_number", *peopleNumber)
    }
    if query != nil {
        req.QueryParam("query", *query)
    }
    if region != nil {
        req.QueryParam("region", *region)
    }
    if safe != nil {
        req.QueryParam("safe", *safe)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if spellcheckQuery != nil {
        req.QueryParam("spellcheck_query", *spellcheckQuery)
    }
    if view != nil {
        req.QueryParam("view", *view)
    }
    if width != nil {
        req.QueryParam("width", *width)
    }
    if widthFrom != nil {
        req.QueryParam("width_from", *widthFrom)
    }
    if widthTo != nil {
        req.QueryParam("width_to", *widthTo)
    }
    var result models.ImageSearchResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.ImageSearchResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetImageSuggestions takes context, query, limit as parameters and
// returns an models.ApiResponse with models.Suggestions data and
// an error if there was an issue with the request or response.
// This endpoint provides autocomplete suggestions for partial search terms.
func (i *ImagesController) GetImageSuggestions(
    ctx context.Context,
    query string,
    limit *int) (
    models.ApiResponse[models.Suggestions],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/search/suggestions")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.QueryParam("query", query)
    if limit != nil {
        req.QueryParam("limit", *limit)
    }
    var result models.Suggestions
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.Suggestions](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetImageKeywordSuggestions takes context, body as parameters and
// returns an models.ApiResponse with models.SearchEntitiesResponse data and
// an error if there was an issue with the request or response.
// This endpoint returns up to 10 important keywords from a block of plain text.
func (i *ImagesController) GetImageKeywordSuggestions(
    ctx context.Context,
    body models.SearchEntitiesRequest) (
    models.ApiResponse[models.SearchEntitiesResponse],
    error) {
    req := i.prepareRequest(ctx, "POST", "/v2/images/search/suggestions")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    var result models.SearchEntitiesResponse
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.SearchEntitiesResponse](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetUpdatedImages takes context, mType, startDate, endDate, interval, page, perPage, sort as parameters and
// returns an models.ApiResponse with models.UpdatedMediaDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists images that have been updated in the specified time period to update content management systems (CMS) or digital asset management (DAM) systems. In most cases, use the `interval` parameter to show images that were updated recently, but you can also use the `start_date` and `end_date` parameters to specify a range of no more than three days. Do not use the `interval` parameter with either `start_date` or `end_date`.
func (i *ImagesController) GetUpdatedImages(
    ctx context.Context,
    mType []models.Type5Enum,
    startDate *time.Time,
    endDate *time.Time,
    interval *string,
    page *int,
    perPage *int,
    sort *models.Sort1Enum) (
    models.ApiResponse[models.UpdatedMediaDataList],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/updated")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    if mType != nil {
        req.QueryParam("type", mType)
    }
    if startDate != nil {
        req.QueryParam("start_date", startDate.Format(models.DEFAULT_DATE))
    }
    if endDate != nil {
        req.QueryParam("end_date", endDate.Format(models.DEFAULT_DATE))
    }
    if interval != nil {
        req.QueryParam("interval", *interval)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    var result models.UpdatedMediaDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.UpdatedMediaDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetImage takes context, id, language, view, searchId as parameters and
// returns an models.ApiResponse with models.Image data and
// an error if there was an issue with the request or response.
// This endpoint shows information about an image, including a URL to a preview image and the sizes that it is available in.
func (i *ImagesController) GetImage(
    ctx context.Context,
    id string,
    language *models.LanguageEnum,
    view *models.View1Enum,
    searchId *string) (
    models.ApiResponse[models.Image],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if language != nil {
        req.QueryParam("language", *language)
    }
    if view != nil {
        req.QueryParam("view", *view)
    }
    if searchId != nil {
        req.QueryParam("search_id", *searchId)
    }
    
    var result models.Image
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.Image](decoder)
    return models.NewApiResponse(result, resp), err
}

// ListSimilarImages takes context, id, language, page, perPage, view as parameters and
// returns an models.ApiResponse with models.ImageSearchResults data and
// an error if there was an issue with the request or response.
// This endpoint returns images that are visually similar to an image that you specify.
func (i *ImagesController) ListSimilarImages(
    ctx context.Context,
    id string,
    language *models.LanguageEnum,
    page *int,
    perPage *int,
    view *models.View1Enum) (
    models.ApiResponse[models.ImageSearchResults],
    error) {
    req := i.prepareRequest(ctx, "GET", "/v2/images/%v/similar")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if language != nil {
        req.QueryParam("language", *language)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if view != nil {
        req.QueryParam("view", *view)
    }
    
    var result models.ImageSearchResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.ImageSearchResults](decoder)
    return models.NewApiResponse(result, resp), err
}
