// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "github.com/apimatic/go-core-runtime/https"
    "github.com/apimatic/go-core-runtime/utilities"
    "shutterstockapiexplorer/errors"
    "shutterstockapiexplorer/models"
)

// OAuthAuthorizationController represents a controller struct.
type OAuthAuthorizationController struct {
    baseController
}

// NewOAuthAuthorizationController creates a new instance of OAuthAuthorizationController.
// It takes a baseController as a parameter and returns a pointer to the OAuthAuthorizationController.
func NewOAuthAuthorizationController(baseController baseController) *OAuthAuthorizationController {
    oAuthAuthorizationController := OAuthAuthorizationController{baseController: baseController}
    return &oAuthAuthorizationController
}

// RequestTokenCustomerAccessCode takes context, authorization, code, redirectUri as parameters and
// returns an models.ApiResponse with models.OAuthToken data and
// an error if there was an issue with the request or response.
// Create a new OAuth 2 token.
func (o *OAuthAuthorizationController) RequestTokenCustomerAccessCode(
    ctx context.Context,
    authorization string,
    code string,
    redirectUri string,
    formParams map[string]any) (
    models.ApiResponse[models.OAuthToken],
    error) {
    req := o.prepareRequest(ctx, "POST", "/v2/oauth/access_token")
    
    req.BaseUrl("default")
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "OAuth 2 provider returned an error.", Unmarshaller: errors.NewOAuthProvider},
        "401": {Message: "OAuth 2 provider says client authentication failed.", Unmarshaller: errors.NewOAuthProvider},
    })
    req.Header("Authorization", authorization)
    req.FormParam("grant_type", "authorization_code")
    req.FormParam("code", code)
    req.FormParam("redirect_uri", redirectUri)
    req.FormParams(formParams)
    var result models.OAuthToken
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.OAuthToken](decoder)
    return models.NewApiResponse(result, resp), err
}

// RefreshTokenCustomerAccessCode takes context, authorization, refreshToken, scope as parameters and
// returns an models.ApiResponse with models.OAuthToken data and
// an error if there was an issue with the request or response.
// Obtain a new access token using a refresh token
func (o *OAuthAuthorizationController) RefreshTokenCustomerAccessCode(
    ctx context.Context,
    authorization string,
    refreshToken string,
    scope *string,
    formParams map[string]any) (
    models.ApiResponse[models.OAuthToken],
    error) {
    req := o.prepareRequest(ctx, "POST", "/v2/oauth/access_token")
    
    req.BaseUrl("default")
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "OAuth 2 provider returned an error.", Unmarshaller: errors.NewOAuthProvider},
        "401": {Message: "OAuth 2 provider says client authentication failed.", Unmarshaller: errors.NewOAuthProvider},
    })
    req.Header("Authorization", authorization)
    req.FormParam("grant_type", "refresh_token")
    req.FormParam("refresh_token", refreshToken)
    if scope != nil {
        req.FormParam("scope", *scope)
    }
    req.FormParams(formParams)
    var result models.OAuthToken
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.OAuthToken](decoder)
    return models.NewApiResponse(result, resp), err
}
