// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "github.com/apimatic/go-core-runtime/https"
    "github.com/apimatic/go-core-runtime/utilities"
    "shutterstockapiexplorer/models"
    "time"
)

// SoundEffectsController represents a controller struct.
type SoundEffectsController struct {
    baseController
}

// NewSoundEffectsController creates a new instance of SoundEffectsController.
// It takes a baseController as a parameter and returns a pointer to the SoundEffectsController.
func NewSoundEffectsController(baseController baseController) *SoundEffectsController {
    soundEffectsController := SoundEffectsController{baseController: baseController}
    return &soundEffectsController
}

// GetSfxListDetails takes context, id, view, language, library, searchId as parameters and
// returns an models.ApiResponse with models.SFXDataList data and
// an error if there was an issue with the request or response.
// This endpoint shows information about sound effects.
func (s *SoundEffectsController) GetSfxListDetails(
    ctx context.Context,
    id []string,
    view *models.View1Enum,
    language *models.LanguageEnum,
    library *models.Library1Enum,
    searchId *string) (
    models.ApiResponse[models.SFXDataList],
    error) {
    req := s.prepareRequest(ctx, "GET", "/v2/sfx")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.QueryParam("id", id)
    if view != nil {
        req.QueryParam("view", *view)
    }
    if language != nil {
        req.QueryParam("language", *language)
    }
    if library != nil {
        req.QueryParam("library", *library)
    }
    if searchId != nil {
        req.QueryParam("search_id", *searchId)
    }
    var result models.SFXDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.SFXDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetSfxLicenseList takes context, sfxId, license, page, perPage, sort, username, startDate, endDate, licenseId, downloadAvailability, teamHistory as parameters and
// returns an models.ApiResponse with models.DownloadHistoryDataList data and
// an error if there was an issue with the request or response.
// This endpoint lists existing licenses.
func (s *SoundEffectsController) GetSfxLicenseList(
    ctx context.Context,
    sfxId *string,
    license *string,
    page *int,
    perPage *int,
    sort *models.Sort1Enum,
    username *string,
    startDate *time.Time,
    endDate *time.Time,
    licenseId *string,
    downloadAvailability *models.DownloadAvailabilityEnum,
    teamHistory *bool) (
    models.ApiResponse[models.DownloadHistoryDataList],
    error) {
    req := s.prepareRequest(ctx, "GET", "/v2/sfx/licenses")
    
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if sfxId != nil {
        req.QueryParam("sfx_id", *sfxId)
    }
    if license != nil {
        req.QueryParam("license", *license)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if username != nil {
        req.QueryParam("username", *username)
    }
    if startDate != nil {
        req.QueryParam("start_date", startDate.Format(time.RFC3339))
    }
    if endDate != nil {
        req.QueryParam("end_date", endDate.Format(time.RFC3339))
    }
    if licenseId != nil {
        req.QueryParam("license_id", *licenseId)
    }
    if downloadAvailability != nil {
        req.QueryParam("download_availability", *downloadAvailability)
    }
    if teamHistory != nil {
        req.QueryParam("team_history", *teamHistory)
    }
    var result models.DownloadHistoryDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.DownloadHistoryDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// LicensesSFX takes context, body as parameters and
// returns an models.ApiResponse with models.LicenseSFXResultDataList data and
// an error if there was an issue with the request or response.
// This endpoint licenses sounds effect assets.
func (s *SoundEffectsController) LicensesSFX(
    ctx context.Context,
    body models.LicenseSFXRequest) (
    models.ApiResponse[models.LicenseSFXResultDataList],
    error) {
    req := s.prepareRequest(ctx, "POST", "/v2/sfx/licenses")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    req.Header("Content-Type", "application/json")
    req.Json(&body)
    var result models.LicenseSFXResultDataList
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.LicenseSFXResultDataList](decoder)
    return models.NewApiResponse(result, resp), err
}

// DownloadSfx takes context, id as parameters and
// returns an models.ApiResponse with models.SfxUrl data and
// an error if there was an issue with the request or response.
// This endpoint redownloads sound effects that you have already received a license for. The download links in the response are valid for 8 hours.
func (s *SoundEffectsController) DownloadSfx(
    ctx context.Context,
    id string) (
    models.ApiResponse[models.SfxUrl],
    error) {
    req := s.prepareRequest(ctx, "POST", "/v2/sfx/licenses/%v/downloads")
    req.AppendTemplateParams(id)
    req.Authenticate(NewAuth("customer_accessCode"))
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    
    var result models.SfxUrl
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.SfxUrl](decoder)
    return models.NewApiResponse(result, resp), err
}

// SearchSFX takes context, addedDate, addedDateStart, addedDateEnd, duration, durationFrom, durationTo, page, perPage, query, safe, sort, view, language as parameters and
// returns an models.ApiResponse with models.SFXSearchResults data and
// an error if there was an issue with the request or response.
// This endpoint searches for sound effects. If you specify more than one search parameter, the API uses an AND condition.
func (s *SoundEffectsController) SearchSFX(
    ctx context.Context,
    addedDate *time.Time,
    addedDateStart *time.Time,
    addedDateEnd *time.Time,
    duration *int,
    durationFrom *int,
    durationTo *int,
    page *int,
    perPage *int,
    query *string,
    safe *bool,
    sort *models.Sort21Enum,
    view *models.View1Enum,
    language *models.LanguageEnum) (
    models.ApiResponse[models.SFXSearchResults],
    error) {
    req := s.prepareRequest(ctx, "GET", "/v2/sfx/search")
    
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if addedDate != nil {
        req.QueryParam("added_date", addedDate.Format(models.DEFAULT_DATE))
    }
    if addedDateStart != nil {
        req.QueryParam("added_date_start", addedDateStart.Format(models.DEFAULT_DATE))
    }
    if addedDateEnd != nil {
        req.QueryParam("added_date_end", addedDateEnd.Format(models.DEFAULT_DATE))
    }
    if duration != nil {
        req.QueryParam("duration", *duration)
    }
    if durationFrom != nil {
        req.QueryParam("duration_from", *durationFrom)
    }
    if durationTo != nil {
        req.QueryParam("duration_to", *durationTo)
    }
    if page != nil {
        req.QueryParam("page", *page)
    }
    if perPage != nil {
        req.QueryParam("per_page", *perPage)
    }
    if query != nil {
        req.QueryParam("query", *query)
    }
    if safe != nil {
        req.QueryParam("safe", *safe)
    }
    if sort != nil {
        req.QueryParam("sort", *sort)
    }
    if view != nil {
        req.QueryParam("view", *view)
    }
    if language != nil {
        req.QueryParam("language", *language)
    }
    var result models.SFXSearchResults
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.SFXSearchResults](decoder)
    return models.NewApiResponse(result, resp), err
}

// GetSfxDetails takes context, id, language, view, library, searchId as parameters and
// returns an models.ApiResponse with models.SFX data and
// an error if there was an issue with the request or response.
// This endpoint shows information about a sound effect.
func (s *SoundEffectsController) GetSfxDetails(
    ctx context.Context,
    id int,
    language *models.LanguageEnum,
    view *models.View1Enum,
    library *models.Library1Enum,
    searchId *string) (
    models.ApiResponse[models.SFX],
    error) {
    req := s.prepareRequest(ctx, "GET", "/v2/sfx/%v")
    req.AppendTemplateParams(id)
    req.Authenticate(
        NewOrAuth(
            NewAuth("basic"),
            NewAuth("customer_accessCode"),
        ),
    )
    req.AppendErrors(map[string]https.ErrorBuilder[error]{
        "400": {Message: "Bad Request"},
        "401": {Message: "Unauthorized"},
        "403": {Message: "Forbidden"},
    })
    if language != nil {
        req.QueryParam("language", *language)
    }
    if view != nil {
        req.QueryParam("view", *view)
    }
    if library != nil {
        req.QueryParam("library", *library)
    }
    if searchId != nil {
        req.QueryParam("search_id", *searchId)
    }
    
    var result models.SFX
    decoder, resp, err := req.CallAsJson()
    if err != nil {
        return models.NewApiResponse(result, resp), err
    }
    
    result, err = utilities.DecodeResults[models.SFX](decoder)
    return models.NewApiResponse(result, resp), err
}
