// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package shutterstockapiexplorer

import (
    "context"
    "fmt"
)

var customMusicController CustomMusicController

var audioController AudioController

var imagesController ImagesController

var catalogController CatalogController

var contributorsController ContributorsController

var computerVisionController ComputerVisionController

var editorialImagesController EditorialImagesController

var editorialVideoController EditorialVideoController

var soundEffectsController SoundEffectsController

var testController TestController

var usersController UsersController

var videosController VideosController

// init is an initialization function that sets up the controllers.
// It creates a configuration from the environment with a specified HTTP configuration and initializes the client.
// Then, it assigns the different controllers from the client to the corresponding variables for further use.
func init() {
    
    config := CreateConfigurationFromEnvironment(
        WithHttpConfiguration(
            CreateHttpConfiguration(
                WithTimeout(30),
            ),
        ),
    )
    
    client := NewClient(config)
    
    ctx := context.Background()
    
    customerAccessCodeToken, err := client.CustomerAccessCodeManager().FetchToken(ctx, "authorizationCode")
    if err != nil {
        fmt.Println(err)
        return
    }
    
    client = client.CloneWithConfiguration(
        WithCustomerAccessCodeCredentials(
            config.CustomerAccessCodeCredentials().
                WithOAuthToken(customerAccessCodeToken),
        ),
    )
    customMusicController = *client.CustomMusicController()
    audioController = *client.AudioController()
    imagesController = *client.ImagesController()
    catalogController = *client.CatalogController()
    contributorsController = *client.ContributorsController()
    computerVisionController = *client.ComputerVisionController()
    editorialImagesController = *client.EditorialImagesController()
    editorialVideoController = *client.EditorialVideoController()
    soundEffectsController = *client.SoundEffectsController()
    testController = *client.TestController()
    usersController = *client.UsersController()
    videosController = *client.VideosController()
}
