// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// AccessTokenDetails represents a AccessTokenDetails struct.
// Access token details that are currently associated with this user
type AccessTokenDetails struct {
    // Client ID that is associated with the user
    ClientId             *string                `json:"client_id,omitempty"`
    // Contributor ID that is associated with the user
    ContributorId        *string                `json:"contributor_id,omitempty"`
    // Customer ID that is associated with the user
    CustomerId           *string                `json:"customer_id,omitempty"`
    // Number of seconds until the access token expires; no expiration if this value is null
    ExpiresIn            *int                   `json:"expires_in,omitempty"`
    // Organization ID that is associated with the user
    OrganizationId       *string                `json:"organization_id,omitempty"`
    // Type of access token
    Realm                *RealmEnum             `json:"realm,omitempty"`
    // Scopes that this access token provides when used as authentication
    Scopes               []string               `json:"scopes,omitempty"`
    // User ID that is associated with the user
    UserId               *string                `json:"user_id,omitempty"`
    // User name that is associated with the user
    Username             *string                `json:"username,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for AccessTokenDetails,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (a AccessTokenDetails) String() string {
    return fmt.Sprintf(
    	"AccessTokenDetails[ClientId=%v, ContributorId=%v, CustomerId=%v, ExpiresIn=%v, OrganizationId=%v, Realm=%v, Scopes=%v, UserId=%v, Username=%v, AdditionalProperties=%v]",
    	a.ClientId, a.ContributorId, a.CustomerId, a.ExpiresIn, a.OrganizationId, a.Realm, a.Scopes, a.UserId, a.Username, a.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for AccessTokenDetails.
// It customizes the JSON marshaling process for AccessTokenDetails objects.
func (a AccessTokenDetails) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(a.AdditionalProperties,
        "client_id", "contributor_id", "customer_id", "expires_in", "organization_id", "realm", "scopes", "user_id", "username"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(a.toMap())
}

// toMap converts the AccessTokenDetails object to a map representation for JSON marshaling.
func (a AccessTokenDetails) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, a.AdditionalProperties)
    if a.ClientId != nil {
        structMap["client_id"] = a.ClientId
    }
    if a.ContributorId != nil {
        structMap["contributor_id"] = a.ContributorId
    }
    if a.CustomerId != nil {
        structMap["customer_id"] = a.CustomerId
    }
    if a.ExpiresIn != nil {
        structMap["expires_in"] = a.ExpiresIn
    }
    if a.OrganizationId != nil {
        structMap["organization_id"] = a.OrganizationId
    }
    if a.Realm != nil {
        structMap["realm"] = a.Realm
    }
    if a.Scopes != nil {
        structMap["scopes"] = a.Scopes
    }
    if a.UserId != nil {
        structMap["user_id"] = a.UserId
    }
    if a.Username != nil {
        structMap["username"] = a.Username
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for AccessTokenDetails.
// It customizes the JSON unmarshaling process for AccessTokenDetails objects.
func (a *AccessTokenDetails) UnmarshalJSON(input []byte) error {
    var temp tempAccessTokenDetails
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "client_id", "contributor_id", "customer_id", "expires_in", "organization_id", "realm", "scopes", "user_id", "username")
    if err != nil {
    	return err
    }
    a.AdditionalProperties = additionalProperties
    
    a.ClientId = temp.ClientId
    a.ContributorId = temp.ContributorId
    a.CustomerId = temp.CustomerId
    a.ExpiresIn = temp.ExpiresIn
    a.OrganizationId = temp.OrganizationId
    a.Realm = temp.Realm
    a.Scopes = temp.Scopes
    a.UserId = temp.UserId
    a.Username = temp.Username
    return nil
}

// tempAccessTokenDetails is a temporary struct used for validating the fields of AccessTokenDetails.
type tempAccessTokenDetails  struct {
    ClientId       *string    `json:"client_id,omitempty"`
    ContributorId  *string    `json:"contributor_id,omitempty"`
    CustomerId     *string    `json:"customer_id,omitempty"`
    ExpiresIn      *int       `json:"expires_in,omitempty"`
    OrganizationId *string    `json:"organization_id,omitempty"`
    Realm          *RealmEnum `json:"realm,omitempty"`
    Scopes         []string   `json:"scopes,omitempty"`
    UserId         *string    `json:"user_id,omitempty"`
    Username       *string    `json:"username,omitempty"`
}
