// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// Album represents a Album struct.
// Album metadata
type Album struct {
    // The album ID
    Id    string `json:"id"`
    // The album title
    Title string `json:"title"`
}

// String implements the fmt.Stringer interface for Album,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (a Album) String() string {
    return fmt.Sprintf(
    	"Album[Id=%v, Title=%v]",
    	a.Id, a.Title)
}

// MarshalJSON implements the json.Marshaler interface for Album.
// It customizes the JSON marshaling process for Album objects.
func (a Album) MarshalJSON() (
    []byte,
    error) {
    return json.Marshal(a.toMap())
}

// toMap converts the Album object to a map representation for JSON marshaling.
func (a Album) toMap() map[string]any {
    structMap := make(map[string]any)
    structMap["id"] = a.Id
    structMap["title"] = a.Title
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Album.
// It customizes the JSON unmarshaling process for Album objects.
func (a *Album) UnmarshalJSON(input []byte) error {
    var temp tempAlbum
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    
    a.Id = *temp.Id
    a.Title = *temp.Title
    return nil
}

// tempAlbum is a temporary struct used for validating the fields of Album.
type tempAlbum  struct {
    Id    *string `json:"id"`
    Title *string `json:"title"`
}

func (a *tempAlbum) validate() error {
    var errs []string
    if a.Id == nil {
        errs = append(errs, "required field `id` is missing for type `Album`")
    }
    if a.Title == nil {
        errs = append(errs, "required field `title` is missing for type `Album`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
