// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// AudioRenderTimelineSpanInstrumentGroup represents a AudioRenderTimelineSpanInstrumentGroup struct.
// An instrument and the status objects that specify when that instrument plays
type AudioRenderTimelineSpanInstrumentGroup struct {
    // The instrument ID
    InstrumentGroup      string                                         `json:"instrument_group"`
    // An array of status objects
    Statuses             []AudioRenderTimelineSpanInstrumentGroupStatus `json:"statuses,omitempty"`
    AdditionalProperties map[string]interface{}                         `json:"_"`
}

// String implements the fmt.Stringer interface for AudioRenderTimelineSpanInstrumentGroup,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (a AudioRenderTimelineSpanInstrumentGroup) String() string {
    return fmt.Sprintf(
    	"AudioRenderTimelineSpanInstrumentGroup[InstrumentGroup=%v, Statuses=%v, AdditionalProperties=%v]",
    	a.InstrumentGroup, a.Statuses, a.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for AudioRenderTimelineSpanInstrumentGroup.
// It customizes the JSON marshaling process for AudioRenderTimelineSpanInstrumentGroup objects.
func (a AudioRenderTimelineSpanInstrumentGroup) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(a.AdditionalProperties,
        "instrument_group", "statuses"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(a.toMap())
}

// toMap converts the AudioRenderTimelineSpanInstrumentGroup object to a map representation for JSON marshaling.
func (a AudioRenderTimelineSpanInstrumentGroup) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, a.AdditionalProperties)
    structMap["instrument_group"] = a.InstrumentGroup
    if a.Statuses != nil {
        structMap["statuses"] = a.Statuses
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for AudioRenderTimelineSpanInstrumentGroup.
// It customizes the JSON unmarshaling process for AudioRenderTimelineSpanInstrumentGroup objects.
func (a *AudioRenderTimelineSpanInstrumentGroup) UnmarshalJSON(input []byte) error {
    var temp tempAudioRenderTimelineSpanInstrumentGroup
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "instrument_group", "statuses")
    if err != nil {
    	return err
    }
    a.AdditionalProperties = additionalProperties
    
    a.InstrumentGroup = *temp.InstrumentGroup
    a.Statuses = temp.Statuses
    return nil
}

// tempAudioRenderTimelineSpanInstrumentGroup is a temporary struct used for validating the fields of AudioRenderTimelineSpanInstrumentGroup.
type tempAudioRenderTimelineSpanInstrumentGroup  struct {
    InstrumentGroup *string                                        `json:"instrument_group"`
    Statuses        []AudioRenderTimelineSpanInstrumentGroupStatus `json:"statuses,omitempty"`
}

func (a *tempAudioRenderTimelineSpanInstrumentGroup) validate() error {
    var errs []string
    if a.InstrumentGroup == nil {
        errs = append(errs, "required field `instrument_group` is missing for type `AudioRenderTimelineSpanInstrumentGroup`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
