// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// AudioDataList represents a AudioDataList struct.
// List of tracks
type AudioDataList struct {
    // Tracks
    Data                 []Audio                `json:"data,omitempty"`
    // Error list; appears only if there was an error
    Errors               []Error                `json:"errors,omitempty"`
    // Server-generated message, if any
    Message              *string                `json:"message,omitempty"`
    // Current page that is returned
    Page                 *int                   `json:"page,omitempty"`
    // Number of results per page
    PerPage              *int                   `json:"per_page,omitempty"`
    // Total count of all results across all pages
    TotalCount           *int                   `json:"total_count,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for AudioDataList,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (a AudioDataList) String() string {
    return fmt.Sprintf(
    	"AudioDataList[Data=%v, Errors=%v, Message=%v, Page=%v, PerPage=%v, TotalCount=%v, AdditionalProperties=%v]",
    	a.Data, a.Errors, a.Message, a.Page, a.PerPage, a.TotalCount, a.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for AudioDataList.
// It customizes the JSON marshaling process for AudioDataList objects.
func (a AudioDataList) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(a.AdditionalProperties,
        "data", "errors", "message", "page", "per_page", "total_count"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(a.toMap())
}

// toMap converts the AudioDataList object to a map representation for JSON marshaling.
func (a AudioDataList) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, a.AdditionalProperties)
    if a.Data != nil {
        structMap["data"] = a.Data
    }
    if a.Errors != nil {
        structMap["errors"] = a.Errors
    }
    if a.Message != nil {
        structMap["message"] = a.Message
    }
    if a.Page != nil {
        structMap["page"] = a.Page
    }
    if a.PerPage != nil {
        structMap["per_page"] = a.PerPage
    }
    if a.TotalCount != nil {
        structMap["total_count"] = a.TotalCount
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for AudioDataList.
// It customizes the JSON unmarshaling process for AudioDataList objects.
func (a *AudioDataList) UnmarshalJSON(input []byte) error {
    var temp tempAudioDataList
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "data", "errors", "message", "page", "per_page", "total_count")
    if err != nil {
    	return err
    }
    a.AdditionalProperties = additionalProperties
    
    a.Data = temp.Data
    a.Errors = temp.Errors
    a.Message = temp.Message
    a.Page = temp.Page
    a.PerPage = temp.PerPage
    a.TotalCount = temp.TotalCount
    return nil
}

// tempAudioDataList is a temporary struct used for validating the fields of AudioDataList.
type tempAudioDataList  struct {
    Data       []Audio `json:"data,omitempty"`
    Errors     []Error `json:"errors,omitempty"`
    Message    *string `json:"message,omitempty"`
    Page       *int    `json:"page,omitempty"`
    PerPage    *int    `json:"per_page,omitempty"`
    TotalCount *int    `json:"total_count,omitempty"`
}
