// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// AudioUrl represents a AudioUrl struct.
// Audio License URL object
type AudioUrl struct {
    // URL that can be used to download the .zip file containing shorts, loops, and stems
    ShortsLoopsStems     *string                `json:"shorts_loops_stems,omitempty"`
    // URL that can be used to download the unwatermarked, licensed asset
    Url                  string                 `json:"url"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for AudioUrl,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (a AudioUrl) String() string {
    return fmt.Sprintf(
    	"AudioUrl[ShortsLoopsStems=%v, Url=%v, AdditionalProperties=%v]",
    	a.ShortsLoopsStems, a.Url, a.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for AudioUrl.
// It customizes the JSON marshaling process for AudioUrl objects.
func (a AudioUrl) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(a.AdditionalProperties,
        "shorts_loops_stems", "url"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(a.toMap())
}

// toMap converts the AudioUrl object to a map representation for JSON marshaling.
func (a AudioUrl) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, a.AdditionalProperties)
    if a.ShortsLoopsStems != nil {
        structMap["shorts_loops_stems"] = a.ShortsLoopsStems
    }
    structMap["url"] = a.Url
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for AudioUrl.
// It customizes the JSON unmarshaling process for AudioUrl objects.
func (a *AudioUrl) UnmarshalJSON(input []byte) error {
    var temp tempAudioUrl
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "shorts_loops_stems", "url")
    if err != nil {
    	return err
    }
    a.AdditionalProperties = additionalProperties
    
    a.ShortsLoopsStems = temp.ShortsLoopsStems
    a.Url = *temp.Url
    return nil
}

// tempAudioUrl is a temporary struct used for validating the fields of AudioUrl.
type tempAudioUrl  struct {
    ShortsLoopsStems *string `json:"shorts_loops_stems,omitempty"`
    Url              *string `json:"url"`
}

func (a *tempAudioUrl) validate() error {
    var errs []string
    if a.Url == nil {
        errs = append(errs, "required field `url` is missing for type `AudioUrl`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
