// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// AudioRenderTimelineSpanRegion represents a AudioRenderTimelineSpanRegion struct.
// A period of music or silence, measured in beats
type AudioRenderTimelineSpanRegion struct {
    // The beat, relative to the span, at which the region object's music begins
    Beat                 int                    `json:"beat"`
    // The descriptor ID needed to compose the music
    Descriptor           string                 `json:"descriptor"`
    // A high-level description of how a region ends
    EndType              *EndType               `json:"end_type,omitempty"`
    // An identifier which must be unique within the parent span
    Id                   float64                `json:"id"`
    // The key signature active at the beginning of the region
    Key                  *Key                   `json:"key,omitempty"`
    // The type of region
    Region               RegionEnum             `json:"region"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for AudioRenderTimelineSpanRegion,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (a AudioRenderTimelineSpanRegion) String() string {
    return fmt.Sprintf(
    	"AudioRenderTimelineSpanRegion[Beat=%v, Descriptor=%v, EndType=%v, Id=%v, Key=%v, Region=%v, AdditionalProperties=%v]",
    	a.Beat, a.Descriptor, a.EndType, a.Id, a.Key, a.Region, a.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for AudioRenderTimelineSpanRegion.
// It customizes the JSON marshaling process for AudioRenderTimelineSpanRegion objects.
func (a AudioRenderTimelineSpanRegion) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(a.AdditionalProperties,
        "beat", "descriptor", "end_type", "id", "key", "region"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(a.toMap())
}

// toMap converts the AudioRenderTimelineSpanRegion object to a map representation for JSON marshaling.
func (a AudioRenderTimelineSpanRegion) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, a.AdditionalProperties)
    structMap["beat"] = a.Beat
    structMap["descriptor"] = a.Descriptor
    if a.EndType != nil {
        structMap["end_type"] = a.EndType.toMap()
    }
    structMap["id"] = a.Id
    if a.Key != nil {
        structMap["key"] = a.Key.toMap()
    }
    structMap["region"] = a.Region
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for AudioRenderTimelineSpanRegion.
// It customizes the JSON unmarshaling process for AudioRenderTimelineSpanRegion objects.
func (a *AudioRenderTimelineSpanRegion) UnmarshalJSON(input []byte) error {
    var temp tempAudioRenderTimelineSpanRegion
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "beat", "descriptor", "end_type", "id", "key", "region")
    if err != nil {
    	return err
    }
    a.AdditionalProperties = additionalProperties
    
    a.Beat = *temp.Beat
    a.Descriptor = *temp.Descriptor
    a.EndType = temp.EndType
    a.Id = *temp.Id
    a.Key = temp.Key
    a.Region = *temp.Region
    return nil
}

// tempAudioRenderTimelineSpanRegion is a temporary struct used for validating the fields of AudioRenderTimelineSpanRegion.
type tempAudioRenderTimelineSpanRegion  struct {
    Beat       *int        `json:"beat"`
    Descriptor *string     `json:"descriptor"`
    EndType    *EndType    `json:"end_type,omitempty"`
    Id         *float64    `json:"id"`
    Key        *Key        `json:"key,omitempty"`
    Region     *RegionEnum `json:"region"`
}

func (a *tempAudioRenderTimelineSpanRegion) validate() error {
    var errs []string
    if a.Beat == nil {
        errs = append(errs, "required field `beat` is missing for type `AudioRenderTimelineSpanRegion`")
    }
    if a.Descriptor == nil {
        errs = append(errs, "required field `descriptor` is missing for type `AudioRenderTimelineSpanRegion`")
    }
    if a.Id == nil {
        errs = append(errs, "required field `id` is missing for type `AudioRenderTimelineSpanRegion`")
    }
    if a.Region == nil {
        errs = append(errs, "required field `region` is missing for type `AudioRenderTimelineSpanRegion`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
