// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// AudioRenderTimelineSpan represents a AudioRenderTimelineSpan struct.
// The beginning of a non-overlapping period of absolute time
type AudioRenderTimelineSpan struct {
    // An identifier which must be unique within the parent span
    Id                   *float64                                 `json:"id,omitempty"`
    // An array of instrument_group objects that are used in this span
    InstrumentGroups     []AudioRenderTimelineSpanInstrumentGroup `json:"instrument_groups,omitempty"`
    // An array of region objects within the span
    Regions              []AudioRenderTimelineSpanRegion          `json:"regions,omitempty"`
    // Type of span; metered spans represent a pariod of time with music, and unmetered spans denote the end of the prior metered span
    SpanType             SpanTypeEnum                             `json:"span_type"`
    // The tempo, in beats per minute, at the start of the span; if not provided, the API selects a random tempo
    Tempo                *int                                     `json:"tempo,omitempty"`
    // Two or more inflection points in a tempo curve; the API creates a smoothly changing tempo by using a linear interpolation of the time between each tempo change
    TempoChanges         []AudioRenderTimelineSpanTempoChanges    `json:"tempo_changes,omitempty"`
    // The absolute time, in seconds, at which the span starts
    Time                 int                                      `json:"time"`
    AdditionalProperties map[string]interface{}                   `json:"_"`
}

// String implements the fmt.Stringer interface for AudioRenderTimelineSpan,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (a AudioRenderTimelineSpan) String() string {
    return fmt.Sprintf(
    	"AudioRenderTimelineSpan[Id=%v, InstrumentGroups=%v, Regions=%v, SpanType=%v, Tempo=%v, TempoChanges=%v, Time=%v, AdditionalProperties=%v]",
    	a.Id, a.InstrumentGroups, a.Regions, a.SpanType, a.Tempo, a.TempoChanges, a.Time, a.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for AudioRenderTimelineSpan.
// It customizes the JSON marshaling process for AudioRenderTimelineSpan objects.
func (a AudioRenderTimelineSpan) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(a.AdditionalProperties,
        "id", "instrument_groups", "regions", "span_type", "tempo", "tempo_changes", "time"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(a.toMap())
}

// toMap converts the AudioRenderTimelineSpan object to a map representation for JSON marshaling.
func (a AudioRenderTimelineSpan) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, a.AdditionalProperties)
    if a.Id != nil {
        structMap["id"] = a.Id
    }
    if a.InstrumentGroups != nil {
        structMap["instrument_groups"] = a.InstrumentGroups
    }
    if a.Regions != nil {
        structMap["regions"] = a.Regions
    }
    structMap["span_type"] = a.SpanType
    if a.Tempo != nil {
        structMap["tempo"] = a.Tempo
    }
    if a.TempoChanges != nil {
        structMap["tempo_changes"] = a.TempoChanges
    }
    structMap["time"] = a.Time
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for AudioRenderTimelineSpan.
// It customizes the JSON unmarshaling process for AudioRenderTimelineSpan objects.
func (a *AudioRenderTimelineSpan) UnmarshalJSON(input []byte) error {
    var temp tempAudioRenderTimelineSpan
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "id", "instrument_groups", "regions", "span_type", "tempo", "tempo_changes", "time")
    if err != nil {
    	return err
    }
    a.AdditionalProperties = additionalProperties
    
    a.Id = temp.Id
    a.InstrumentGroups = temp.InstrumentGroups
    a.Regions = temp.Regions
    a.SpanType = *temp.SpanType
    a.Tempo = temp.Tempo
    a.TempoChanges = temp.TempoChanges
    a.Time = *temp.Time
    return nil
}

// tempAudioRenderTimelineSpan is a temporary struct used for validating the fields of AudioRenderTimelineSpan.
type tempAudioRenderTimelineSpan  struct {
    Id               *float64                                 `json:"id,omitempty"`
    InstrumentGroups []AudioRenderTimelineSpanInstrumentGroup `json:"instrument_groups,omitempty"`
    Regions          []AudioRenderTimelineSpanRegion          `json:"regions,omitempty"`
    SpanType         *SpanTypeEnum                            `json:"span_type"`
    Tempo            *int                                     `json:"tempo,omitempty"`
    TempoChanges     []AudioRenderTimelineSpanTempoChanges    `json:"tempo_changes,omitempty"`
    Time             *int                                     `json:"time"`
}

func (a *tempAudioRenderTimelineSpan) validate() error {
    var errs []string
    if a.SpanType == nil {
        errs = append(errs, "required field `span_type` is missing for type `AudioRenderTimelineSpan`")
    }
    if a.Time == nil {
        errs = append(errs, "required field `time` is missing for type `AudioRenderTimelineSpan`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
