// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
)

// BulkSearchImagesRegion represents a BulkSearchImagesRegion struct.
// This is a container for any-of cases.
type BulkSearchImagesRegion struct {
    value    any
    isString bool
}

// String implements the fmt.Stringer interface for BulkSearchImagesRegion,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (b BulkSearchImagesRegion) String() string {
    return fmt.Sprintf("%v", b.value)
}

// MarshalJSON implements the json.Marshaler interface for BulkSearchImagesRegion.
// It customizes the JSON marshaling process for BulkSearchImagesRegion objects.
func (b BulkSearchImagesRegion) MarshalJSON() (
    []byte,
    error) {
    if b.value == nil {
        return nil, errors.New("No underlying type is set. Please use any of the `models.BulkSearchImagesRegionContainer.From*` functions to initialize the BulkSearchImagesRegion object.")
    }
    return json.Marshal(b.toMap())
}

// toMap converts the BulkSearchImagesRegion object to a map representation for JSON marshaling.
func (b *BulkSearchImagesRegion) toMap() any {
    switch obj := b.value.(type) {
    case *string:
        return *obj
    }
    return nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for BulkSearchImagesRegion.
// It customizes the JSON unmarshaling process for BulkSearchImagesRegion objects.
func (b *BulkSearchImagesRegion) UnmarshalJSON(input []byte) error {
    result, err := UnmarshallAnyOf(input,
        NewTypeHolder(new(string), false, &b.isString),
    )
    
    b.value = result
    return err
}

func (b *BulkSearchImagesRegion) AsString() (
    *string,
    bool) {
    if !b.isString {
        return nil, false
    }
    return b.value.(*string), true
}

// internalBulkSearchImagesRegion represents a bulkSearchImagesRegion struct.
// This is a container for any-of cases.
type internalBulkSearchImagesRegion struct {}

var BulkSearchImagesRegionContainer internalBulkSearchImagesRegion

// The internalBulkSearchImagesRegion instance, wrapping the provided string value.
func (b *internalBulkSearchImagesRegion) FromString(val string) BulkSearchImagesRegion {
    return BulkSearchImagesRegion{value: &val}
}
