// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// CatalogCollection represents a CatalogCollection struct.
// Catalog collection
type CatalogCollection struct {
    // Metadata about an item that is part of a collection
    CoverAsset           *CatalogCollectionItem           `json:"cover_asset,omitempty"`
    CreatedTime          time.Time                        `json:"created_time"`
    Id                   string                           `json:"id"`
    Name                 string                           `json:"name"`
    // List of role assignments for a catalog collection
    RoleAssignments      CatalogCollectionRoleAssignments `json:"role_assignments"`
    TotalItemCount       float64                          `json:"total_item_count"`
    UpdatedTime          time.Time                        `json:"updated_time"`
    Visibility           VisibilityEnum                   `json:"visibility"`
    AdditionalProperties map[string]interface{}           `json:"_"`
}

// String implements the fmt.Stringer interface for CatalogCollection,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c CatalogCollection) String() string {
    return fmt.Sprintf(
    	"CatalogCollection[CoverAsset=%v, CreatedTime=%v, Id=%v, Name=%v, RoleAssignments=%v, TotalItemCount=%v, UpdatedTime=%v, Visibility=%v, AdditionalProperties=%v]",
    	c.CoverAsset, c.CreatedTime, c.Id, c.Name, c.RoleAssignments, c.TotalItemCount, c.UpdatedTime, c.Visibility, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for CatalogCollection.
// It customizes the JSON marshaling process for CatalogCollection objects.
func (c CatalogCollection) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "cover_asset", "created_time", "id", "name", "role_assignments", "total_item_count", "updated_time", "visibility"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the CatalogCollection object to a map representation for JSON marshaling.
func (c CatalogCollection) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    if c.CoverAsset != nil {
        structMap["cover_asset"] = c.CoverAsset.toMap()
    }
    structMap["created_time"] = c.CreatedTime.Format(time.RFC3339)
    structMap["id"] = c.Id
    structMap["name"] = c.Name
    structMap["role_assignments"] = c.RoleAssignments.toMap()
    structMap["total_item_count"] = c.TotalItemCount
    structMap["updated_time"] = c.UpdatedTime.Format(time.RFC3339)
    structMap["visibility"] = c.Visibility
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for CatalogCollection.
// It customizes the JSON unmarshaling process for CatalogCollection objects.
func (c *CatalogCollection) UnmarshalJSON(input []byte) error {
    var temp tempCatalogCollection
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "cover_asset", "created_time", "id", "name", "role_assignments", "total_item_count", "updated_time", "visibility")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.CoverAsset = temp.CoverAsset
    CreatedTimeVal, err := time.Parse(time.RFC3339, *temp.CreatedTime)
    if err != nil {
        log.Fatalf("Cannot Parse created_time as % s format.", time.RFC3339)
    }
    c.CreatedTime = CreatedTimeVal
    c.Id = *temp.Id
    c.Name = *temp.Name
    c.RoleAssignments = *temp.RoleAssignments
    c.TotalItemCount = *temp.TotalItemCount
    UpdatedTimeVal, err := time.Parse(time.RFC3339, *temp.UpdatedTime)
    if err != nil {
        log.Fatalf("Cannot Parse updated_time as % s format.", time.RFC3339)
    }
    c.UpdatedTime = UpdatedTimeVal
    c.Visibility = *temp.Visibility
    return nil
}

// tempCatalogCollection is a temporary struct used for validating the fields of CatalogCollection.
type tempCatalogCollection  struct {
    CoverAsset      *CatalogCollectionItem            `json:"cover_asset,omitempty"`
    CreatedTime     *string                           `json:"created_time"`
    Id              *string                           `json:"id"`
    Name            *string                           `json:"name"`
    RoleAssignments *CatalogCollectionRoleAssignments `json:"role_assignments"`
    TotalItemCount  *float64                          `json:"total_item_count"`
    UpdatedTime     *string                           `json:"updated_time"`
    Visibility      *VisibilityEnum                   `json:"visibility"`
}

func (c *tempCatalogCollection) validate() error {
    var errs []string
    if c.CreatedTime == nil {
        errs = append(errs, "required field `created_time` is missing for type `CatalogCollection`")
    }
    if c.Id == nil {
        errs = append(errs, "required field `id` is missing for type `CatalogCollection`")
    }
    if c.Name == nil {
        errs = append(errs, "required field `name` is missing for type `CatalogCollection`")
    }
    if c.RoleAssignments == nil {
        errs = append(errs, "required field `role_assignments` is missing for type `CatalogCollection`")
    }
    if c.TotalItemCount == nil {
        errs = append(errs, "required field `total_item_count` is missing for type `CatalogCollection`")
    }
    if c.UpdatedTime == nil {
        errs = append(errs, "required field `updated_time` is missing for type `CatalogCollection`")
    }
    if c.Visibility == nil {
        errs = append(errs, "required field `visibility` is missing for type `CatalogCollection`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
