// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// CatalogCollectionItem represents a CatalogCollectionItem struct.
// Metadata about an item that is part of a collection
type CatalogCollectionItem struct {
    Asset                Asset                  `json:"asset"`
    // The collection IDs that this asset belongs to
    CollectionIds        []string               `json:"collection_ids,omitempty"`
    CreatedTime          time.Time              `json:"created_time"`
    Id                   string                 `json:"id"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for CatalogCollectionItem,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c CatalogCollectionItem) String() string {
    return fmt.Sprintf(
    	"CatalogCollectionItem[Asset=%v, CollectionIds=%v, CreatedTime=%v, Id=%v, AdditionalProperties=%v]",
    	c.Asset, c.CollectionIds, c.CreatedTime, c.Id, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for CatalogCollectionItem.
// It customizes the JSON marshaling process for CatalogCollectionItem objects.
func (c CatalogCollectionItem) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "asset", "collection_ids", "created_time", "id"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the CatalogCollectionItem object to a map representation for JSON marshaling.
func (c CatalogCollectionItem) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    structMap["asset"] = c.Asset.toMap()
    if c.CollectionIds != nil {
        structMap["collection_ids"] = c.CollectionIds
    }
    structMap["created_time"] = c.CreatedTime.Format(time.RFC3339)
    structMap["id"] = c.Id
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for CatalogCollectionItem.
// It customizes the JSON unmarshaling process for CatalogCollectionItem objects.
func (c *CatalogCollectionItem) UnmarshalJSON(input []byte) error {
    var temp tempCatalogCollectionItem
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "asset", "collection_ids", "created_time", "id")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.Asset = *temp.Asset
    c.CollectionIds = temp.CollectionIds
    CreatedTimeVal, err := time.Parse(time.RFC3339, *temp.CreatedTime)
    if err != nil {
        log.Fatalf("Cannot Parse created_time as % s format.", time.RFC3339)
    }
    c.CreatedTime = CreatedTimeVal
    c.Id = *temp.Id
    return nil
}

// tempCatalogCollectionItem is a temporary struct used for validating the fields of CatalogCollectionItem.
type tempCatalogCollectionItem  struct {
    Asset         *Asset   `json:"asset"`
    CollectionIds []string `json:"collection_ids,omitempty"`
    CreatedTime   *string  `json:"created_time"`
    Id            *string  `json:"id"`
}

func (c *tempCatalogCollectionItem) validate() error {
    var errs []string
    if c.Asset == nil {
        errs = append(errs, "required field `asset` is missing for type `CatalogCollectionItem`")
    }
    if c.CreatedTime == nil {
        errs = append(errs, "required field `created_time` is missing for type `CatalogCollectionItem`")
    }
    if c.Id == nil {
        errs = append(errs, "required field `id` is missing for type `CatalogCollectionItem`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
