// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// CatalogCollectionRole represents a CatalogCollectionRole struct.
// A user that has access to a catalog collection
type CatalogCollectionRole struct {
    Email                string                 `json:"email"`
    Id                   string                 `json:"id"`
    Type                 string                 `json:"type"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for CatalogCollectionRole,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c CatalogCollectionRole) String() string {
    return fmt.Sprintf(
    	"CatalogCollectionRole[Email=%v, Id=%v, Type=%v, AdditionalProperties=%v]",
    	c.Email, c.Id, c.Type, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for CatalogCollectionRole.
// It customizes the JSON marshaling process for CatalogCollectionRole objects.
func (c CatalogCollectionRole) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "email", "id", "type"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the CatalogCollectionRole object to a map representation for JSON marshaling.
func (c CatalogCollectionRole) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    structMap["email"] = c.Email
    structMap["id"] = c.Id
    structMap["type"] = c.Type
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for CatalogCollectionRole.
// It customizes the JSON unmarshaling process for CatalogCollectionRole objects.
func (c *CatalogCollectionRole) UnmarshalJSON(input []byte) error {
    var temp tempCatalogCollectionRole
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "email", "id", "type")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.Email = *temp.Email
    c.Id = *temp.Id
    c.Type = *temp.Type
    return nil
}

// tempCatalogCollectionRole is a temporary struct used for validating the fields of CatalogCollectionRole.
type tempCatalogCollectionRole  struct {
    Email *string `json:"email"`
    Id    *string `json:"id"`
    Type  *string `json:"type"`
}

func (c *tempCatalogCollectionRole) validate() error {
    var errs []string
    if c.Email == nil {
        errs = append(errs, "required field `email` is missing for type `CatalogCollectionRole`")
    }
    if c.Id == nil {
        errs = append(errs, "required field `id` is missing for type `CatalogCollectionRole`")
    }
    if c.Type == nil {
        errs = append(errs, "required field `type` is missing for type `CatalogCollectionRole`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
