// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// CollectionCreateResponse represents a CollectionCreateResponse struct.
// Collection creation response
type CollectionCreateResponse struct {
    // ID of the new collection
    Id                   string                 `json:"id"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for CollectionCreateResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c CollectionCreateResponse) String() string {
    return fmt.Sprintf(
    	"CollectionCreateResponse[Id=%v, AdditionalProperties=%v]",
    	c.Id, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for CollectionCreateResponse.
// It customizes the JSON marshaling process for CollectionCreateResponse objects.
func (c CollectionCreateResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "id"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the CollectionCreateResponse object to a map representation for JSON marshaling.
func (c CollectionCreateResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    structMap["id"] = c.Id
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for CollectionCreateResponse.
// It customizes the JSON unmarshaling process for CollectionCreateResponse objects.
func (c *CollectionCreateResponse) UnmarshalJSON(input []byte) error {
    var temp tempCollectionCreateResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "id")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.Id = *temp.Id
    return nil
}

// tempCollectionCreateResponse is a temporary struct used for validating the fields of CollectionCreateResponse.
type tempCollectionCreateResponse  struct {
    Id *string `json:"id"`
}

func (c *tempCollectionCreateResponse) validate() error {
    var errs []string
    if c.Id == nil {
        errs = append(errs, "required field `id` is missing for type `CollectionCreateResponse`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
