// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// CollectionCreateRequest represents a CollectionCreateRequest struct.
// Collection creation request
type CollectionCreateRequest struct {
    // The name of the collection
    Name                 string                 `json:"name"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for CollectionCreateRequest,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c CollectionCreateRequest) String() string {
    return fmt.Sprintf(
    	"CollectionCreateRequest[Name=%v, AdditionalProperties=%v]",
    	c.Name, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for CollectionCreateRequest.
// It customizes the JSON marshaling process for CollectionCreateRequest objects.
func (c CollectionCreateRequest) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "name"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the CollectionCreateRequest object to a map representation for JSON marshaling.
func (c CollectionCreateRequest) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    structMap["name"] = c.Name
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for CollectionCreateRequest.
// It customizes the JSON unmarshaling process for CollectionCreateRequest objects.
func (c *CollectionCreateRequest) UnmarshalJSON(input []byte) error {
    var temp tempCollectionCreateRequest
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "name")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.Name = *temp.Name
    return nil
}

// tempCollectionCreateRequest is a temporary struct used for validating the fields of CollectionCreateRequest.
type tempCollectionCreateRequest  struct {
    Name *string `json:"name"`
}

func (c *tempCollectionCreateRequest) validate() error {
    var errs []string
    if c.Name == nil {
        errs = append(errs, "required field `name` is missing for type `CollectionCreateRequest`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
