// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// CollectionItemRequest represents a CollectionItemRequest struct.
// Request to get a list of items in a collection
type CollectionItemRequest struct {
    // List of items
    Items                []CollectionItem       `json:"items"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for CollectionItemRequest,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c CollectionItemRequest) String() string {
    return fmt.Sprintf(
    	"CollectionItemRequest[Items=%v, AdditionalProperties=%v]",
    	c.Items, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for CollectionItemRequest.
// It customizes the JSON marshaling process for CollectionItemRequest objects.
func (c CollectionItemRequest) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "items"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the CollectionItemRequest object to a map representation for JSON marshaling.
func (c CollectionItemRequest) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    structMap["items"] = c.Items
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for CollectionItemRequest.
// It customizes the JSON unmarshaling process for CollectionItemRequest objects.
func (c *CollectionItemRequest) UnmarshalJSON(input []byte) error {
    var temp tempCollectionItemRequest
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "items")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.Items = *temp.Items
    return nil
}

// tempCollectionItemRequest is a temporary struct used for validating the fields of CollectionItemRequest.
type tempCollectionItemRequest  struct {
    Items *[]CollectionItem `json:"items"`
}

func (c *tempCollectionItemRequest) validate() error {
    var errs []string
    if c.Items == nil {
        errs = append(errs, "required field `items` is missing for type `CollectionItemRequest`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
