// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// CollectionItem represents a CollectionItem struct.
// Metadata about an item that is part of a collection
type CollectionItem struct {
    // The date the item was added to the collection
    AddedTime            *time.Time             `json:"added_time,omitempty"`
    // ID of the item
    Id                   string                 `json:"id"`
    // The media type of the item, such as image, video, or audio
    MediaType            *string                `json:"media_type,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for CollectionItem,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c CollectionItem) String() string {
    return fmt.Sprintf(
    	"CollectionItem[AddedTime=%v, Id=%v, MediaType=%v, AdditionalProperties=%v]",
    	c.AddedTime, c.Id, c.MediaType, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for CollectionItem.
// It customizes the JSON marshaling process for CollectionItem objects.
func (c CollectionItem) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "added_time", "id", "media_type"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the CollectionItem object to a map representation for JSON marshaling.
func (c CollectionItem) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    if c.AddedTime != nil {
        structMap["added_time"] = c.AddedTime.Format(time.RFC3339)
    }
    structMap["id"] = c.Id
    if c.MediaType != nil {
        structMap["media_type"] = c.MediaType
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for CollectionItem.
// It customizes the JSON unmarshaling process for CollectionItem objects.
func (c *CollectionItem) UnmarshalJSON(input []byte) error {
    var temp tempCollectionItem
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "added_time", "id", "media_type")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    if temp.AddedTime != nil {
        AddedTimeVal, err := time.Parse(time.RFC3339, *temp.AddedTime)
        if err != nil {
            log.Fatalf("Cannot Parse added_time as % s format.", time.RFC3339)
        }
        c.AddedTime = &AddedTimeVal
    }
    c.Id = *temp.Id
    c.MediaType = temp.MediaType
    return nil
}

// tempCollectionItem is a temporary struct used for validating the fields of CollectionItem.
type tempCollectionItem  struct {
    AddedTime *string `json:"added_time,omitempty"`
    Id        *string `json:"id"`
    MediaType *string `json:"media_type,omitempty"`
}

func (c *tempCollectionItem) validate() error {
    var errs []string
    if c.Id == nil {
        errs = append(errs, "required field `id` is missing for type `CollectionItem`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
