// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// ContributorProfileDataList represents a ContributorProfileDataList struct.
// List of contributor profiles
type ContributorProfileDataList struct {
    // Conributor profiles
    Data                 []ContributorProfile   `json:"data,omitempty"`
    // Error list; appears only if there was an error
    Errors               []Error                `json:"errors,omitempty"`
    // Error message
    Message              *string                `json:"message,omitempty"`
    // Page of response
    Page                 *int                   `json:"page,omitempty"`
    // Number of contributors per page
    PerPage              *int                   `json:"per_page,omitempty"`
    // Total count of contributors for this request
    TotalCount           *int                   `json:"total_count,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for ContributorProfileDataList,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c ContributorProfileDataList) String() string {
    return fmt.Sprintf(
    	"ContributorProfileDataList[Data=%v, Errors=%v, Message=%v, Page=%v, PerPage=%v, TotalCount=%v, AdditionalProperties=%v]",
    	c.Data, c.Errors, c.Message, c.Page, c.PerPage, c.TotalCount, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for ContributorProfileDataList.
// It customizes the JSON marshaling process for ContributorProfileDataList objects.
func (c ContributorProfileDataList) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "data", "errors", "message", "page", "per_page", "total_count"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the ContributorProfileDataList object to a map representation for JSON marshaling.
func (c ContributorProfileDataList) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    if c.Data != nil {
        structMap["data"] = c.Data
    }
    if c.Errors != nil {
        structMap["errors"] = c.Errors
    }
    if c.Message != nil {
        structMap["message"] = c.Message
    }
    if c.Page != nil {
        structMap["page"] = c.Page
    }
    if c.PerPage != nil {
        structMap["per_page"] = c.PerPage
    }
    if c.TotalCount != nil {
        structMap["total_count"] = c.TotalCount
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for ContributorProfileDataList.
// It customizes the JSON unmarshaling process for ContributorProfileDataList objects.
func (c *ContributorProfileDataList) UnmarshalJSON(input []byte) error {
    var temp tempContributorProfileDataList
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "data", "errors", "message", "page", "per_page", "total_count")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.Data = temp.Data
    c.Errors = temp.Errors
    c.Message = temp.Message
    c.Page = temp.Page
    c.PerPage = temp.PerPage
    c.TotalCount = temp.TotalCount
    return nil
}

// tempContributorProfileDataList is a temporary struct used for validating the fields of ContributorProfileDataList.
type tempContributorProfileDataList  struct {
    Data       []ContributorProfile `json:"data,omitempty"`
    Errors     []Error              `json:"errors,omitempty"`
    Message    *string              `json:"message,omitempty"`
    Page       *int                 `json:"page,omitempty"`
    PerPage    *int                 `json:"per_page,omitempty"`
    TotalCount *int                 `json:"total_count,omitempty"`
}
