// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// ContributorProfile represents a ContributorProfile struct.
// Contributor profile data
type ContributorProfile struct {
    // Short description of the contributors' library
    About                *string                        `json:"about,omitempty"`
    // Type of content that the contributor specializes in (photographer, illustrator, etc)
    ContributorType      []string                       `json:"contributor_type,omitempty"`
    // Preferred name to be displayed for the contributor
    DisplayName          *string                        `json:"display_name,omitempty"`
    // List of equipment used by the contributor (Canon EOS 5D Mark II, etc)
    Equipment            []string                       `json:"equipment,omitempty"`
    // Contributor ID
    Id                   string                         `json:"id"`
    // Country code representing the contributor's locale
    Location             *string                        `json:"location,omitempty"`
    // Web URL for the contributors' profile
    PortfolioUrl         *string                        `json:"portfolio_url,omitempty"`
    // Contributor profile social media links
    SocialMedia          *ContributorProfileSocialMedia `json:"social_media,omitempty"`
    // List of styles that the contributor specializes in (lifestyle, mixed media, etc)
    Styles               []string                       `json:"styles,omitempty"`
    // Generic list of subjects for contributors' work (food_and_drink, holiday, people, etc)
    Subjects             []string                       `json:"subjects,omitempty"`
    // Personal website for the contributor
    Website              *string                        `json:"website,omitempty"`
    AdditionalProperties map[string]interface{}         `json:"_"`
}

// String implements the fmt.Stringer interface for ContributorProfile,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c ContributorProfile) String() string {
    return fmt.Sprintf(
    	"ContributorProfile[About=%v, ContributorType=%v, DisplayName=%v, Equipment=%v, Id=%v, Location=%v, PortfolioUrl=%v, SocialMedia=%v, Styles=%v, Subjects=%v, Website=%v, AdditionalProperties=%v]",
    	c.About, c.ContributorType, c.DisplayName, c.Equipment, c.Id, c.Location, c.PortfolioUrl, c.SocialMedia, c.Styles, c.Subjects, c.Website, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for ContributorProfile.
// It customizes the JSON marshaling process for ContributorProfile objects.
func (c ContributorProfile) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "about", "contributor_type", "display_name", "equipment", "id", "location", "portfolio_url", "social_media", "styles", "subjects", "website"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the ContributorProfile object to a map representation for JSON marshaling.
func (c ContributorProfile) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    if c.About != nil {
        structMap["about"] = c.About
    }
    if c.ContributorType != nil {
        structMap["contributor_type"] = c.ContributorType
    }
    if c.DisplayName != nil {
        structMap["display_name"] = c.DisplayName
    }
    if c.Equipment != nil {
        structMap["equipment"] = c.Equipment
    }
    structMap["id"] = c.Id
    if c.Location != nil {
        structMap["location"] = c.Location
    }
    if c.PortfolioUrl != nil {
        structMap["portfolio_url"] = c.PortfolioUrl
    }
    if c.SocialMedia != nil {
        structMap["social_media"] = c.SocialMedia.toMap()
    }
    if c.Styles != nil {
        structMap["styles"] = c.Styles
    }
    if c.Subjects != nil {
        structMap["subjects"] = c.Subjects
    }
    if c.Website != nil {
        structMap["website"] = c.Website
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for ContributorProfile.
// It customizes the JSON unmarshaling process for ContributorProfile objects.
func (c *ContributorProfile) UnmarshalJSON(input []byte) error {
    var temp tempContributorProfile
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "about", "contributor_type", "display_name", "equipment", "id", "location", "portfolio_url", "social_media", "styles", "subjects", "website")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.About = temp.About
    c.ContributorType = temp.ContributorType
    c.DisplayName = temp.DisplayName
    c.Equipment = temp.Equipment
    c.Id = *temp.Id
    c.Location = temp.Location
    c.PortfolioUrl = temp.PortfolioUrl
    c.SocialMedia = temp.SocialMedia
    c.Styles = temp.Styles
    c.Subjects = temp.Subjects
    c.Website = temp.Website
    return nil
}

// tempContributorProfile is a temporary struct used for validating the fields of ContributorProfile.
type tempContributorProfile  struct {
    About           *string                        `json:"about,omitempty"`
    ContributorType []string                       `json:"contributor_type,omitempty"`
    DisplayName     *string                        `json:"display_name,omitempty"`
    Equipment       []string                       `json:"equipment,omitempty"`
    Id              *string                        `json:"id"`
    Location        *string                        `json:"location,omitempty"`
    PortfolioUrl    *string                        `json:"portfolio_url,omitempty"`
    SocialMedia     *ContributorProfileSocialMedia `json:"social_media,omitempty"`
    Styles          []string                       `json:"styles,omitempty"`
    Subjects        []string                       `json:"subjects,omitempty"`
    Website         *string                        `json:"website,omitempty"`
}

func (c *tempContributorProfile) validate() error {
    var errs []string
    if c.Id == nil {
        errs = append(errs, "required field `id` is missing for type `ContributorProfile`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
