// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// CreateCatalogCollectionItems represents a CreateCatalogCollectionItems struct.
type CreateCatalogCollectionItems struct {
    Items                []CreateCatalogCollectionItem `json:"items"`
    AdditionalProperties map[string]interface{}        `json:"_"`
}

// String implements the fmt.Stringer interface for CreateCatalogCollectionItems,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (c CreateCatalogCollectionItems) String() string {
    return fmt.Sprintf(
    	"CreateCatalogCollectionItems[Items=%v, AdditionalProperties=%v]",
    	c.Items, c.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for CreateCatalogCollectionItems.
// It customizes the JSON marshaling process for CreateCatalogCollectionItems objects.
func (c CreateCatalogCollectionItems) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(c.AdditionalProperties,
        "items"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(c.toMap())
}

// toMap converts the CreateCatalogCollectionItems object to a map representation for JSON marshaling.
func (c CreateCatalogCollectionItems) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, c.AdditionalProperties)
    structMap["items"] = c.Items
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for CreateCatalogCollectionItems.
// It customizes the JSON unmarshaling process for CreateCatalogCollectionItems objects.
func (c *CreateCatalogCollectionItems) UnmarshalJSON(input []byte) error {
    var temp tempCreateCatalogCollectionItems
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "items")
    if err != nil {
    	return err
    }
    c.AdditionalProperties = additionalProperties
    
    c.Items = *temp.Items
    return nil
}

// tempCreateCatalogCollectionItems is a temporary struct used for validating the fields of CreateCatalogCollectionItems.
type tempCreateCatalogCollectionItems  struct {
    Items *[]CreateCatalogCollectionItem `json:"items"`
}

func (c *tempCreateCatalogCollectionItems) validate() error {
    var errs []string
    if c.Items == nil {
        errs = append(errs, "required field `items` is missing for type `CreateCatalogCollectionItems`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
