// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// DownloadHistoryFormatDetails represents a DownloadHistoryFormatDetails struct.
// Information about the format of a download
type DownloadHistoryFormatDetails struct {
    // The format of the downloaded media
    Format               *string                `json:"format,omitempty"`
    // The size of the downloaded media
    Size                 *string                `json:"size,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for DownloadHistoryFormatDetails,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (d DownloadHistoryFormatDetails) String() string {
    return fmt.Sprintf(
    	"DownloadHistoryFormatDetails[Format=%v, Size=%v, AdditionalProperties=%v]",
    	d.Format, d.Size, d.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for DownloadHistoryFormatDetails.
// It customizes the JSON marshaling process for DownloadHistoryFormatDetails objects.
func (d DownloadHistoryFormatDetails) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(d.AdditionalProperties,
        "format", "size"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(d.toMap())
}

// toMap converts the DownloadHistoryFormatDetails object to a map representation for JSON marshaling.
func (d DownloadHistoryFormatDetails) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, d.AdditionalProperties)
    if d.Format != nil {
        structMap["format"] = d.Format
    }
    if d.Size != nil {
        structMap["size"] = d.Size
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for DownloadHistoryFormatDetails.
// It customizes the JSON unmarshaling process for DownloadHistoryFormatDetails objects.
func (d *DownloadHistoryFormatDetails) UnmarshalJSON(input []byte) error {
    var temp tempDownloadHistoryFormatDetails
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "format", "size")
    if err != nil {
    	return err
    }
    d.AdditionalProperties = additionalProperties
    
    d.Format = temp.Format
    d.Size = temp.Size
    return nil
}

// tempDownloadHistoryFormatDetails is a temporary struct used for validating the fields of DownloadHistoryFormatDetails.
type tempDownloadHistoryFormatDetails  struct {
    Format *string `json:"format,omitempty"`
    Size   *string `json:"size,omitempty"`
}
