// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// DownloadHistory represents a DownloadHistory struct.
// Information about a downloaded media item. Applicable for all media types, only one of 'audio', 'image' or 'video' will be in a single DownloadHistory object
type DownloadHistory struct {
    // Information about the downloaded media
    Audio                *DownloadHistoryMediaDetails    `json:"audio,omitempty"`
    // Date the media was downloaded the first time
    DownloadTime         time.Time                       `json:"download_time"`
    // ID of the download
    Id                   string                          `json:"id"`
    // Information about the downloaded media
    Image                *DownloadHistoryMediaDetails    `json:"image,omitempty"`
    // Specifies if the media is downloadable via its respective downloads endpoint
    IsDownloadable       *bool                           `json:"is_downloadable,omitempty"`
    // The name of the license of this download
    License              string                          `json:"license"`
    // The metadata that was passed in the original licensing request
    Metadata             *interface{}                    `json:"metadata,omitempty"`
    // Pricing information for revenue-sharing transactions
    Revshare             *DownloadHistoryRevshareDetails `json:"revshare,omitempty"`
    // ID of the subscription used to perform this download
    SubscriptionId       *string                         `json:"subscription_id,omitempty"`
    // Information about a user
    User                 *DownloadHistoryUserDetails     `json:"user,omitempty"`
    // Information about the downloaded media
    Video                *DownloadHistoryMediaDetails    `json:"video,omitempty"`
    AdditionalProperties map[string]interface{}          `json:"_"`
}

// String implements the fmt.Stringer interface for DownloadHistory,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (d DownloadHistory) String() string {
    return fmt.Sprintf(
    	"DownloadHistory[Audio=%v, DownloadTime=%v, Id=%v, Image=%v, IsDownloadable=%v, License=%v, Metadata=%v, Revshare=%v, SubscriptionId=%v, User=%v, Video=%v, AdditionalProperties=%v]",
    	d.Audio, d.DownloadTime, d.Id, d.Image, d.IsDownloadable, d.License, d.Metadata, d.Revshare, d.SubscriptionId, d.User, d.Video, d.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for DownloadHistory.
// It customizes the JSON marshaling process for DownloadHistory objects.
func (d DownloadHistory) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(d.AdditionalProperties,
        "audio", "download_time", "id", "image", "is_downloadable", "license", "metadata", "revshare", "subscription_id", "user", "video"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(d.toMap())
}

// toMap converts the DownloadHistory object to a map representation for JSON marshaling.
func (d DownloadHistory) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, d.AdditionalProperties)
    if d.Audio != nil {
        structMap["audio"] = d.Audio.toMap()
    }
    structMap["download_time"] = d.DownloadTime.Format(time.RFC3339)
    structMap["id"] = d.Id
    if d.Image != nil {
        structMap["image"] = d.Image.toMap()
    }
    if d.IsDownloadable != nil {
        structMap["is_downloadable"] = d.IsDownloadable
    }
    structMap["license"] = d.License
    if d.Metadata != nil {
        structMap["metadata"] = d.Metadata
    }
    if d.Revshare != nil {
        structMap["revshare"] = d.Revshare.toMap()
    }
    if d.SubscriptionId != nil {
        structMap["subscription_id"] = d.SubscriptionId
    }
    if d.User != nil {
        structMap["user"] = d.User.toMap()
    }
    if d.Video != nil {
        structMap["video"] = d.Video.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for DownloadHistory.
// It customizes the JSON unmarshaling process for DownloadHistory objects.
func (d *DownloadHistory) UnmarshalJSON(input []byte) error {
    var temp tempDownloadHistory
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "audio", "download_time", "id", "image", "is_downloadable", "license", "metadata", "revshare", "subscription_id", "user", "video")
    if err != nil {
    	return err
    }
    d.AdditionalProperties = additionalProperties
    
    d.Audio = temp.Audio
    DownloadTimeVal, err := time.Parse(time.RFC3339, *temp.DownloadTime)
    if err != nil {
        log.Fatalf("Cannot Parse download_time as % s format.", time.RFC3339)
    }
    d.DownloadTime = DownloadTimeVal
    d.Id = *temp.Id
    d.Image = temp.Image
    d.IsDownloadable = temp.IsDownloadable
    d.License = *temp.License
    d.Metadata = temp.Metadata
    d.Revshare = temp.Revshare
    d.SubscriptionId = temp.SubscriptionId
    d.User = temp.User
    d.Video = temp.Video
    return nil
}

// tempDownloadHistory is a temporary struct used for validating the fields of DownloadHistory.
type tempDownloadHistory  struct {
    Audio          *DownloadHistoryMediaDetails    `json:"audio,omitempty"`
    DownloadTime   *string                         `json:"download_time"`
    Id             *string                         `json:"id"`
    Image          *DownloadHistoryMediaDetails    `json:"image,omitempty"`
    IsDownloadable *bool                           `json:"is_downloadable,omitempty"`
    License        *string                         `json:"license"`
    Metadata       *interface{}                    `json:"metadata,omitempty"`
    Revshare       *DownloadHistoryRevshareDetails `json:"revshare,omitempty"`
    SubscriptionId *string                         `json:"subscription_id,omitempty"`
    User           *DownloadHistoryUserDetails     `json:"user,omitempty"`
    Video          *DownloadHistoryMediaDetails    `json:"video,omitempty"`
}

func (d *tempDownloadHistory) validate() error {
    var errs []string
    if d.DownloadTime == nil {
        errs = append(errs, "required field `download_time` is missing for type `DownloadHistory`")
    }
    if d.Id == nil {
        errs = append(errs, "required field `id` is missing for type `DownloadHistory`")
    }
    if d.License == nil {
        errs = append(errs, "required field `license` is missing for type `DownloadHistory`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
