// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// DownloadHistoryRevshareDetails represents a DownloadHistoryRevshareDetails struct.
// Pricing information for revenue-sharing transactions
type DownloadHistoryRevshareDetails struct {
    // The amount charged for the license
    PurchaseAmount       string                 `json:"purchase_amount"`
    // The currency the amount was charged in
    PurchaseCurrency     string                 `json:"purchase_currency"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for DownloadHistoryRevshareDetails,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (d DownloadHistoryRevshareDetails) String() string {
    return fmt.Sprintf(
    	"DownloadHistoryRevshareDetails[PurchaseAmount=%v, PurchaseCurrency=%v, AdditionalProperties=%v]",
    	d.PurchaseAmount, d.PurchaseCurrency, d.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for DownloadHistoryRevshareDetails.
// It customizes the JSON marshaling process for DownloadHistoryRevshareDetails objects.
func (d DownloadHistoryRevshareDetails) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(d.AdditionalProperties,
        "purchase_amount", "purchase_currency"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(d.toMap())
}

// toMap converts the DownloadHistoryRevshareDetails object to a map representation for JSON marshaling.
func (d DownloadHistoryRevshareDetails) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, d.AdditionalProperties)
    structMap["purchase_amount"] = d.PurchaseAmount
    structMap["purchase_currency"] = d.PurchaseCurrency
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for DownloadHistoryRevshareDetails.
// It customizes the JSON unmarshaling process for DownloadHistoryRevshareDetails objects.
func (d *DownloadHistoryRevshareDetails) UnmarshalJSON(input []byte) error {
    var temp tempDownloadHistoryRevshareDetails
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "purchase_amount", "purchase_currency")
    if err != nil {
    	return err
    }
    d.AdditionalProperties = additionalProperties
    
    d.PurchaseAmount = *temp.PurchaseAmount
    d.PurchaseCurrency = *temp.PurchaseCurrency
    return nil
}

// tempDownloadHistoryRevshareDetails is a temporary struct used for validating the fields of DownloadHistoryRevshareDetails.
type tempDownloadHistoryRevshareDetails  struct {
    PurchaseAmount   *string `json:"purchase_amount"`
    PurchaseCurrency *string `json:"purchase_currency"`
}

func (d *tempDownloadHistoryRevshareDetails) validate() error {
    var errs []string
    if d.PurchaseAmount == nil {
        errs = append(errs, "required field `purchase_amount` is missing for type `DownloadHistoryRevshareDetails`")
    }
    if d.PurchaseCurrency == nil {
        errs = append(errs, "required field `purchase_currency` is missing for type `DownloadHistoryRevshareDetails`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
