// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// EditorialUpdatedContent represents a EditorialUpdatedContent struct.
// Metadata about updated editorial content
type EditorialUpdatedContent struct {
    Aspect               *float64               `json:"aspect,omitempty"`
    // Asset information, including size and thumbnail URLs
    Assets               *EditorialAssets       `json:"assets,omitempty"`
    Byline               *string                `json:"byline,omitempty"`
    Caption              *string                `json:"caption,omitempty"`
    // List of categories
    Categories           []EditorialCategory    `json:"categories,omitempty"`
    CommercialStatus     *CommercialStatus      `json:"commercial_status,omitempty"`
    CreatedTime          *time.Time             `json:"created_time,omitempty"`
    DateTaken            *time.Time             `json:"date_taken,omitempty"`
    Description          *string                `json:"description,omitempty"`
    Id                   string                 `json:"id"`
    Keywords             []string               `json:"keywords,omitempty"`
    Rights               *Rights                `json:"rights,omitempty"`
    SpecialInstructions  *string                `json:"special_instructions,omitempty"`
    SupplierCode         *string                `json:"supplier_code,omitempty"`
    Title                *string                `json:"title,omitempty"`
    UpdatedTime          *time.Time             `json:"updated_time,omitempty"`
    Updates              []string               `json:"updates,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for EditorialUpdatedContent,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (e EditorialUpdatedContent) String() string {
    return fmt.Sprintf(
    	"EditorialUpdatedContent[Aspect=%v, Assets=%v, Byline=%v, Caption=%v, Categories=%v, CommercialStatus=%v, CreatedTime=%v, DateTaken=%v, Description=%v, Id=%v, Keywords=%v, Rights=%v, SpecialInstructions=%v, SupplierCode=%v, Title=%v, UpdatedTime=%v, Updates=%v, AdditionalProperties=%v]",
    	e.Aspect, e.Assets, e.Byline, e.Caption, e.Categories, e.CommercialStatus, e.CreatedTime, e.DateTaken, e.Description, e.Id, e.Keywords, e.Rights, e.SpecialInstructions, e.SupplierCode, e.Title, e.UpdatedTime, e.Updates, e.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for EditorialUpdatedContent.
// It customizes the JSON marshaling process for EditorialUpdatedContent objects.
func (e EditorialUpdatedContent) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(e.AdditionalProperties,
        "aspect", "assets", "byline", "caption", "categories", "commercial_status", "created_time", "date_taken", "description", "id", "keywords", "rights", "special_instructions", "supplier_code", "title", "updated_time", "updates"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(e.toMap())
}

// toMap converts the EditorialUpdatedContent object to a map representation for JSON marshaling.
func (e EditorialUpdatedContent) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, e.AdditionalProperties)
    if e.Aspect != nil {
        structMap["aspect"] = e.Aspect
    }
    if e.Assets != nil {
        structMap["assets"] = e.Assets.toMap()
    }
    if e.Byline != nil {
        structMap["byline"] = e.Byline
    }
    if e.Caption != nil {
        structMap["caption"] = e.Caption
    }
    if e.Categories != nil {
        structMap["categories"] = e.Categories
    }
    if e.CommercialStatus != nil {
        structMap["commercial_status"] = e.CommercialStatus.toMap()
    }
    if e.CreatedTime != nil {
        structMap["created_time"] = e.CreatedTime.Format(time.RFC3339)
    }
    if e.DateTaken != nil {
        structMap["date_taken"] = e.DateTaken.Format(DEFAULT_DATE)
    }
    if e.Description != nil {
        structMap["description"] = e.Description
    }
    structMap["id"] = e.Id
    if e.Keywords != nil {
        structMap["keywords"] = e.Keywords
    }
    if e.Rights != nil {
        structMap["rights"] = e.Rights.toMap()
    }
    if e.SpecialInstructions != nil {
        structMap["special_instructions"] = e.SpecialInstructions
    }
    if e.SupplierCode != nil {
        structMap["supplier_code"] = e.SupplierCode
    }
    if e.Title != nil {
        structMap["title"] = e.Title
    }
    if e.UpdatedTime != nil {
        structMap["updated_time"] = e.UpdatedTime.Format(time.RFC3339)
    }
    if e.Updates != nil {
        structMap["updates"] = e.Updates
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for EditorialUpdatedContent.
// It customizes the JSON unmarshaling process for EditorialUpdatedContent objects.
func (e *EditorialUpdatedContent) UnmarshalJSON(input []byte) error {
    var temp tempEditorialUpdatedContent
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "aspect", "assets", "byline", "caption", "categories", "commercial_status", "created_time", "date_taken", "description", "id", "keywords", "rights", "special_instructions", "supplier_code", "title", "updated_time", "updates")
    if err != nil {
    	return err
    }
    e.AdditionalProperties = additionalProperties
    
    e.Aspect = temp.Aspect
    e.Assets = temp.Assets
    e.Byline = temp.Byline
    e.Caption = temp.Caption
    e.Categories = temp.Categories
    e.CommercialStatus = temp.CommercialStatus
    if temp.CreatedTime != nil {
        CreatedTimeVal, err := time.Parse(time.RFC3339, *temp.CreatedTime)
        if err != nil {
            log.Fatalf("Cannot Parse created_time as % s format.", time.RFC3339)
        }
        e.CreatedTime = &CreatedTimeVal
    }
    if temp.DateTaken != nil {
        DateTakenVal, err := time.Parse(DEFAULT_DATE, *temp.DateTaken)
        if err != nil {
            log.Fatalf("Cannot Parse date_taken as % s format.", DEFAULT_DATE)
        }
        e.DateTaken = &DateTakenVal
    }
    e.Description = temp.Description
    e.Id = *temp.Id
    e.Keywords = temp.Keywords
    e.Rights = temp.Rights
    e.SpecialInstructions = temp.SpecialInstructions
    e.SupplierCode = temp.SupplierCode
    e.Title = temp.Title
    if temp.UpdatedTime != nil {
        UpdatedTimeVal, err := time.Parse(time.RFC3339, *temp.UpdatedTime)
        if err != nil {
            log.Fatalf("Cannot Parse updated_time as % s format.", time.RFC3339)
        }
        e.UpdatedTime = &UpdatedTimeVal
    }
    e.Updates = temp.Updates
    return nil
}

// tempEditorialUpdatedContent is a temporary struct used for validating the fields of EditorialUpdatedContent.
type tempEditorialUpdatedContent  struct {
    Aspect              *float64            `json:"aspect,omitempty"`
    Assets              *EditorialAssets    `json:"assets,omitempty"`
    Byline              *string             `json:"byline,omitempty"`
    Caption             *string             `json:"caption,omitempty"`
    Categories          []EditorialCategory `json:"categories,omitempty"`
    CommercialStatus    *CommercialStatus   `json:"commercial_status,omitempty"`
    CreatedTime         *string             `json:"created_time,omitempty"`
    DateTaken           *string             `json:"date_taken,omitempty"`
    Description         *string             `json:"description,omitempty"`
    Id                  *string             `json:"id"`
    Keywords            []string            `json:"keywords,omitempty"`
    Rights              *Rights             `json:"rights,omitempty"`
    SpecialInstructions *string             `json:"special_instructions,omitempty"`
    SupplierCode        *string             `json:"supplier_code,omitempty"`
    Title               *string             `json:"title,omitempty"`
    UpdatedTime         *string             `json:"updated_time,omitempty"`
    Updates             []string            `json:"updates,omitempty"`
}

func (e *tempEditorialUpdatedContent) validate() error {
    var errs []string
    if e.Id == nil {
        errs = append(errs, "required field `id` is missing for type `EditorialUpdatedContent`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
