// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// EditorialImageContentDataList represents a EditorialImageContentDataList struct.
// List of editorial items
type EditorialImageContentDataList struct {
    // Editorial items
    Data                 []EditorialContent     `json:"data,omitempty"`
    // Error list; appears only if there was an error
    Errors               []Error                `json:"errors,omitempty"`
    // Optional error message
    Message              *string                `json:"message,omitempty"`
    // Current page of the response
    Page                 *int                   `json:"page,omitempty"`
    // Number of results per page
    PerPage              *int                   `json:"per_page,omitempty"`
    // Total count of all results
    TotalCount           *int                   `json:"total_count,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for EditorialImageContentDataList,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (e EditorialImageContentDataList) String() string {
    return fmt.Sprintf(
    	"EditorialImageContentDataList[Data=%v, Errors=%v, Message=%v, Page=%v, PerPage=%v, TotalCount=%v, AdditionalProperties=%v]",
    	e.Data, e.Errors, e.Message, e.Page, e.PerPage, e.TotalCount, e.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for EditorialImageContentDataList.
// It customizes the JSON marshaling process for EditorialImageContentDataList objects.
func (e EditorialImageContentDataList) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(e.AdditionalProperties,
        "data", "errors", "message", "page", "per_page", "total_count"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(e.toMap())
}

// toMap converts the EditorialImageContentDataList object to a map representation for JSON marshaling.
func (e EditorialImageContentDataList) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, e.AdditionalProperties)
    if e.Data != nil {
        structMap["data"] = e.Data
    }
    if e.Errors != nil {
        structMap["errors"] = e.Errors
    }
    if e.Message != nil {
        structMap["message"] = e.Message
    }
    if e.Page != nil {
        structMap["page"] = e.Page
    }
    if e.PerPage != nil {
        structMap["per_page"] = e.PerPage
    }
    if e.TotalCount != nil {
        structMap["total_count"] = e.TotalCount
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for EditorialImageContentDataList.
// It customizes the JSON unmarshaling process for EditorialImageContentDataList objects.
func (e *EditorialImageContentDataList) UnmarshalJSON(input []byte) error {
    var temp tempEditorialImageContentDataList
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "data", "errors", "message", "page", "per_page", "total_count")
    if err != nil {
    	return err
    }
    e.AdditionalProperties = additionalProperties
    
    e.Data = temp.Data
    e.Errors = temp.Errors
    e.Message = temp.Message
    e.Page = temp.Page
    e.PerPage = temp.PerPage
    e.TotalCount = temp.TotalCount
    return nil
}

// tempEditorialImageContentDataList is a temporary struct used for validating the fields of EditorialImageContentDataList.
type tempEditorialImageContentDataList  struct {
    Data       []EditorialContent `json:"data,omitempty"`
    Errors     []Error            `json:"errors,omitempty"`
    Message    *string            `json:"message,omitempty"`
    Page       *int               `json:"page,omitempty"`
    PerPage    *int               `json:"per_page,omitempty"`
    TotalCount *int               `json:"total_count,omitempty"`
}
