// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// EditorialVideoAssets represents a EditorialVideoAssets struct.
// Asset information, including size and thumbnail URLs
type EditorialVideoAssets struct {
    // Video asset information
    Original             *VideoSizeDetails      `json:"original,omitempty"`
    // Video preview information
    PreviewMp4           *VideoPreviewUrl       `json:"preview_mp4,omitempty"`
    // Video preview information
    PreviewWebm          *VideoPreviewUrl       `json:"preview_webm,omitempty"`
    // Video preview information
    ThumbJpg             *VideoPreviewUrl       `json:"thumb_jpg,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for EditorialVideoAssets,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (e EditorialVideoAssets) String() string {
    return fmt.Sprintf(
    	"EditorialVideoAssets[Original=%v, PreviewMp4=%v, PreviewWebm=%v, ThumbJpg=%v, AdditionalProperties=%v]",
    	e.Original, e.PreviewMp4, e.PreviewWebm, e.ThumbJpg, e.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for EditorialVideoAssets.
// It customizes the JSON marshaling process for EditorialVideoAssets objects.
func (e EditorialVideoAssets) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(e.AdditionalProperties,
        "original", "preview_mp4", "preview_webm", "thumb_jpg"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(e.toMap())
}

// toMap converts the EditorialVideoAssets object to a map representation for JSON marshaling.
func (e EditorialVideoAssets) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, e.AdditionalProperties)
    if e.Original != nil {
        structMap["original"] = e.Original.toMap()
    }
    if e.PreviewMp4 != nil {
        structMap["preview_mp4"] = e.PreviewMp4.toMap()
    }
    if e.PreviewWebm != nil {
        structMap["preview_webm"] = e.PreviewWebm.toMap()
    }
    if e.ThumbJpg != nil {
        structMap["thumb_jpg"] = e.ThumbJpg.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for EditorialVideoAssets.
// It customizes the JSON unmarshaling process for EditorialVideoAssets objects.
func (e *EditorialVideoAssets) UnmarshalJSON(input []byte) error {
    var temp tempEditorialVideoAssets
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "original", "preview_mp4", "preview_webm", "thumb_jpg")
    if err != nil {
    	return err
    }
    e.AdditionalProperties = additionalProperties
    
    e.Original = temp.Original
    e.PreviewMp4 = temp.PreviewMp4
    e.PreviewWebm = temp.PreviewWebm
    e.ThumbJpg = temp.ThumbJpg
    return nil
}

// tempEditorialVideoAssets is a temporary struct used for validating the fields of EditorialVideoAssets.
type tempEditorialVideoAssets  struct {
    Original    *VideoSizeDetails `json:"original,omitempty"`
    PreviewMp4  *VideoPreviewUrl  `json:"preview_mp4,omitempty"`
    PreviewWebm *VideoPreviewUrl  `json:"preview_webm,omitempty"`
    ThumbJpg    *VideoPreviewUrl  `json:"thumb_jpg,omitempty"`
}
