// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// EndType represents a EndType struct.
// A high-level description of how a region ends
type EndType struct {
    // The beat, relative to the start of the active region, at which the end_type begins; in other words, the ending starts on this beat of the region
    Beat                 float64                `json:"beat"`
    // The type of event
    Event                EventEnum              `json:"event"`
    // The specific action to perform; if the event type is "ending" then this must be "ringout" and if event type is "transition" this must be "cut"
    Type                 TypeEnum               `json:"type"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for EndType,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (e EndType) String() string {
    return fmt.Sprintf(
    	"EndType[Beat=%v, Event=%v, Type=%v, AdditionalProperties=%v]",
    	e.Beat, e.Event, e.Type, e.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for EndType.
// It customizes the JSON marshaling process for EndType objects.
func (e EndType) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(e.AdditionalProperties,
        "beat", "event", "type"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(e.toMap())
}

// toMap converts the EndType object to a map representation for JSON marshaling.
func (e EndType) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, e.AdditionalProperties)
    structMap["beat"] = e.Beat
    structMap["event"] = e.Event
    structMap["type"] = e.Type
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for EndType.
// It customizes the JSON unmarshaling process for EndType objects.
func (e *EndType) UnmarshalJSON(input []byte) error {
    var temp tempEndType
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "beat", "event", "type")
    if err != nil {
    	return err
    }
    e.AdditionalProperties = additionalProperties
    
    e.Beat = *temp.Beat
    e.Event = *temp.Event
    e.Type = *temp.Type
    return nil
}

// tempEndType is a temporary struct used for validating the fields of EndType.
type tempEndType  struct {
    Beat  *float64   `json:"beat"`
    Event *EventEnum `json:"event"`
    Type  *TypeEnum  `json:"type"`
}

func (e *tempEndType) validate() error {
    var errs []string
    if e.Beat == nil {
        errs = append(errs, "required field `beat` is missing for type `EndType`")
    }
    if e.Event == nil {
        errs = append(errs, "required field `event` is missing for type `EndType`")
    }
    if e.Type == nil {
        errs = append(errs, "required field `type` is missing for type `EndType`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
