// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// FeaturedCollectionDataList represents a FeaturedCollectionDataList struct.
// List of featured collections
type FeaturedCollectionDataList struct {
    // Featured collections
    Data                 []FeaturedCollection   `json:"data,omitempty"`
    // Error list; appears only if there was an error
    Errors               []Error                `json:"errors,omitempty"`
    // Server-generated message, if any
    Message              *string                `json:"message,omitempty"`
    // Current page that is returned
    Page                 *int                   `json:"page,omitempty"`
    // Number of results per page
    PerPage              *int                   `json:"per_page,omitempty"`
    // Total count of all results across all pages
    TotalCount           *int                   `json:"total_count,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for FeaturedCollectionDataList,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (f FeaturedCollectionDataList) String() string {
    return fmt.Sprintf(
    	"FeaturedCollectionDataList[Data=%v, Errors=%v, Message=%v, Page=%v, PerPage=%v, TotalCount=%v, AdditionalProperties=%v]",
    	f.Data, f.Errors, f.Message, f.Page, f.PerPage, f.TotalCount, f.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for FeaturedCollectionDataList.
// It customizes the JSON marshaling process for FeaturedCollectionDataList objects.
func (f FeaturedCollectionDataList) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(f.AdditionalProperties,
        "data", "errors", "message", "page", "per_page", "total_count"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(f.toMap())
}

// toMap converts the FeaturedCollectionDataList object to a map representation for JSON marshaling.
func (f FeaturedCollectionDataList) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, f.AdditionalProperties)
    if f.Data != nil {
        structMap["data"] = f.Data
    }
    if f.Errors != nil {
        structMap["errors"] = f.Errors
    }
    if f.Message != nil {
        structMap["message"] = f.Message
    }
    if f.Page != nil {
        structMap["page"] = f.Page
    }
    if f.PerPage != nil {
        structMap["per_page"] = f.PerPage
    }
    if f.TotalCount != nil {
        structMap["total_count"] = f.TotalCount
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for FeaturedCollectionDataList.
// It customizes the JSON unmarshaling process for FeaturedCollectionDataList objects.
func (f *FeaturedCollectionDataList) UnmarshalJSON(input []byte) error {
    var temp tempFeaturedCollectionDataList
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "data", "errors", "message", "page", "per_page", "total_count")
    if err != nil {
    	return err
    }
    f.AdditionalProperties = additionalProperties
    
    f.Data = temp.Data
    f.Errors = temp.Errors
    f.Message = temp.Message
    f.Page = temp.Page
    f.PerPage = temp.PerPage
    f.TotalCount = temp.TotalCount
    return nil
}

// tempFeaturedCollectionDataList is a temporary struct used for validating the fields of FeaturedCollectionDataList.
type tempFeaturedCollectionDataList  struct {
    Data       []FeaturedCollection `json:"data,omitempty"`
    Errors     []Error              `json:"errors,omitempty"`
    Message    *string              `json:"message,omitempty"`
    Page       *int                 `json:"page,omitempty"`
    PerPage    *int                 `json:"per_page,omitempty"`
    TotalCount *int                 `json:"total_count,omitempty"`
}
