// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// GenreList represents a GenreList struct.
// List of audio genres
type GenreList struct {
    // List of genres
    Data []string `json:"data"`
}

// String implements the fmt.Stringer interface for GenreList,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (g GenreList) String() string {
    return fmt.Sprintf(
    	"GenreList[Data=%v]",
    	g.Data)
}

// MarshalJSON implements the json.Marshaler interface for GenreList.
// It customizes the JSON marshaling process for GenreList objects.
func (g GenreList) MarshalJSON() (
    []byte,
    error) {
    return json.Marshal(g.toMap())
}

// toMap converts the GenreList object to a map representation for JSON marshaling.
func (g GenreList) toMap() map[string]any {
    structMap := make(map[string]any)
    structMap["data"] = g.Data
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for GenreList.
// It customizes the JSON unmarshaling process for GenreList objects.
func (g *GenreList) UnmarshalJSON(input []byte) error {
    var temp tempGenreList
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    
    g.Data = *temp.Data
    return nil
}

// tempGenreList is a temporary struct used for validating the fields of GenreList.
type tempGenreList  struct {
    Data *[]string `json:"data"`
}

func (g *tempGenreList) validate() error {
    var errs []string
    if g.Data == nil {
        errs = append(errs, "required field `data` is missing for type `GenreList`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
