// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
)

// GetKeywordsAssetId represents a GetKeywordsAssetId struct.
// This is a container for one-of cases.
type GetKeywordsAssetId struct {
    value    any
    isString bool
}

// String implements the fmt.Stringer interface for GetKeywordsAssetId,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (g GetKeywordsAssetId) String() string {
    return fmt.Sprintf("%v", g.value)
}

// MarshalJSON implements the json.Marshaler interface for GetKeywordsAssetId.
// It customizes the JSON marshaling process for GetKeywordsAssetId objects.
func (g GetKeywordsAssetId) MarshalJSON() (
    []byte,
    error) {
    if g.value == nil {
        return nil, errors.New("No underlying type is set. Please use any of the `models.GetKeywordsAssetIdContainer.From*` functions to initialize the GetKeywordsAssetId object.")
    }
    return json.Marshal(g.toMap())
}

// toMap converts the GetKeywordsAssetId object to a map representation for JSON marshaling.
func (g *GetKeywordsAssetId) toMap() any {
    switch obj := g.value.(type) {
    case *string:
        return *obj
    }
    return nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for GetKeywordsAssetId.
// It customizes the JSON unmarshaling process for GetKeywordsAssetId objects.
func (g *GetKeywordsAssetId) UnmarshalJSON(input []byte) error {
    result, err := UnmarshallOneOf(input,
        NewTypeHolder(new(string), false, &g.isString),
    )
    
    g.value = result
    return err
}

func (g *GetKeywordsAssetId) AsString() (
    *string,
    bool) {
    if !g.isString {
        return nil, false
    }
    return g.value.(*string), true
}

// internalGetKeywordsAssetId represents a getKeywordsAssetId struct.
// This is a container for one-of cases.
type internalGetKeywordsAssetId struct {}

var GetKeywordsAssetIdContainer internalGetKeywordsAssetId

// The internalGetKeywordsAssetId instance, wrapping the provided string value.
func (g *internalGetKeywordsAssetId) FromString(val string) GetKeywordsAssetId {
    return GetKeywordsAssetId{value: &val}
}
