// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// ImageDataList represents a ImageDataList struct.
// List of images
type ImageDataList struct {
    // Images
    Data                 []Image                `json:"data,omitempty"`
    // Error list; appears only if there was an error
    Errors               []Error                `json:"errors,omitempty"`
    // Server-generated message, if any
    Message              *string                `json:"message,omitempty"`
    // Current page that is returned
    Page                 *int                   `json:"page,omitempty"`
    // Number of results per page
    PerPage              *int                   `json:"per_page,omitempty"`
    // Total count of all results across all pages
    TotalCount           *int                   `json:"total_count,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for ImageDataList,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i ImageDataList) String() string {
    return fmt.Sprintf(
    	"ImageDataList[Data=%v, Errors=%v, Message=%v, Page=%v, PerPage=%v, TotalCount=%v, AdditionalProperties=%v]",
    	i.Data, i.Errors, i.Message, i.Page, i.PerPage, i.TotalCount, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for ImageDataList.
// It customizes the JSON marshaling process for ImageDataList objects.
func (i ImageDataList) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "data", "errors", "message", "page", "per_page", "total_count"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the ImageDataList object to a map representation for JSON marshaling.
func (i ImageDataList) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.Data != nil {
        structMap["data"] = i.Data
    }
    if i.Errors != nil {
        structMap["errors"] = i.Errors
    }
    if i.Message != nil {
        structMap["message"] = i.Message
    }
    if i.Page != nil {
        structMap["page"] = i.Page
    }
    if i.PerPage != nil {
        structMap["per_page"] = i.PerPage
    }
    if i.TotalCount != nil {
        structMap["total_count"] = i.TotalCount
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for ImageDataList.
// It customizes the JSON unmarshaling process for ImageDataList objects.
func (i *ImageDataList) UnmarshalJSON(input []byte) error {
    var temp tempImageDataList
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "data", "errors", "message", "page", "per_page", "total_count")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.Data = temp.Data
    i.Errors = temp.Errors
    i.Message = temp.Message
    i.Page = temp.Page
    i.PerPage = temp.PerPage
    i.TotalCount = temp.TotalCount
    return nil
}

// tempImageDataList is a temporary struct used for validating the fields of ImageDataList.
type tempImageDataList  struct {
    Data       []Image `json:"data,omitempty"`
    Errors     []Error `json:"errors,omitempty"`
    Message    *string `json:"message,omitempty"`
    Page       *int    `json:"page,omitempty"`
    PerPage    *int    `json:"per_page,omitempty"`
    TotalCount *int    `json:"total_count,omitempty"`
}
