// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// ImageCreateResponse represents a ImageCreateResponse struct.
// Image upload information
type ImageCreateResponse struct {
    Id                   string                 `json:"id"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for ImageCreateResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i ImageCreateResponse) String() string {
    return fmt.Sprintf(
    	"ImageCreateResponse[Id=%v, AdditionalProperties=%v]",
    	i.Id, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for ImageCreateResponse.
// It customizes the JSON marshaling process for ImageCreateResponse objects.
func (i ImageCreateResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "id"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the ImageCreateResponse object to a map representation for JSON marshaling.
func (i ImageCreateResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    structMap["id"] = i.Id
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for ImageCreateResponse.
// It customizes the JSON unmarshaling process for ImageCreateResponse objects.
func (i *ImageCreateResponse) UnmarshalJSON(input []byte) error {
    var temp tempImageCreateResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "id")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.Id = *temp.Id
    return nil
}

// tempImageCreateResponse is a temporary struct used for validating the fields of ImageCreateResponse.
type tempImageCreateResponse  struct {
    Id *string `json:"id"`
}

func (i *tempImageCreateResponse) validate() error {
    var errs []string
    if i.Id == nil {
        errs = append(errs, "required field `id` is missing for type `ImageCreateResponse`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
