// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// Image1 represents a Image1 struct.
type Image1 struct {
    // Cookie object
    AuthCookie               *Cookie                `json:"auth_cookie,omitempty"`
    // A custom height or a custom width to resize the image to, but not both (experimental)
    CustomDimensions         *CustomSizeDimensions  `json:"custom_dimensions,omitempty"`
    // Set to true to acknowledge the editorial agreement
    EditorialAcknowledgement *bool                  `json:"editorial_acknowledgement,omitempty"`
    // (Deprecated) Image format to download
    Format                   *FormatEnum            `json:"format,omitempty"`
    // Image ID
    ImageId                  *string                `json:"image_id,omitempty"`
    // Additional information for license requests for enterprise accounts and API subscriptions, 4 fields maximum; which fields are required is set by the account holder
    Metadata                 *interface{}           `json:"metadata,omitempty"`
    // For revenue-sharing transactions, the final cost to the end customer as a floating-point number in the transaction currency, such as 12.34
    Price                    *float64               `json:"price,omitempty"`
    // ID of the search that led to this licensing transaction
    SearchId                 *string                `json:"search_id,omitempty"`
    // (Deprecated)
    ShowModal                *bool                  `json:"show_modal,omitempty"`                // Deprecated
    // Image size to download
    Size                     *Size2Enum             `json:"size,omitempty"`
    // ID of the subscription to use for the download.
    SubscriptionId           *string                `json:"subscription_id,omitempty"`
    // (Deprecated)
    VerificationCode         *string                `json:"verification_code,omitempty"`         // Deprecated
    AdditionalProperties     map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Image1,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i Image1) String() string {
    return fmt.Sprintf(
    	"Image1[AuthCookie=%v, CustomDimensions=%v, EditorialAcknowledgement=%v, Format=%v, ImageId=%v, Metadata=%v, Price=%v, SearchId=%v, ShowModal=%v, Size=%v, SubscriptionId=%v, VerificationCode=%v, AdditionalProperties=%v]",
    	i.AuthCookie, i.CustomDimensions, i.EditorialAcknowledgement, i.Format, i.ImageId, i.Metadata, i.Price, i.SearchId, i.ShowModal, i.Size, i.SubscriptionId, i.VerificationCode, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Image1.
// It customizes the JSON marshaling process for Image1 objects.
func (i Image1) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "auth_cookie", "custom_dimensions", "editorial_acknowledgement", "format", "image_id", "metadata", "price", "search_id", "show_modal", "size", "subscription_id", "verification_code"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the Image1 object to a map representation for JSON marshaling.
func (i Image1) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.AuthCookie != nil {
        structMap["auth_cookie"] = i.AuthCookie.toMap()
    }
    if i.CustomDimensions != nil {
        structMap["custom_dimensions"] = i.CustomDimensions.toMap()
    }
    if i.EditorialAcknowledgement != nil {
        structMap["editorial_acknowledgement"] = i.EditorialAcknowledgement
    }
    if i.Format != nil {
        structMap["format"] = i.Format
    }
    if i.ImageId != nil {
        structMap["image_id"] = i.ImageId
    }
    if i.Metadata != nil {
        structMap["metadata"] = i.Metadata
    }
    if i.Price != nil {
        structMap["price"] = i.Price
    }
    if i.SearchId != nil {
        structMap["search_id"] = i.SearchId
    }
    if i.ShowModal != nil {
        structMap["show_modal"] = i.ShowModal
    }
    if i.Size != nil {
        structMap["size"] = i.Size
    }
    if i.SubscriptionId != nil {
        structMap["subscription_id"] = i.SubscriptionId
    }
    if i.VerificationCode != nil {
        structMap["verification_code"] = i.VerificationCode
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Image1.
// It customizes the JSON unmarshaling process for Image1 objects.
func (i *Image1) UnmarshalJSON(input []byte) error {
    var temp tempImage1
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "auth_cookie", "custom_dimensions", "editorial_acknowledgement", "format", "image_id", "metadata", "price", "search_id", "show_modal", "size", "subscription_id", "verification_code")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.AuthCookie = temp.AuthCookie
    i.CustomDimensions = temp.CustomDimensions
    i.EditorialAcknowledgement = temp.EditorialAcknowledgement
    i.Format = temp.Format
    i.ImageId = temp.ImageId
    i.Metadata = temp.Metadata
    i.Price = temp.Price
    i.SearchId = temp.SearchId
    i.ShowModal = temp.ShowModal
    i.Size = temp.Size
    i.SubscriptionId = temp.SubscriptionId
    i.VerificationCode = temp.VerificationCode
    return nil
}

// tempImage1 is a temporary struct used for validating the fields of Image1.
type tempImage1  struct {
    AuthCookie               *Cookie               `json:"auth_cookie,omitempty"`
    CustomDimensions         *CustomSizeDimensions `json:"custom_dimensions,omitempty"`
    EditorialAcknowledgement *bool                 `json:"editorial_acknowledgement,omitempty"`
    Format                   *FormatEnum           `json:"format,omitempty"`
    ImageId                  *string               `json:"image_id,omitempty"`
    Metadata                 *interface{}          `json:"metadata,omitempty"`
    Price                    *float64              `json:"price,omitempty"`
    SearchId                 *string               `json:"search_id,omitempty"`
    ShowModal                *bool                 `json:"show_modal,omitempty"`
    Size                     *Size2Enum            `json:"size,omitempty"`
    SubscriptionId           *string               `json:"subscription_id,omitempty"`
    VerificationCode         *string               `json:"verification_code,omitempty"`
}
