// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// Instrument represents a Instrument struct.
// Information about an musical instrument
type Instrument struct {
    // The id of the instrument
    Id                   *string                `json:"id,omitempty"`
    // Name of the instrument
    Name                 *string                `json:"name,omitempty"`
    // Preview of the instrument
    Previews             []Preview              `json:"previews,omitempty"`
    // List of tags
    Tags                 []string               `json:"tags,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Instrument,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i Instrument) String() string {
    return fmt.Sprintf(
    	"Instrument[Id=%v, Name=%v, Previews=%v, Tags=%v, AdditionalProperties=%v]",
    	i.Id, i.Name, i.Previews, i.Tags, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Instrument.
// It customizes the JSON marshaling process for Instrument objects.
func (i Instrument) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "id", "name", "previews", "tags"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the Instrument object to a map representation for JSON marshaling.
func (i Instrument) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.Id != nil {
        structMap["id"] = i.Id
    }
    if i.Name != nil {
        structMap["name"] = i.Name
    }
    if i.Previews != nil {
        structMap["previews"] = i.Previews
    }
    if i.Tags != nil {
        structMap["tags"] = i.Tags
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Instrument.
// It customizes the JSON unmarshaling process for Instrument objects.
func (i *Instrument) UnmarshalJSON(input []byte) error {
    var temp tempInstrument
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "id", "name", "previews", "tags")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.Id = temp.Id
    i.Name = temp.Name
    i.Previews = temp.Previews
    i.Tags = temp.Tags
    return nil
}

// tempInstrument is a temporary struct used for validating the fields of Instrument.
type tempInstrument  struct {
    Id       *string   `json:"id,omitempty"`
    Name     *string   `json:"name,omitempty"`
    Previews []Preview `json:"previews,omitempty"`
    Tags     []string  `json:"tags,omitempty"`
}
