// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// InstrumentList represents a InstrumentList struct.
// List of instruments
type InstrumentList struct {
    // List of instruments
    Data []string `json:"data"`
}

// String implements the fmt.Stringer interface for InstrumentList,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i InstrumentList) String() string {
    return fmt.Sprintf(
    	"InstrumentList[Data=%v]",
    	i.Data)
}

// MarshalJSON implements the json.Marshaler interface for InstrumentList.
// It customizes the JSON marshaling process for InstrumentList objects.
func (i InstrumentList) MarshalJSON() (
    []byte,
    error) {
    return json.Marshal(i.toMap())
}

// toMap converts the InstrumentList object to a map representation for JSON marshaling.
func (i InstrumentList) toMap() map[string]any {
    structMap := make(map[string]any)
    structMap["data"] = i.Data
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for InstrumentList.
// It customizes the JSON unmarshaling process for InstrumentList objects.
func (i *InstrumentList) UnmarshalJSON(input []byte) error {
    var temp tempInstrumentList
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    
    i.Data = *temp.Data
    return nil
}

// tempInstrumentList is a temporary struct used for validating the fields of InstrumentList.
type tempInstrumentList  struct {
    Data *[]string `json:"data"`
}

func (i *tempInstrumentList) validate() error {
    var errs []string
    if i.Data == nil {
        errs = append(errs, "required field `data` is missing for type `InstrumentList`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
