// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// Instruments represents a Instruments struct.
// Instruments
type Instruments struct {
    // The string id of the instrument
    Id                   *string                `json:"id,omitempty"`
    // The string name of the instrument
    Name                 *string                `json:"name,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Instruments,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (i Instruments) String() string {
    return fmt.Sprintf(
    	"Instruments[Id=%v, Name=%v, AdditionalProperties=%v]",
    	i.Id, i.Name, i.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Instruments.
// It customizes the JSON marshaling process for Instruments objects.
func (i Instruments) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(i.AdditionalProperties,
        "id", "name"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(i.toMap())
}

// toMap converts the Instruments object to a map representation for JSON marshaling.
func (i Instruments) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, i.AdditionalProperties)
    if i.Id != nil {
        structMap["id"] = i.Id
    }
    if i.Name != nil {
        structMap["name"] = i.Name
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Instruments.
// It customizes the JSON unmarshaling process for Instruments objects.
func (i *Instruments) UnmarshalJSON(input []byte) error {
    var temp tempInstruments
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "id", "name")
    if err != nil {
    	return err
    }
    i.AdditionalProperties = additionalProperties
    
    i.Id = temp.Id
    i.Name = temp.Name
    return nil
}

// tempInstruments is a temporary struct used for validating the fields of Instruments.
type tempInstruments  struct {
    Id   *string `json:"id,omitempty"`
    Name *string `json:"name,omitempty"`
}
