// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// Key represents a Key struct.
// The key signature active at the beginning of the region
type Key struct {
    // A text representation of the accidental; if this field is specified, the tonic_note field should also be specified
    TonicAccidental      *TonicAccidentalEnum   `json:"tonic_accidental,omitempty"`
    // A text representation of the musical note; if this field is specified, the tonic_accidental field should also be specified
    TonicNote            *TonicNoteEnum         `json:"tonic_note,omitempty"`
    // The scale quality; if this field is not specified, the API selects the quality automatically
    TonicQuality         *TonicQualityEnum      `json:"tonic_quality,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Key,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (k Key) String() string {
    return fmt.Sprintf(
    	"Key[TonicAccidental=%v, TonicNote=%v, TonicQuality=%v, AdditionalProperties=%v]",
    	k.TonicAccidental, k.TonicNote, k.TonicQuality, k.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Key.
// It customizes the JSON marshaling process for Key objects.
func (k Key) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(k.AdditionalProperties,
        "tonic_accidental", "tonic_note", "tonic_quality"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(k.toMap())
}

// toMap converts the Key object to a map representation for JSON marshaling.
func (k Key) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, k.AdditionalProperties)
    if k.TonicAccidental != nil {
        structMap["tonic_accidental"] = k.TonicAccidental
    }
    if k.TonicNote != nil {
        structMap["tonic_note"] = k.TonicNote
    }
    if k.TonicQuality != nil {
        structMap["tonic_quality"] = k.TonicQuality
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Key.
// It customizes the JSON unmarshaling process for Key objects.
func (k *Key) UnmarshalJSON(input []byte) error {
    var temp tempKey
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "tonic_accidental", "tonic_note", "tonic_quality")
    if err != nil {
    	return err
    }
    k.AdditionalProperties = additionalProperties
    
    k.TonicAccidental = temp.TonicAccidental
    k.TonicNote = temp.TonicNote
    k.TonicQuality = temp.TonicQuality
    return nil
}

// tempKey is a temporary struct used for validating the fields of Key.
type tempKey  struct {
    TonicAccidental *TonicAccidentalEnum `json:"tonic_accidental,omitempty"`
    TonicNote       *TonicNoteEnum       `json:"tonic_note,omitempty"`
    TonicQuality    *TonicQualityEnum    `json:"tonic_quality,omitempty"`
}
