// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// LicenseImageVector represents a LicenseImageVector struct.
// Data required to license an image
type LicenseImageVector struct {
    // Cookie object
    AuthCookie               *Cookie                `json:"auth_cookie,omitempty"`
    // Set to true to acknowledge the editorial agreement
    EditorialAcknowledgement *bool                  `json:"editorial_acknowledgement,omitempty"`
    // (Deprecated) Image format to download
    Format                   *Format1Enum           `json:"format,omitempty"`
    // Image ID
    ImageId                  string                 `json:"image_id"`
    // Additional information for license requests for enterprise accounts and API subscriptions, 4 fields maximum; which fields are required is set by the account holder
    Metadata                 *interface{}           `json:"metadata,omitempty"`
    // For revenue-sharing transactions, the final cost to the end customer as a floating-point number in the transaction currency, such as 12.34
    Price                    *float64               `json:"price,omitempty"`
    // ID of the search that led to this licensing transaction
    SearchId                 *string                `json:"search_id,omitempty"`
    // (Deprecated)
    ShowModal                *bool                  `json:"show_modal,omitempty"`                // Deprecated
    // Image size to download
    Size                     *Size3Enum             `json:"size,omitempty"`
    // ID of the subscription to use for the download.
    SubscriptionId           *string                `json:"subscription_id,omitempty"`
    // (Deprecated)
    VerificationCode         *string                `json:"verification_code,omitempty"`         // Deprecated
    AdditionalProperties     map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for LicenseImageVector,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (l LicenseImageVector) String() string {
    return fmt.Sprintf(
    	"LicenseImageVector[AuthCookie=%v, EditorialAcknowledgement=%v, Format=%v, ImageId=%v, Metadata=%v, Price=%v, SearchId=%v, ShowModal=%v, Size=%v, SubscriptionId=%v, VerificationCode=%v, AdditionalProperties=%v]",
    	l.AuthCookie, l.EditorialAcknowledgement, l.Format, l.ImageId, l.Metadata, l.Price, l.SearchId, l.ShowModal, l.Size, l.SubscriptionId, l.VerificationCode, l.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for LicenseImageVector.
// It customizes the JSON marshaling process for LicenseImageVector objects.
func (l LicenseImageVector) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(l.AdditionalProperties,
        "auth_cookie", "editorial_acknowledgement", "format", "image_id", "metadata", "price", "search_id", "show_modal", "size", "subscription_id", "verification_code"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(l.toMap())
}

// toMap converts the LicenseImageVector object to a map representation for JSON marshaling.
func (l LicenseImageVector) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, l.AdditionalProperties)
    if l.AuthCookie != nil {
        structMap["auth_cookie"] = l.AuthCookie.toMap()
    }
    if l.EditorialAcknowledgement != nil {
        structMap["editorial_acknowledgement"] = l.EditorialAcknowledgement
    }
    if l.Format != nil {
        structMap["format"] = l.Format
    }
    structMap["image_id"] = l.ImageId
    if l.Metadata != nil {
        structMap["metadata"] = l.Metadata
    }
    if l.Price != nil {
        structMap["price"] = l.Price
    }
    if l.SearchId != nil {
        structMap["search_id"] = l.SearchId
    }
    if l.ShowModal != nil {
        structMap["show_modal"] = l.ShowModal
    }
    if l.Size != nil {
        structMap["size"] = l.Size
    }
    if l.SubscriptionId != nil {
        structMap["subscription_id"] = l.SubscriptionId
    }
    if l.VerificationCode != nil {
        structMap["verification_code"] = l.VerificationCode
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for LicenseImageVector.
// It customizes the JSON unmarshaling process for LicenseImageVector objects.
func (l *LicenseImageVector) UnmarshalJSON(input []byte) error {
    var temp tempLicenseImageVector
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "auth_cookie", "editorial_acknowledgement", "format", "image_id", "metadata", "price", "search_id", "show_modal", "size", "subscription_id", "verification_code")
    if err != nil {
    	return err
    }
    l.AdditionalProperties = additionalProperties
    
    l.AuthCookie = temp.AuthCookie
    l.EditorialAcknowledgement = temp.EditorialAcknowledgement
    l.Format = temp.Format
    l.ImageId = *temp.ImageId
    l.Metadata = temp.Metadata
    l.Price = temp.Price
    l.SearchId = temp.SearchId
    l.ShowModal = temp.ShowModal
    l.Size = temp.Size
    l.SubscriptionId = temp.SubscriptionId
    l.VerificationCode = temp.VerificationCode
    return nil
}

// tempLicenseImageVector is a temporary struct used for validating the fields of LicenseImageVector.
type tempLicenseImageVector  struct {
    AuthCookie               *Cookie      `json:"auth_cookie,omitempty"`
    EditorialAcknowledgement *bool        `json:"editorial_acknowledgement,omitempty"`
    Format                   *Format1Enum `json:"format,omitempty"`
    ImageId                  *string      `json:"image_id"`
    Metadata                 *interface{} `json:"metadata,omitempty"`
    Price                    *float64     `json:"price,omitempty"`
    SearchId                 *string      `json:"search_id,omitempty"`
    ShowModal                *bool        `json:"show_modal,omitempty"`
    Size                     *Size3Enum   `json:"size,omitempty"`
    SubscriptionId           *string      `json:"subscription_id,omitempty"`
    VerificationCode         *string      `json:"verification_code,omitempty"`
}

func (l *tempLicenseImageVector) validate() error {
    var errs []string
    if l.ImageId == nil {
        errs = append(errs, "required field `image_id` is missing for type `LicenseImageVector`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
