// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// LicenseAudioRequest represents a LicenseAudioRequest struct.
// Audio license request data
type LicenseAudioRequest struct {
    // List of audio tracks to license
    Audio                []LicenseAudio         `json:"audio"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for LicenseAudioRequest,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (l LicenseAudioRequest) String() string {
    return fmt.Sprintf(
    	"LicenseAudioRequest[Audio=%v, AdditionalProperties=%v]",
    	l.Audio, l.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for LicenseAudioRequest.
// It customizes the JSON marshaling process for LicenseAudioRequest objects.
func (l LicenseAudioRequest) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(l.AdditionalProperties,
        "audio"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(l.toMap())
}

// toMap converts the LicenseAudioRequest object to a map representation for JSON marshaling.
func (l LicenseAudioRequest) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, l.AdditionalProperties)
    structMap["audio"] = l.Audio
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for LicenseAudioRequest.
// It customizes the JSON unmarshaling process for LicenseAudioRequest objects.
func (l *LicenseAudioRequest) UnmarshalJSON(input []byte) error {
    var temp tempLicenseAudioRequest
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "audio")
    if err != nil {
    	return err
    }
    l.AdditionalProperties = additionalProperties
    
    l.Audio = *temp.Audio
    return nil
}

// tempLicenseAudioRequest is a temporary struct used for validating the fields of LicenseAudioRequest.
type tempLicenseAudioRequest  struct {
    Audio *[]LicenseAudio `json:"audio"`
}

func (l *tempLicenseAudioRequest) validate() error {
    var errs []string
    if l.Audio == nil {
        errs = append(errs, "required field `audio` is missing for type `LicenseAudioRequest`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
