// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// LicenseAudio represents a LicenseAudio struct.
// An audio track in a licensing request
type LicenseAudio struct {
    // ID of the track being licensed
    AudioId              string                 `json:"audio_id"`
    // Type of license
    License              *License1Enum          `json:"license,omitempty"`
    // ID of the search that led to this licensing event
    SearchId             *string                `json:"search_id,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for LicenseAudio,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (l LicenseAudio) String() string {
    return fmt.Sprintf(
    	"LicenseAudio[AudioId=%v, License=%v, SearchId=%v, AdditionalProperties=%v]",
    	l.AudioId, l.License, l.SearchId, l.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for LicenseAudio.
// It customizes the JSON marshaling process for LicenseAudio objects.
func (l LicenseAudio) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(l.AdditionalProperties,
        "audio_id", "license", "search_id"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(l.toMap())
}

// toMap converts the LicenseAudio object to a map representation for JSON marshaling.
func (l LicenseAudio) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, l.AdditionalProperties)
    structMap["audio_id"] = l.AudioId
    if l.License != nil {
        structMap["license"] = l.License
    }
    if l.SearchId != nil {
        structMap["search_id"] = l.SearchId
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for LicenseAudio.
// It customizes the JSON unmarshaling process for LicenseAudio objects.
func (l *LicenseAudio) UnmarshalJSON(input []byte) error {
    var temp tempLicenseAudio
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "audio_id", "license", "search_id")
    if err != nil {
    	return err
    }
    l.AdditionalProperties = additionalProperties
    
    l.AudioId = *temp.AudioId
    l.License = temp.License
    l.SearchId = temp.SearchId
    return nil
}

// tempLicenseAudio is a temporary struct used for validating the fields of LicenseAudio.
type tempLicenseAudio  struct {
    AudioId  *string       `json:"audio_id"`
    License  *License1Enum `json:"license,omitempty"`
    SearchId *string       `json:"search_id,omitempty"`
}

func (l *tempLicenseAudio) validate() error {
    var errs []string
    if l.AudioId == nil {
        errs = append(errs, "required field `audio_id` is missing for type `LicenseAudio`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
