// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// LicenseImageRequest represents a LicenseImageRequest struct.
// Image license request data
type LicenseImageRequest struct {
    // Images to create licenses for
    Images               []LicenseImageRequestImages `json:"images"`
    AdditionalProperties map[string]interface{}      `json:"_"`
}

// String implements the fmt.Stringer interface for LicenseImageRequest,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (l LicenseImageRequest) String() string {
    return fmt.Sprintf(
    	"LicenseImageRequest[Images=%v, AdditionalProperties=%v]",
    	l.Images, l.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for LicenseImageRequest.
// It customizes the JSON marshaling process for LicenseImageRequest objects.
func (l LicenseImageRequest) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(l.AdditionalProperties,
        "images"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(l.toMap())
}

// toMap converts the LicenseImageRequest object to a map representation for JSON marshaling.
func (l LicenseImageRequest) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, l.AdditionalProperties)
    structMap["images"] = l.Images
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for LicenseImageRequest.
// It customizes the JSON unmarshaling process for LicenseImageRequest objects.
func (l *LicenseImageRequest) UnmarshalJSON(input []byte) error {
    var temp tempLicenseImageRequest
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "images")
    if err != nil {
    	return err
    }
    l.AdditionalProperties = additionalProperties
    
    l.Images = *temp.Images
    return nil
}

// tempLicenseImageRequest is a temporary struct used for validating the fields of LicenseImageRequest.
type tempLicenseImageRequest  struct {
    Images *[]LicenseImageRequestImages `json:"images"`
}

func (l *tempLicenseImageRequest) validate() error {
    var errs []string
    if l.Images == nil {
        errs = append(errs, "required field `images` is missing for type `LicenseImageRequest`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
