// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// LicenseEditorialContent represents a LicenseEditorialContent struct.
// Individual editorial content to license
type LicenseEditorialContent struct {
    // Editorial ID
    EditorialId          string                 `json:"editorial_id"`
    // License agreement to use for licensing
    License              string                 `json:"license"`
    // Additional information for license requests for enterprise accounts and API subscriptions, 4 fields maximum; which fields are required is set by the account holder
    Metadata             *interface{}           `json:"metadata,omitempty"`
    // Asset size to download
    Size                 *SizeEnum              `json:"size,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for LicenseEditorialContent,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (l LicenseEditorialContent) String() string {
    return fmt.Sprintf(
    	"LicenseEditorialContent[EditorialId=%v, License=%v, Metadata=%v, Size=%v, AdditionalProperties=%v]",
    	l.EditorialId, l.License, l.Metadata, l.Size, l.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for LicenseEditorialContent.
// It customizes the JSON marshaling process for LicenseEditorialContent objects.
func (l LicenseEditorialContent) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(l.AdditionalProperties,
        "editorial_id", "license", "metadata", "size"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(l.toMap())
}

// toMap converts the LicenseEditorialContent object to a map representation for JSON marshaling.
func (l LicenseEditorialContent) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, l.AdditionalProperties)
    structMap["editorial_id"] = l.EditorialId
    structMap["license"] = l.License
    if l.Metadata != nil {
        structMap["metadata"] = l.Metadata
    }
    if l.Size != nil {
        structMap["size"] = l.Size
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for LicenseEditorialContent.
// It customizes the JSON unmarshaling process for LicenseEditorialContent objects.
func (l *LicenseEditorialContent) UnmarshalJSON(input []byte) error {
    var temp tempLicenseEditorialContent
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "editorial_id", "license", "metadata", "size")
    if err != nil {
    	return err
    }
    l.AdditionalProperties = additionalProperties
    
    l.EditorialId = *temp.EditorialId
    l.License = *temp.License
    l.Metadata = temp.Metadata
    l.Size = temp.Size
    return nil
}

// tempLicenseEditorialContent is a temporary struct used for validating the fields of LicenseEditorialContent.
type tempLicenseEditorialContent  struct {
    EditorialId *string      `json:"editorial_id"`
    License     *string      `json:"license"`
    Metadata    *interface{} `json:"metadata,omitempty"`
    Size        *SizeEnum    `json:"size,omitempty"`
}

func (l *tempLicenseEditorialContent) validate() error {
    var errs []string
    if l.EditorialId == nil {
        errs = append(errs, "required field `editorial_id` is missing for type `LicenseEditorialContent`")
    }
    if l.License == nil {
        errs = append(errs, "required field `license` is missing for type `LicenseEditorialContent`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
