// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// LicenseEditorialContentRequest represents a LicenseEditorialContentRequest struct.
// License editorial content request
type LicenseEditorialContentRequest struct {
    // A valid ISO 3166-1 Alpha-2 or ISO 3166-1 Alpha-3 code.
    Country              ISOCountryCode            `json:"country"`
    // Editorial content to license
    Editorial            []LicenseEditorialContent `json:"editorial"`
    AdditionalProperties map[string]interface{}    `json:"_"`
}

// String implements the fmt.Stringer interface for LicenseEditorialContentRequest,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (l LicenseEditorialContentRequest) String() string {
    return fmt.Sprintf(
    	"LicenseEditorialContentRequest[Country=%v, Editorial=%v, AdditionalProperties=%v]",
    	l.Country, l.Editorial, l.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for LicenseEditorialContentRequest.
// It customizes the JSON marshaling process for LicenseEditorialContentRequest objects.
func (l LicenseEditorialContentRequest) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(l.AdditionalProperties,
        "country", "editorial"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(l.toMap())
}

// toMap converts the LicenseEditorialContentRequest object to a map representation for JSON marshaling.
func (l LicenseEditorialContentRequest) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, l.AdditionalProperties)
    structMap["country"] = l.Country.toMap()
    structMap["editorial"] = l.Editorial
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for LicenseEditorialContentRequest.
// It customizes the JSON unmarshaling process for LicenseEditorialContentRequest objects.
func (l *LicenseEditorialContentRequest) UnmarshalJSON(input []byte) error {
    var temp tempLicenseEditorialContentRequest
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "country", "editorial")
    if err != nil {
    	return err
    }
    l.AdditionalProperties = additionalProperties
    
    l.Country = *temp.Country
    l.Editorial = *temp.Editorial
    return nil
}

// tempLicenseEditorialContentRequest is a temporary struct used for validating the fields of LicenseEditorialContentRequest.
type tempLicenseEditorialContentRequest  struct {
    Country   *ISOCountryCode            `json:"country"`
    Editorial *[]LicenseEditorialContent `json:"editorial"`
}

func (l *tempLicenseEditorialContentRequest) validate() error {
    var errs []string
    if l.Country == nil {
        errs = append(errs, "required field `country` is missing for type `LicenseEditorialContentRequest`")
    }
    if l.Editorial == nil {
        errs = append(errs, "required field `editorial` is missing for type `LicenseEditorialContentRequest`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
