// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// LicenseFormat represents a LicenseFormat struct.
// Description of a license
type LicenseFormat struct {
    // Description of the license
    Description          *string                `json:"description,omitempty"`
    // Format or extension of the media, such as mpeg for videos or jpeg for images
    Format               *string                `json:"format,omitempty"`
    // Media type of the license
    MediaType            *MediaTypeEnum         `json:"media_type,omitempty"`
    // Width of the media, in pixels, allowed by this license
    MinResolution        *int                   `json:"min_resolution,omitempty"`
    // Keyword that details the size of the media, such as hd or sd for video, huge or vector for images
    Size                 *string                `json:"size,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for LicenseFormat,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (l LicenseFormat) String() string {
    return fmt.Sprintf(
    	"LicenseFormat[Description=%v, Format=%v, MediaType=%v, MinResolution=%v, Size=%v, AdditionalProperties=%v]",
    	l.Description, l.Format, l.MediaType, l.MinResolution, l.Size, l.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for LicenseFormat.
// It customizes the JSON marshaling process for LicenseFormat objects.
func (l LicenseFormat) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(l.AdditionalProperties,
        "description", "format", "media_type", "min_resolution", "size"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(l.toMap())
}

// toMap converts the LicenseFormat object to a map representation for JSON marshaling.
func (l LicenseFormat) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, l.AdditionalProperties)
    if l.Description != nil {
        structMap["description"] = l.Description
    }
    if l.Format != nil {
        structMap["format"] = l.Format
    }
    if l.MediaType != nil {
        structMap["media_type"] = l.MediaType
    }
    if l.MinResolution != nil {
        structMap["min_resolution"] = l.MinResolution
    }
    if l.Size != nil {
        structMap["size"] = l.Size
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for LicenseFormat.
// It customizes the JSON unmarshaling process for LicenseFormat objects.
func (l *LicenseFormat) UnmarshalJSON(input []byte) error {
    var temp tempLicenseFormat
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "description", "format", "media_type", "min_resolution", "size")
    if err != nil {
    	return err
    }
    l.AdditionalProperties = additionalProperties
    
    l.Description = temp.Description
    l.Format = temp.Format
    l.MediaType = temp.MediaType
    l.MinResolution = temp.MinResolution
    l.Size = temp.Size
    return nil
}

// tempLicenseFormat is a temporary struct used for validating the fields of LicenseFormat.
type tempLicenseFormat  struct {
    Description   *string        `json:"description,omitempty"`
    Format        *string        `json:"format,omitempty"`
    MediaType     *MediaTypeEnum `json:"media_type,omitempty"`
    MinResolution *int           `json:"min_resolution,omitempty"`
    Size          *string        `json:"size,omitempty"`
}
