// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// LicenseEditorialVideoContent represents a LicenseEditorialVideoContent struct.
// Individual editorial video content to license
type LicenseEditorialVideoContent struct {
    // Editorial ID
    EditorialId          string                 `json:"editorial_id"`
    // License agreement to use for licensing
    License              License2Enum           `json:"license"`
    // Additional information for license requests for enterprise accounts and API subscriptions, 4 fields maximum; which fields are required is set by the account holder
    Metadata             *interface{}           `json:"metadata,omitempty"`
    // Asset size to download
    Size                 *Size1Enum             `json:"size,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for LicenseEditorialVideoContent,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (l LicenseEditorialVideoContent) String() string {
    return fmt.Sprintf(
    	"LicenseEditorialVideoContent[EditorialId=%v, License=%v, Metadata=%v, Size=%v, AdditionalProperties=%v]",
    	l.EditorialId, l.License, l.Metadata, l.Size, l.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for LicenseEditorialVideoContent.
// It customizes the JSON marshaling process for LicenseEditorialVideoContent objects.
func (l LicenseEditorialVideoContent) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(l.AdditionalProperties,
        "editorial_id", "license", "metadata", "size"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(l.toMap())
}

// toMap converts the LicenseEditorialVideoContent object to a map representation for JSON marshaling.
func (l LicenseEditorialVideoContent) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, l.AdditionalProperties)
    structMap["editorial_id"] = l.EditorialId
    structMap["license"] = l.License
    if l.Metadata != nil {
        structMap["metadata"] = l.Metadata
    }
    if l.Size != nil {
        structMap["size"] = l.Size
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for LicenseEditorialVideoContent.
// It customizes the JSON unmarshaling process for LicenseEditorialVideoContent objects.
func (l *LicenseEditorialVideoContent) UnmarshalJSON(input []byte) error {
    var temp tempLicenseEditorialVideoContent
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "editorial_id", "license", "metadata", "size")
    if err != nil {
    	return err
    }
    l.AdditionalProperties = additionalProperties
    
    l.EditorialId = *temp.EditorialId
    l.License = *temp.License
    l.Metadata = temp.Metadata
    l.Size = temp.Size
    return nil
}

// tempLicenseEditorialVideoContent is a temporary struct used for validating the fields of LicenseEditorialVideoContent.
type tempLicenseEditorialVideoContent  struct {
    EditorialId *string       `json:"editorial_id"`
    License     *License2Enum `json:"license"`
    Metadata    *interface{}  `json:"metadata,omitempty"`
    Size        *Size1Enum    `json:"size,omitempty"`
}

func (l *tempLicenseEditorialVideoContent) validate() error {
    var errs []string
    if l.EditorialId == nil {
        errs = append(errs, "required field `editorial_id` is missing for type `LicenseEditorialVideoContent`")
    }
    if l.License == nil {
        errs = append(errs, "required field `license` is missing for type `LicenseEditorialVideoContent`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
