// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// Loops represents a Loops struct.
type Loops struct {
    Url                  *string                `json:"url,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Loops,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (l Loops) String() string {
    return fmt.Sprintf(
    	"Loops[Url=%v, AdditionalProperties=%v]",
    	l.Url, l.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Loops.
// It customizes the JSON marshaling process for Loops objects.
func (l Loops) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(l.AdditionalProperties,
        "url"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(l.toMap())
}

// toMap converts the Loops object to a map representation for JSON marshaling.
func (l Loops) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, l.AdditionalProperties)
    if l.Url != nil {
        structMap["url"] = l.Url
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Loops.
// It customizes the JSON unmarshaling process for Loops objects.
func (l *Loops) UnmarshalJSON(input []byte) error {
    var temp tempLoops
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "url")
    if err != nil {
    	return err
    }
    l.AdditionalProperties = additionalProperties
    
    l.Url = temp.Url
    return nil
}

// tempLoops is a temporary struct used for validating the fields of Loops.
type tempLoops  struct {
    Url *string `json:"url,omitempty"`
}
