// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// OauthAccessTokenResponse represents a OauthAccessTokenResponse struct.
// Access token response to client apps
type OauthAccessTokenResponse struct {
    // Access token that can be used for future requests
    AccessToken          string                 `json:"access_token"`
    // Number of seconds before token expires, only present for expiring tokens
    ExpiresIn            *int                   `json:"expires_in,omitempty"`
    // A refresh token that can be used to renew the access_token when it expires, only present for expiring tokens
    RefreshToken         *string                `json:"refresh_token,omitempty"`
    // Type of token
    TokenType            string                 `json:"token_type"`
    // Metadata about the access_token, only present for expiring tokens
    UserToken            *string                `json:"user_token,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for OauthAccessTokenResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (o OauthAccessTokenResponse) String() string {
    return fmt.Sprintf(
    	"OauthAccessTokenResponse[AccessToken=%v, ExpiresIn=%v, RefreshToken=%v, TokenType=%v, UserToken=%v, AdditionalProperties=%v]",
    	o.AccessToken, o.ExpiresIn, o.RefreshToken, o.TokenType, o.UserToken, o.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for OauthAccessTokenResponse.
// It customizes the JSON marshaling process for OauthAccessTokenResponse objects.
func (o OauthAccessTokenResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(o.AdditionalProperties,
        "access_token", "expires_in", "refresh_token", "token_type", "user_token"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(o.toMap())
}

// toMap converts the OauthAccessTokenResponse object to a map representation for JSON marshaling.
func (o OauthAccessTokenResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, o.AdditionalProperties)
    structMap["access_token"] = o.AccessToken
    if o.ExpiresIn != nil {
        structMap["expires_in"] = o.ExpiresIn
    }
    if o.RefreshToken != nil {
        structMap["refresh_token"] = o.RefreshToken
    }
    structMap["token_type"] = o.TokenType
    if o.UserToken != nil {
        structMap["user_token"] = o.UserToken
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for OauthAccessTokenResponse.
// It customizes the JSON unmarshaling process for OauthAccessTokenResponse objects.
func (o *OauthAccessTokenResponse) UnmarshalJSON(input []byte) error {
    var temp tempOauthAccessTokenResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "access_token", "expires_in", "refresh_token", "token_type", "user_token")
    if err != nil {
    	return err
    }
    o.AdditionalProperties = additionalProperties
    
    o.AccessToken = *temp.AccessToken
    o.ExpiresIn = temp.ExpiresIn
    o.RefreshToken = temp.RefreshToken
    o.TokenType = *temp.TokenType
    o.UserToken = temp.UserToken
    return nil
}

// tempOauthAccessTokenResponse is a temporary struct used for validating the fields of OauthAccessTokenResponse.
type tempOauthAccessTokenResponse  struct {
    AccessToken  *string `json:"access_token"`
    ExpiresIn    *int    `json:"expires_in,omitempty"`
    RefreshToken *string `json:"refresh_token,omitempty"`
    TokenType    *string `json:"token_type"`
    UserToken    *string `json:"user_token,omitempty"`
}

func (o *tempOauthAccessTokenResponse) validate() error {
    var errs []string
    if o.AccessToken == nil {
        errs = append(errs, "required field `access_token` is missing for type `OauthAccessTokenResponse`")
    }
    if o.TokenType == nil {
        errs = append(errs, "required field `token_type` is missing for type `OauthAccessTokenResponse`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
