// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// RedownloadVideo represents a RedownloadVideo struct.
// Data required to redownload a video
type RedownloadVideo struct {
    // Cookie object
    AuthCookie           *Cookie                `json:"auth_cookie,omitempty"`
    // (Deprecated)
    ShowModal            *bool                  `json:"show_modal,omitempty"`        // Deprecated
    // Size of the video
    Size                 *Size7Enum             `json:"size,omitempty"`
    // (Deprecated)
    VerificationCode     *string                `json:"verification_code,omitempty"` // Deprecated
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for RedownloadVideo,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (r RedownloadVideo) String() string {
    return fmt.Sprintf(
    	"RedownloadVideo[AuthCookie=%v, ShowModal=%v, Size=%v, VerificationCode=%v, AdditionalProperties=%v]",
    	r.AuthCookie, r.ShowModal, r.Size, r.VerificationCode, r.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for RedownloadVideo.
// It customizes the JSON marshaling process for RedownloadVideo objects.
func (r RedownloadVideo) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(r.AdditionalProperties,
        "auth_cookie", "show_modal", "size", "verification_code"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(r.toMap())
}

// toMap converts the RedownloadVideo object to a map representation for JSON marshaling.
func (r RedownloadVideo) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, r.AdditionalProperties)
    if r.AuthCookie != nil {
        structMap["auth_cookie"] = r.AuthCookie.toMap()
    }
    if r.ShowModal != nil {
        structMap["show_modal"] = r.ShowModal
    }
    if r.Size != nil {
        structMap["size"] = r.Size
    }
    if r.VerificationCode != nil {
        structMap["verification_code"] = r.VerificationCode
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for RedownloadVideo.
// It customizes the JSON unmarshaling process for RedownloadVideo objects.
func (r *RedownloadVideo) UnmarshalJSON(input []byte) error {
    var temp tempRedownloadVideo
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "auth_cookie", "show_modal", "size", "verification_code")
    if err != nil {
    	return err
    }
    r.AdditionalProperties = additionalProperties
    
    r.AuthCookie = temp.AuthCookie
    r.ShowModal = temp.ShowModal
    r.Size = temp.Size
    r.VerificationCode = temp.VerificationCode
    return nil
}

// tempRedownloadVideo is a temporary struct used for validating the fields of RedownloadVideo.
type tempRedownloadVideo  struct {
    AuthCookie       *Cookie    `json:"auth_cookie,omitempty"`
    ShowModal        *bool      `json:"show_modal,omitempty"`
    Size             *Size7Enum `json:"size,omitempty"`
    VerificationCode *string    `json:"verification_code,omitempty"`
}
