// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// RemoveCatalogCollectionItems represents a RemoveCatalogCollectionItems struct.
type RemoveCatalogCollectionItems struct {
    Items                []RemoveCatalogCollectionItem `json:"items"`
    AdditionalProperties map[string]interface{}        `json:"_"`
}

// String implements the fmt.Stringer interface for RemoveCatalogCollectionItems,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (r RemoveCatalogCollectionItems) String() string {
    return fmt.Sprintf(
    	"RemoveCatalogCollectionItems[Items=%v, AdditionalProperties=%v]",
    	r.Items, r.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for RemoveCatalogCollectionItems.
// It customizes the JSON marshaling process for RemoveCatalogCollectionItems objects.
func (r RemoveCatalogCollectionItems) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(r.AdditionalProperties,
        "items"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(r.toMap())
}

// toMap converts the RemoveCatalogCollectionItems object to a map representation for JSON marshaling.
func (r RemoveCatalogCollectionItems) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, r.AdditionalProperties)
    structMap["items"] = r.Items
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for RemoveCatalogCollectionItems.
// It customizes the JSON unmarshaling process for RemoveCatalogCollectionItems objects.
func (r *RemoveCatalogCollectionItems) UnmarshalJSON(input []byte) error {
    var temp tempRemoveCatalogCollectionItems
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "items")
    if err != nil {
    	return err
    }
    r.AdditionalProperties = additionalProperties
    
    r.Items = *temp.Items
    return nil
}

// tempRemoveCatalogCollectionItems is a temporary struct used for validating the fields of RemoveCatalogCollectionItems.
type tempRemoveCatalogCollectionItems  struct {
    Items *[]RemoveCatalogCollectionItem `json:"items"`
}

func (r *tempRemoveCatalogCollectionItems) validate() error {
    var errs []string
    if r.Items == nil {
        errs = append(errs, "required field `items` is missing for type `RemoveCatalogCollectionItems`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
