// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// Roles represents a Roles struct.
type Roles struct {
    Editors              []CatalogCollectionRole `json:"editors,omitempty"`
    Owners               []CatalogCollectionRole `json:"owners,omitempty"`
    Viewers              []CatalogCollectionRole `json:"viewers,omitempty"`
    AdditionalProperties map[string]interface{}  `json:"_"`
}

// String implements the fmt.Stringer interface for Roles,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (r Roles) String() string {
    return fmt.Sprintf(
    	"Roles[Editors=%v, Owners=%v, Viewers=%v, AdditionalProperties=%v]",
    	r.Editors, r.Owners, r.Viewers, r.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Roles.
// It customizes the JSON marshaling process for Roles objects.
func (r Roles) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(r.AdditionalProperties,
        "editors", "owners", "viewers"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(r.toMap())
}

// toMap converts the Roles object to a map representation for JSON marshaling.
func (r Roles) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, r.AdditionalProperties)
    if r.Editors != nil {
        structMap["editors"] = r.Editors
    }
    if r.Owners != nil {
        structMap["owners"] = r.Owners
    }
    if r.Viewers != nil {
        structMap["viewers"] = r.Viewers
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Roles.
// It customizes the JSON unmarshaling process for Roles objects.
func (r *Roles) UnmarshalJSON(input []byte) error {
    var temp tempRoles
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "editors", "owners", "viewers")
    if err != nil {
    	return err
    }
    r.AdditionalProperties = additionalProperties
    
    r.Editors = temp.Editors
    r.Owners = temp.Owners
    r.Viewers = temp.Viewers
    return nil
}

// tempRoles is a temporary struct used for validating the fields of Roles.
type tempRoles  struct {
    Editors []CatalogCollectionRole `json:"editors,omitempty"`
    Owners  []CatalogCollectionRole `json:"owners,omitempty"`
    Viewers []CatalogCollectionRole `json:"viewers,omitempty"`
}
