// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// SFXAssets represents a SFXAssets struct.
// Files that are available as part of an sound effect asset
type SFXAssets struct {
    // Information about a file that is part of an sound effect asset
    PreviewMp3           *SFXAssetDetails       `json:"preview_mp3,omitempty"`
    // Information about a file that is part of an sound effect asset
    Waveform             *SFXAssetDetails       `json:"waveform,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for SFXAssets,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s SFXAssets) String() string {
    return fmt.Sprintf(
    	"SFXAssets[PreviewMp3=%v, Waveform=%v, AdditionalProperties=%v]",
    	s.PreviewMp3, s.Waveform, s.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for SFXAssets.
// It customizes the JSON marshaling process for SFXAssets objects.
func (s SFXAssets) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(s.AdditionalProperties,
        "preview_mp3", "waveform"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(s.toMap())
}

// toMap converts the SFXAssets object to a map representation for JSON marshaling.
func (s SFXAssets) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, s.AdditionalProperties)
    if s.PreviewMp3 != nil {
        structMap["preview_mp3"] = s.PreviewMp3.toMap()
    }
    if s.Waveform != nil {
        structMap["waveform"] = s.Waveform.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for SFXAssets.
// It customizes the JSON unmarshaling process for SFXAssets objects.
func (s *SFXAssets) UnmarshalJSON(input []byte) error {
    var temp tempSFXAssets
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "preview_mp3", "waveform")
    if err != nil {
    	return err
    }
    s.AdditionalProperties = additionalProperties
    
    s.PreviewMp3 = temp.PreviewMp3
    s.Waveform = temp.Waveform
    return nil
}

// tempSFXAssets is a temporary struct used for validating the fields of SFXAssets.
type tempSFXAssets  struct {
    PreviewMp3 *SFXAssetDetails `json:"preview_mp3,omitempty"`
    Waveform   *SFXAssetDetails `json:"waveform,omitempty"`
}
