// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
)

// SearchImageRegion represents a SearchImageRegion struct.
// This is a container for any-of cases.
type SearchImageRegion struct {
    value    any
    isString bool
}

// String implements the fmt.Stringer interface for SearchImageRegion,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s SearchImageRegion) String() string {
    return fmt.Sprintf("%v", s.value)
}

// MarshalJSON implements the json.Marshaler interface for SearchImageRegion.
// It customizes the JSON marshaling process for SearchImageRegion objects.
func (s SearchImageRegion) MarshalJSON() (
    []byte,
    error) {
    if s.value == nil {
        return nil, errors.New("No underlying type is set. Please use any of the `models.SearchImageRegionContainer.From*` functions to initialize the SearchImageRegion object.")
    }
    return json.Marshal(s.toMap())
}

// toMap converts the SearchImageRegion object to a map representation for JSON marshaling.
func (s *SearchImageRegion) toMap() any {
    switch obj := s.value.(type) {
    case *string:
        return *obj
    }
    return nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for SearchImageRegion.
// It customizes the JSON unmarshaling process for SearchImageRegion objects.
func (s *SearchImageRegion) UnmarshalJSON(input []byte) error {
    result, err := UnmarshallAnyOf(input,
        NewTypeHolder(new(string), false, &s.isString),
    )
    
    s.value = result
    return err
}

func (s *SearchImageRegion) AsString() (
    *string,
    bool) {
    if !s.isString {
        return nil, false
    }
    return s.value.(*string), true
}

// internalSearchImageRegion represents a searchImageRegion struct.
// This is a container for any-of cases.
type internalSearchImageRegion struct {}

var SearchImageRegionContainer internalSearchImageRegion

// The internalSearchImageRegion instance, wrapping the provided string value.
func (s *internalSearchImageRegion) FromString(val string) SearchImageRegion {
    return SearchImageRegion{value: &val}
}
