// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// SearchEntitiesResponse represents a SearchEntitiesResponse struct.
// The response to a request for keyword analysis
type SearchEntitiesResponse struct {
    // The top keywords from the submitted text
    Keywords             []string               `json:"keywords,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for SearchEntitiesResponse,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s SearchEntitiesResponse) String() string {
    return fmt.Sprintf(
    	"SearchEntitiesResponse[Keywords=%v, AdditionalProperties=%v]",
    	s.Keywords, s.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for SearchEntitiesResponse.
// It customizes the JSON marshaling process for SearchEntitiesResponse objects.
func (s SearchEntitiesResponse) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(s.AdditionalProperties,
        "keywords"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(s.toMap())
}

// toMap converts the SearchEntitiesResponse object to a map representation for JSON marshaling.
func (s SearchEntitiesResponse) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, s.AdditionalProperties)
    if s.Keywords != nil {
        structMap["keywords"] = s.Keywords
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for SearchEntitiesResponse.
// It customizes the JSON unmarshaling process for SearchEntitiesResponse objects.
func (s *SearchEntitiesResponse) UnmarshalJSON(input []byte) error {
    var temp tempSearchEntitiesResponse
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "keywords")
    if err != nil {
    	return err
    }
    s.AdditionalProperties = additionalProperties
    
    s.Keywords = temp.Keywords
    return nil
}

// tempSearchEntitiesResponse is a temporary struct used for validating the fields of SearchEntitiesResponse.
type tempSearchEntitiesResponse  struct {
    Keywords []string `json:"keywords,omitempty"`
}
