// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
)

// SearchImageContributorCountry represents a SearchImageContributorCountry struct.
// This is a container for one-of cases.
type SearchImageContributorCountry struct {
    value           any
    isArrayOfString bool
}

// String implements the fmt.Stringer interface for SearchImageContributorCountry,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s SearchImageContributorCountry) String() string {
    return fmt.Sprintf("%v", s.value)
}

// MarshalJSON implements the json.Marshaler interface for SearchImageContributorCountry.
// It customizes the JSON marshaling process for SearchImageContributorCountry objects.
func (s SearchImageContributorCountry) MarshalJSON() (
    []byte,
    error) {
    if s.value == nil {
        return nil, errors.New("No underlying type is set. Please use any of the `models.SearchImageContributorCountryContainer.From*` functions to initialize the SearchImageContributorCountry object.")
    }
    return json.Marshal(s.toMap())
}

// toMap converts the SearchImageContributorCountry object to a map representation for JSON marshaling.
func (s *SearchImageContributorCountry) toMap() any {
    switch obj := s.value.(type) {
    case *[]string:
        return *obj
    }
    return nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for SearchImageContributorCountry.
// It customizes the JSON unmarshaling process for SearchImageContributorCountry objects.
func (s *SearchImageContributorCountry) UnmarshalJSON(input []byte) error {
    result, err := UnmarshallOneOf(input,
        NewTypeHolder(new([]string), false, &s.isArrayOfString),
    )
    
    s.value = result
    return err
}

func (s *SearchImageContributorCountry) AsArrayOfString() (
    *[]string,
    bool) {
    if !s.isArrayOfString {
        return nil, false
    }
    return s.value.(*[]string), true
}

// internalSearchImageContributorCountry represents a searchImageContributorCountry struct.
// This is a container for one-of cases.
type internalSearchImageContributorCountry struct {}

var SearchImageContributorCountryContainer internalSearchImageContributorCountry

// The internalSearchImageContributorCountry instance, wrapping the provided []string value.
func (s *internalSearchImageContributorCountry) FromArrayOfString(val []string) SearchImageContributorCountry {
    return SearchImageContributorCountry{value: &val}
}
