// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
)

// SearchImagesRegion represents a SearchImagesRegion struct.
// This is a container for any-of cases.
type SearchImagesRegion struct {
    value    any
    isString bool
}

// String implements the fmt.Stringer interface for SearchImagesRegion,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s SearchImagesRegion) String() string {
    return fmt.Sprintf("%v", s.value)
}

// MarshalJSON implements the json.Marshaler interface for SearchImagesRegion.
// It customizes the JSON marshaling process for SearchImagesRegion objects.
func (s SearchImagesRegion) MarshalJSON() (
    []byte,
    error) {
    if s.value == nil {
        return nil, errors.New("No underlying type is set. Please use any of the `models.SearchImagesRegionContainer.From*` functions to initialize the SearchImagesRegion object.")
    }
    return json.Marshal(s.toMap())
}

// toMap converts the SearchImagesRegion object to a map representation for JSON marshaling.
func (s *SearchImagesRegion) toMap() any {
    switch obj := s.value.(type) {
    case *string:
        return *obj
    }
    return nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for SearchImagesRegion.
// It customizes the JSON unmarshaling process for SearchImagesRegion objects.
func (s *SearchImagesRegion) UnmarshalJSON(input []byte) error {
    result, err := UnmarshallAnyOf(input,
        NewTypeHolder(new(string), false, &s.isString),
    )
    
    s.value = result
    return err
}

func (s *SearchImagesRegion) AsString() (
    *string,
    bool) {
    if !s.isString {
        return nil, false
    }
    return s.value.(*string), true
}

// internalSearchImagesRegion represents a searchImagesRegion struct.
// This is a container for any-of cases.
type internalSearchImagesRegion struct {}

var SearchImagesRegionContainer internalSearchImagesRegion

// The internalSearchImagesRegion instance, wrapping the provided string value.
func (s *internalSearchImagesRegion) FromString(val string) SearchImagesRegion {
    return SearchImagesRegion{value: &val}
}
