// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
    "log"
    "time"
)

// SearchImage represents a SearchImage struct.
// Data required to search for an image
type SearchImage struct {
    // Show images added on the specified date
    AddedDate            *time.Time                     `json:"added_date,omitempty"`
    // Show images added before the specified date
    AddedDateEnd         *time.Time                     `json:"added_date_end,omitempty"`
    // Show images added on or after the specified date
    AddedDateStart       *time.Time                     `json:"added_date_start,omitempty"`
    // Show images with the specified aspect ratio, using a positive decimal of the width divided by the height, such as 1.7778 for a 16:9 image
    AspectRatio          *float64                       `json:"aspect_ratio,omitempty"`
    // Show images with the specified aspect ratio or lower, using a positive decimal of the width divided by the height, such as 1.7778 for a 16:9 image
    AspectRatioMax       *float64                       `json:"aspect_ratio_max,omitempty"`
    // Show images with the specified aspect ratio or higher, using a positive decimal of the width divided by the height, such as 1.7778 for a 16:9 image
    AspectRatioMin       *float64                       `json:"aspect_ratio_min,omitempty"`
    // Show only authentic images
    Authentic            *bool                          `json:"authentic,omitempty"`
    // Show images with the specified Shutterstock-defined category; specify a category name or ID
    Category             *string                        `json:"category,omitempty"`
    // Specify either a hexadecimal color in the format '4F21EA' or 'grayscale'; the API returns images that use similar colors
    Color                *string                        `json:"color,omitempty"`
    // Show images with the specified contributor names or IDs, allows multiple
    Contributor          []string                       `json:"contributor,omitempty"`
    // Show images from contributors in one or more specified countries, or start with NOT to exclude a country from the search
    ContributorCountry   *SearchImageContributorCountry `json:"contributor_country,omitempty"`
    // Fields to display in the response; see the documentation for the fields parameter in the overview section
    Fields               *string                        `json:"fields,omitempty"`
    // (Deprecated; use height_from and height_to instead) Show images with the specified height
    Height               *int                           `json:"height,omitempty"`
    // Show images with the specified height or larger, in pixels
    HeightFrom           *int                           `json:"height_from,omitempty"`
    // Show images with the specified height or smaller, in pixels
    HeightTo             *int                           `json:"height_to,omitempty"`
    // Show images of the specified type
    ImageType            []ImageTypeEnum                `json:"image_type,omitempty"`
    // Hide results with potentially unsafe keywords
    KeywordSafeSearch    *bool                          `json:"keyword_safe_search,omitempty"`
    // Language code
    Language             *LanguageEnum                  `json:"language,omitempty"`
    // Show only images with the specified license
    License              []LicenseEnum                  `json:"license,omitempty"`
    // Show image results with the specified model IDs
    Model                []string                       `json:"model,omitempty"`
    // Show image results with horizontal or vertical orientation
    Orientation          *OrientationEnum               `json:"orientation,omitempty"`
    // Page number
    Page                 *int                           `json:"page,omitempty"`
    // Show images that feature people of the specified age category
    PeopleAge            *PeopleAgeEnum                 `json:"people_age,omitempty"`
    // Show images with people of the specified ethnicities, or start with NOT to show images without those ethnicities
    PeopleEthnicity      []PeopleEthnicityEnum          `json:"people_ethnicity,omitempty"`
    // Show images with people of the specified gender
    PeopleGender         *PeopleGenderEnum              `json:"people_gender,omitempty"`
    // Show images of people with a signed model release
    PeopleModelReleased  *bool                          `json:"people_model_released,omitempty"`
    // Show images with the specified number of people
    PeopleNumber         *int                           `json:"people_number,omitempty"`
    // Number of results per page
    PerPage              *int                           `json:"per_page,omitempty"`
    // One or more search terms separated by spaces; you can use NOT to filter out images that match a term
    Query                *string                        `json:"query,omitempty"`
    // Raise or lower search result rankings based on the result's relevance to a specified region; you can provide a country code or an IP address from which the API infers a country
    Region               *SearchImageRegion             `json:"region,omitempty"`
    // Enable or disable safe search
    Safe                 *bool                          `json:"safe,omitempty"`
    // Sort by
    Sort                 *SortEnum                      `json:"sort,omitempty"`
    // Spellcheck the search query and return results on suggested spellings
    SpellcheckQuery      *bool                          `json:"spellcheck_query,omitempty"`
    // Amount of detail to render in the response
    View                 *ViewEnum                      `json:"view,omitempty"`
    // (Deprecated; use width_from and width_to instead) Show images with the specified width
    Width                *int                           `json:"width,omitempty"`
    // Show images with the specified width or larger, in pixels
    WidthFrom            *int                           `json:"width_from,omitempty"`
    // Show images with the specified width or smaller, in pixels
    WidthTo              *int                           `json:"width_to,omitempty"`
    AdditionalProperties map[string]interface{}         `json:"_"`
}

// String implements the fmt.Stringer interface for SearchImage,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s SearchImage) String() string {
    return fmt.Sprintf(
    	"SearchImage[AddedDate=%v, AddedDateEnd=%v, AddedDateStart=%v, AspectRatio=%v, AspectRatioMax=%v, AspectRatioMin=%v, Authentic=%v, Category=%v, Color=%v, Contributor=%v, ContributorCountry=%v, Fields=%v, Height=%v, HeightFrom=%v, HeightTo=%v, ImageType=%v, KeywordSafeSearch=%v, Language=%v, License=%v, Model=%v, Orientation=%v, Page=%v, PeopleAge=%v, PeopleEthnicity=%v, PeopleGender=%v, PeopleModelReleased=%v, PeopleNumber=%v, PerPage=%v, Query=%v, Region=%v, Safe=%v, Sort=%v, SpellcheckQuery=%v, View=%v, Width=%v, WidthFrom=%v, WidthTo=%v, AdditionalProperties=%v]",
    	s.AddedDate, s.AddedDateEnd, s.AddedDateStart, s.AspectRatio, s.AspectRatioMax, s.AspectRatioMin, s.Authentic, s.Category, s.Color, s.Contributor, s.ContributorCountry, s.Fields, s.Height, s.HeightFrom, s.HeightTo, s.ImageType, s.KeywordSafeSearch, s.Language, s.License, s.Model, s.Orientation, s.Page, s.PeopleAge, s.PeopleEthnicity, s.PeopleGender, s.PeopleModelReleased, s.PeopleNumber, s.PerPage, s.Query, s.Region, s.Safe, s.Sort, s.SpellcheckQuery, s.View, s.Width, s.WidthFrom, s.WidthTo, s.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for SearchImage.
// It customizes the JSON marshaling process for SearchImage objects.
func (s SearchImage) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(s.AdditionalProperties,
        "added_date", "added_date_end", "added_date_start", "aspect_ratio", "aspect_ratio_max", "aspect_ratio_min", "authentic", "category", "color", "contributor", "contributor_country", "fields", "height", "height_from", "height_to", "image_type", "keyword_safe_search", "language", "license", "model", "orientation", "page", "people_age", "people_ethnicity", "people_gender", "people_model_released", "people_number", "per_page", "query", "region", "safe", "sort", "spellcheck_query", "view", "width", "width_from", "width_to"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(s.toMap())
}

// toMap converts the SearchImage object to a map representation for JSON marshaling.
func (s SearchImage) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, s.AdditionalProperties)
    if s.AddedDate != nil {
        structMap["added_date"] = s.AddedDate.Format(DEFAULT_DATE)
    }
    if s.AddedDateEnd != nil {
        structMap["added_date_end"] = s.AddedDateEnd.Format(DEFAULT_DATE)
    }
    if s.AddedDateStart != nil {
        structMap["added_date_start"] = s.AddedDateStart.Format(DEFAULT_DATE)
    }
    if s.AspectRatio != nil {
        structMap["aspect_ratio"] = s.AspectRatio
    }
    if s.AspectRatioMax != nil {
        structMap["aspect_ratio_max"] = s.AspectRatioMax
    }
    if s.AspectRatioMin != nil {
        structMap["aspect_ratio_min"] = s.AspectRatioMin
    }
    if s.Authentic != nil {
        structMap["authentic"] = s.Authentic
    }
    if s.Category != nil {
        structMap["category"] = s.Category
    }
    if s.Color != nil {
        structMap["color"] = s.Color
    }
    if s.Contributor != nil {
        structMap["contributor"] = s.Contributor
    }
    if s.ContributorCountry != nil {
        structMap["contributor_country"] = s.ContributorCountry.toMap()
    }
    if s.Fields != nil {
        structMap["fields"] = s.Fields
    }
    if s.Height != nil {
        structMap["height"] = s.Height
    }
    if s.HeightFrom != nil {
        structMap["height_from"] = s.HeightFrom
    }
    if s.HeightTo != nil {
        structMap["height_to"] = s.HeightTo
    }
    if s.ImageType != nil {
        structMap["image_type"] = s.ImageType
    }
    if s.KeywordSafeSearch != nil {
        structMap["keyword_safe_search"] = s.KeywordSafeSearch
    }
    if s.Language != nil {
        structMap["language"] = s.Language
    }
    if s.License != nil {
        structMap["license"] = s.License
    }
    if s.Model != nil {
        structMap["model"] = s.Model
    }
    if s.Orientation != nil {
        structMap["orientation"] = s.Orientation
    }
    if s.Page != nil {
        structMap["page"] = s.Page
    }
    if s.PeopleAge != nil {
        structMap["people_age"] = s.PeopleAge
    }
    if s.PeopleEthnicity != nil {
        structMap["people_ethnicity"] = s.PeopleEthnicity
    }
    if s.PeopleGender != nil {
        structMap["people_gender"] = s.PeopleGender
    }
    if s.PeopleModelReleased != nil {
        structMap["people_model_released"] = s.PeopleModelReleased
    }
    if s.PeopleNumber != nil {
        structMap["people_number"] = s.PeopleNumber
    }
    if s.PerPage != nil {
        structMap["per_page"] = s.PerPage
    }
    if s.Query != nil {
        structMap["query"] = s.Query
    }
    if s.Region != nil {
        structMap["region"] = s.Region.toMap()
    }
    if s.Safe != nil {
        structMap["safe"] = s.Safe
    }
    if s.Sort != nil {
        structMap["sort"] = s.Sort
    }
    if s.SpellcheckQuery != nil {
        structMap["spellcheck_query"] = s.SpellcheckQuery
    }
    if s.View != nil {
        structMap["view"] = s.View
    }
    if s.Width != nil {
        structMap["width"] = s.Width
    }
    if s.WidthFrom != nil {
        structMap["width_from"] = s.WidthFrom
    }
    if s.WidthTo != nil {
        structMap["width_to"] = s.WidthTo
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for SearchImage.
// It customizes the JSON unmarshaling process for SearchImage objects.
func (s *SearchImage) UnmarshalJSON(input []byte) error {
    var temp tempSearchImage
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "added_date", "added_date_end", "added_date_start", "aspect_ratio", "aspect_ratio_max", "aspect_ratio_min", "authentic", "category", "color", "contributor", "contributor_country", "fields", "height", "height_from", "height_to", "image_type", "keyword_safe_search", "language", "license", "model", "orientation", "page", "people_age", "people_ethnicity", "people_gender", "people_model_released", "people_number", "per_page", "query", "region", "safe", "sort", "spellcheck_query", "view", "width", "width_from", "width_to")
    if err != nil {
    	return err
    }
    s.AdditionalProperties = additionalProperties
    
    if temp.AddedDate != nil {
        AddedDateVal, err := time.Parse(DEFAULT_DATE, *temp.AddedDate)
        if err != nil {
            log.Fatalf("Cannot Parse added_date as % s format.", DEFAULT_DATE)
        }
        s.AddedDate = &AddedDateVal
    }
    if temp.AddedDateEnd != nil {
        AddedDateEndVal, err := time.Parse(DEFAULT_DATE, *temp.AddedDateEnd)
        if err != nil {
            log.Fatalf("Cannot Parse added_date_end as % s format.", DEFAULT_DATE)
        }
        s.AddedDateEnd = &AddedDateEndVal
    }
    if temp.AddedDateStart != nil {
        AddedDateStartVal, err := time.Parse(DEFAULT_DATE, *temp.AddedDateStart)
        if err != nil {
            log.Fatalf("Cannot Parse added_date_start as % s format.", DEFAULT_DATE)
        }
        s.AddedDateStart = &AddedDateStartVal
    }
    s.AspectRatio = temp.AspectRatio
    s.AspectRatioMax = temp.AspectRatioMax
    s.AspectRatioMin = temp.AspectRatioMin
    s.Authentic = temp.Authentic
    s.Category = temp.Category
    s.Color = temp.Color
    s.Contributor = temp.Contributor
    s.ContributorCountry = temp.ContributorCountry
    s.Fields = temp.Fields
    s.Height = temp.Height
    s.HeightFrom = temp.HeightFrom
    s.HeightTo = temp.HeightTo
    s.ImageType = temp.ImageType
    s.KeywordSafeSearch = temp.KeywordSafeSearch
    s.Language = temp.Language
    s.License = temp.License
    s.Model = temp.Model
    s.Orientation = temp.Orientation
    s.Page = temp.Page
    s.PeopleAge = temp.PeopleAge
    s.PeopleEthnicity = temp.PeopleEthnicity
    s.PeopleGender = temp.PeopleGender
    s.PeopleModelReleased = temp.PeopleModelReleased
    s.PeopleNumber = temp.PeopleNumber
    s.PerPage = temp.PerPage
    s.Query = temp.Query
    s.Region = temp.Region
    s.Safe = temp.Safe
    s.Sort = temp.Sort
    s.SpellcheckQuery = temp.SpellcheckQuery
    s.View = temp.View
    s.Width = temp.Width
    s.WidthFrom = temp.WidthFrom
    s.WidthTo = temp.WidthTo
    return nil
}

// tempSearchImage is a temporary struct used for validating the fields of SearchImage.
type tempSearchImage  struct {
    AddedDate           *string                        `json:"added_date,omitempty"`
    AddedDateEnd        *string                        `json:"added_date_end,omitempty"`
    AddedDateStart      *string                        `json:"added_date_start,omitempty"`
    AspectRatio         *float64                       `json:"aspect_ratio,omitempty"`
    AspectRatioMax      *float64                       `json:"aspect_ratio_max,omitempty"`
    AspectRatioMin      *float64                       `json:"aspect_ratio_min,omitempty"`
    Authentic           *bool                          `json:"authentic,omitempty"`
    Category            *string                        `json:"category,omitempty"`
    Color               *string                        `json:"color,omitempty"`
    Contributor         []string                       `json:"contributor,omitempty"`
    ContributorCountry  *SearchImageContributorCountry `json:"contributor_country,omitempty"`
    Fields              *string                        `json:"fields,omitempty"`
    Height              *int                           `json:"height,omitempty"`
    HeightFrom          *int                           `json:"height_from,omitempty"`
    HeightTo            *int                           `json:"height_to,omitempty"`
    ImageType           []ImageTypeEnum                `json:"image_type,omitempty"`
    KeywordSafeSearch   *bool                          `json:"keyword_safe_search,omitempty"`
    Language            *LanguageEnum                  `json:"language,omitempty"`
    License             []LicenseEnum                  `json:"license,omitempty"`
    Model               []string                       `json:"model,omitempty"`
    Orientation         *OrientationEnum               `json:"orientation,omitempty"`
    Page                *int                           `json:"page,omitempty"`
    PeopleAge           *PeopleAgeEnum                 `json:"people_age,omitempty"`
    PeopleEthnicity     []PeopleEthnicityEnum          `json:"people_ethnicity,omitempty"`
    PeopleGender        *PeopleGenderEnum              `json:"people_gender,omitempty"`
    PeopleModelReleased *bool                          `json:"people_model_released,omitempty"`
    PeopleNumber        *int                           `json:"people_number,omitempty"`
    PerPage             *int                           `json:"per_page,omitempty"`
    Query               *string                        `json:"query,omitempty"`
    Region              *SearchImageRegion             `json:"region,omitempty"`
    Safe                *bool                          `json:"safe,omitempty"`
    Sort                *SortEnum                      `json:"sort,omitempty"`
    SpellcheckQuery     *bool                          `json:"spellcheck_query,omitempty"`
    View                *ViewEnum                      `json:"view,omitempty"`
    Width               *int                           `json:"width,omitempty"`
    WidthFrom           *int                           `json:"width_from,omitempty"`
    WidthTo             *int                           `json:"width_to,omitempty"`
}
