// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// Shorts represents a Shorts struct.
type Shorts struct {
    Url                  *string                `json:"url,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Shorts,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s Shorts) String() string {
    return fmt.Sprintf(
    	"Shorts[Url=%v, AdditionalProperties=%v]",
    	s.Url, s.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Shorts.
// It customizes the JSON marshaling process for Shorts objects.
func (s Shorts) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(s.AdditionalProperties,
        "url"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(s.toMap())
}

// toMap converts the Shorts object to a map representation for JSON marshaling.
func (s Shorts) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, s.AdditionalProperties)
    if s.Url != nil {
        structMap["url"] = s.Url
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Shorts.
// It customizes the JSON unmarshaling process for Shorts objects.
func (s *Shorts) UnmarshalJSON(input []byte) error {
    var temp tempShorts
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "url")
    if err != nil {
    	return err
    }
    s.AdditionalProperties = additionalProperties
    
    s.Url = temp.Url
    return nil
}

// tempShorts is a temporary struct used for validating the fields of Shorts.
type tempShorts  struct {
    Url *string `json:"url,omitempty"`
}
