// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// ShortsLoopsStems represents a ShortsLoopsStems struct.
// Links for Shorts, Loops and Stems previews
type ShortsLoopsStems struct {
    Loops                map[string]Loops       `json:"loops,omitempty"`
    Shorts               map[string]Shorts      `json:"shorts,omitempty"`
    Stems                map[string]Stems       `json:"stems,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for ShortsLoopsStems,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s ShortsLoopsStems) String() string {
    return fmt.Sprintf(
    	"ShortsLoopsStems[Loops=%v, Shorts=%v, Stems=%v, AdditionalProperties=%v]",
    	s.Loops, s.Shorts, s.Stems, s.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for ShortsLoopsStems.
// It customizes the JSON marshaling process for ShortsLoopsStems objects.
func (s ShortsLoopsStems) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(s.AdditionalProperties,
        "loops", "shorts", "stems"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(s.toMap())
}

// toMap converts the ShortsLoopsStems object to a map representation for JSON marshaling.
func (s ShortsLoopsStems) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, s.AdditionalProperties)
    if s.Loops != nil {
        structMap["loops"] = s.Loops
    }
    if s.Shorts != nil {
        structMap["shorts"] = s.Shorts
    }
    if s.Stems != nil {
        structMap["stems"] = s.Stems
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for ShortsLoopsStems.
// It customizes the JSON unmarshaling process for ShortsLoopsStems objects.
func (s *ShortsLoopsStems) UnmarshalJSON(input []byte) error {
    var temp tempShortsLoopsStems
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "loops", "shorts", "stems")
    if err != nil {
    	return err
    }
    s.AdditionalProperties = additionalProperties
    
    s.Loops = temp.Loops
    s.Shorts = temp.Shorts
    s.Stems = temp.Stems
    return nil
}

// tempShortsLoopsStems is a temporary struct used for validating the fields of ShortsLoopsStems.
type tempShortsLoopsStems  struct {
    Loops  map[string]Loops  `json:"loops,omitempty"`
    Shorts map[string]Shorts `json:"shorts,omitempty"`
    Stems  map[string]Stems  `json:"stems,omitempty"`
}
