// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// Stems represents a Stems struct.
type Stems struct {
    Url                  *string                `json:"url,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Stems,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s Stems) String() string {
    return fmt.Sprintf(
    	"Stems[Url=%v, AdditionalProperties=%v]",
    	s.Url, s.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Stems.
// It customizes the JSON marshaling process for Stems objects.
func (s Stems) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(s.AdditionalProperties,
        "url"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(s.toMap())
}

// toMap converts the Stems object to a map representation for JSON marshaling.
func (s Stems) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, s.AdditionalProperties)
    if s.Url != nil {
        structMap["url"] = s.Url
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Stems.
// It customizes the JSON unmarshaling process for Stems objects.
func (s *Stems) UnmarshalJSON(input []byte) error {
    var temp tempStems
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "url")
    if err != nil {
    	return err
    }
    s.AdditionalProperties = additionalProperties
    
    s.Url = temp.Url
    return nil
}

// tempStems is a temporary struct used for validating the fields of Stems.
type tempStems  struct {
    Url *string `json:"url,omitempty"`
}
