// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// SubscriptionDataList represents a SubscriptionDataList struct.
// List of subscriptions
type SubscriptionDataList struct {
    // Subscriptions retrieved from this user
    Data                 []Subscription         `json:"data,omitempty"`
    // Error list; appears only if there was an error
    Errors               []Error                `json:"errors,omitempty"`
    // Optional error message
    Message              *string                `json:"message,omitempty"`
    // Current page that is being queried
    Page                 *int                   `json:"page,omitempty"`
    // Amount of subscriptions to show per page
    PerPage              *int                   `json:"per_page,omitempty"`
    // Total number of subscriptions for this user
    TotalCount           *int                   `json:"total_count,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for SubscriptionDataList,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s SubscriptionDataList) String() string {
    return fmt.Sprintf(
    	"SubscriptionDataList[Data=%v, Errors=%v, Message=%v, Page=%v, PerPage=%v, TotalCount=%v, AdditionalProperties=%v]",
    	s.Data, s.Errors, s.Message, s.Page, s.PerPage, s.TotalCount, s.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for SubscriptionDataList.
// It customizes the JSON marshaling process for SubscriptionDataList objects.
func (s SubscriptionDataList) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(s.AdditionalProperties,
        "data", "errors", "message", "page", "per_page", "total_count"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(s.toMap())
}

// toMap converts the SubscriptionDataList object to a map representation for JSON marshaling.
func (s SubscriptionDataList) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, s.AdditionalProperties)
    if s.Data != nil {
        structMap["data"] = s.Data
    }
    if s.Errors != nil {
        structMap["errors"] = s.Errors
    }
    if s.Message != nil {
        structMap["message"] = s.Message
    }
    if s.Page != nil {
        structMap["page"] = s.Page
    }
    if s.PerPage != nil {
        structMap["per_page"] = s.PerPage
    }
    if s.TotalCount != nil {
        structMap["total_count"] = s.TotalCount
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for SubscriptionDataList.
// It customizes the JSON unmarshaling process for SubscriptionDataList objects.
func (s *SubscriptionDataList) UnmarshalJSON(input []byte) error {
    var temp tempSubscriptionDataList
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "data", "errors", "message", "page", "per_page", "total_count")
    if err != nil {
    	return err
    }
    s.AdditionalProperties = additionalProperties
    
    s.Data = temp.Data
    s.Errors = temp.Errors
    s.Message = temp.Message
    s.Page = temp.Page
    s.PerPage = temp.PerPage
    s.TotalCount = temp.TotalCount
    return nil
}

// tempSubscriptionDataList is a temporary struct used for validating the fields of SubscriptionDataList.
type tempSubscriptionDataList  struct {
    Data       []Subscription `json:"data,omitempty"`
    Errors     []Error        `json:"errors,omitempty"`
    Message    *string        `json:"message,omitempty"`
    Page       *int           `json:"page,omitempty"`
    PerPage    *int           `json:"per_page,omitempty"`
    TotalCount *int           `json:"total_count,omitempty"`
}
