// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "log"
    "strings"
    "time"
)

// Subscription represents a Subscription struct.
// Subscription information
type Subscription struct {
    // An allotment of credits as part of a subscription
    Allotment            *Allotment             `json:"allotment,omitempty"`
    // Identifier for the type of assets associated with this subscription (images, videos, audio, editorial)
    AssetType            *string                `json:"asset_type,omitempty"`
    // Description of the subscription
    Description          *string                `json:"description,omitempty"`
    // Date the subscription ends
    ExpirationTime       *time.Time             `json:"expiration_time,omitempty"`
    // List of formats that are licensable for the subscription
    Formats              []LicenseFormat        `json:"formats,omitempty"`
    // Unique internal identifier for the subscription
    Id                   string                 `json:"id"`
    // Internal identifier for the type of subscription
    License              *string                `json:"license,omitempty"`
    // Subscription metadata; different for each customer
    Metadata             *interface{}           `json:"metadata,omitempty"`
    // Price
    PricePerDownload     *Price                 `json:"price_per_download,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Subscription,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (s Subscription) String() string {
    return fmt.Sprintf(
    	"Subscription[Allotment=%v, AssetType=%v, Description=%v, ExpirationTime=%v, Formats=%v, Id=%v, License=%v, Metadata=%v, PricePerDownload=%v, AdditionalProperties=%v]",
    	s.Allotment, s.AssetType, s.Description, s.ExpirationTime, s.Formats, s.Id, s.License, s.Metadata, s.PricePerDownload, s.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Subscription.
// It customizes the JSON marshaling process for Subscription objects.
func (s Subscription) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(s.AdditionalProperties,
        "allotment", "asset_type", "description", "expiration_time", "formats", "id", "license", "metadata", "price_per_download"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(s.toMap())
}

// toMap converts the Subscription object to a map representation for JSON marshaling.
func (s Subscription) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, s.AdditionalProperties)
    if s.Allotment != nil {
        structMap["allotment"] = s.Allotment.toMap()
    }
    if s.AssetType != nil {
        structMap["asset_type"] = s.AssetType
    }
    if s.Description != nil {
        structMap["description"] = s.Description
    }
    if s.ExpirationTime != nil {
        structMap["expiration_time"] = s.ExpirationTime.Format(time.RFC3339)
    }
    if s.Formats != nil {
        structMap["formats"] = s.Formats
    }
    structMap["id"] = s.Id
    if s.License != nil {
        structMap["license"] = s.License
    }
    if s.Metadata != nil {
        structMap["metadata"] = s.Metadata
    }
    if s.PricePerDownload != nil {
        structMap["price_per_download"] = s.PricePerDownload.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Subscription.
// It customizes the JSON unmarshaling process for Subscription objects.
func (s *Subscription) UnmarshalJSON(input []byte) error {
    var temp tempSubscription
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "allotment", "asset_type", "description", "expiration_time", "formats", "id", "license", "metadata", "price_per_download")
    if err != nil {
    	return err
    }
    s.AdditionalProperties = additionalProperties
    
    s.Allotment = temp.Allotment
    s.AssetType = temp.AssetType
    s.Description = temp.Description
    if temp.ExpirationTime != nil {
        ExpirationTimeVal, err := time.Parse(time.RFC3339, *temp.ExpirationTime)
        if err != nil {
            log.Fatalf("Cannot Parse expiration_time as % s format.", time.RFC3339)
        }
        s.ExpirationTime = &ExpirationTimeVal
    }
    s.Formats = temp.Formats
    s.Id = *temp.Id
    s.License = temp.License
    s.Metadata = temp.Metadata
    s.PricePerDownload = temp.PricePerDownload
    return nil
}

// tempSubscription is a temporary struct used for validating the fields of Subscription.
type tempSubscription  struct {
    Allotment        *Allotment      `json:"allotment,omitempty"`
    AssetType        *string         `json:"asset_type,omitempty"`
    Description      *string         `json:"description,omitempty"`
    ExpirationTime   *string         `json:"expiration_time,omitempty"`
    Formats          []LicenseFormat `json:"formats,omitempty"`
    Id               *string         `json:"id"`
    License          *string         `json:"license,omitempty"`
    Metadata         *interface{}    `json:"metadata,omitempty"`
    PricePerDownload *Price          `json:"price_per_download,omitempty"`
}

func (s *tempSubscription) validate() error {
    var errs []string
    if s.Id == nil {
        errs = append(errs, "required field `id` is missing for type `Subscription`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
