// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// TestValidateHeader represents a TestValidateHeader struct.
// Validation results
type TestValidateHeader struct {
    // User agent to expect in the response
    UserAgent            *string                `json:"user-agent,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for TestValidateHeader,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (t TestValidateHeader) String() string {
    return fmt.Sprintf(
    	"TestValidateHeader[UserAgent=%v, AdditionalProperties=%v]",
    	t.UserAgent, t.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for TestValidateHeader.
// It customizes the JSON marshaling process for TestValidateHeader objects.
func (t TestValidateHeader) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(t.AdditionalProperties,
        "user-agent"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(t.toMap())
}

// toMap converts the TestValidateHeader object to a map representation for JSON marshaling.
func (t TestValidateHeader) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, t.AdditionalProperties)
    if t.UserAgent != nil {
        structMap["user-agent"] = t.UserAgent
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for TestValidateHeader.
// It customizes the JSON unmarshaling process for TestValidateHeader objects.
func (t *TestValidateHeader) UnmarshalJSON(input []byte) error {
    var temp tempTestValidateHeader
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "user-agent")
    if err != nil {
    	return err
    }
    t.AdditionalProperties = additionalProperties
    
    t.UserAgent = temp.UserAgent
    return nil
}

// tempTestValidateHeader is a temporary struct used for validating the fields of TestValidateHeader.
type tempTestValidateHeader  struct {
    UserAgent *string `json:"user-agent,omitempty"`
}
