// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// TestValidate represents a TestValidate struct.
// Validation results
type TestValidate struct {
    // Validation results
    Header               *TestValidateHeader    `json:"header,omitempty"`
    // Validation results
    Query                *TestValidateQuery     `json:"query,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for TestValidate,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (t TestValidate) String() string {
    return fmt.Sprintf(
    	"TestValidate[Header=%v, Query=%v, AdditionalProperties=%v]",
    	t.Header, t.Query, t.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for TestValidate.
// It customizes the JSON marshaling process for TestValidate objects.
func (t TestValidate) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(t.AdditionalProperties,
        "header", "query"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(t.toMap())
}

// toMap converts the TestValidate object to a map representation for JSON marshaling.
func (t TestValidate) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, t.AdditionalProperties)
    if t.Header != nil {
        structMap["header"] = t.Header.toMap()
    }
    if t.Query != nil {
        structMap["query"] = t.Query.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for TestValidate.
// It customizes the JSON unmarshaling process for TestValidate objects.
func (t *TestValidate) UnmarshalJSON(input []byte) error {
    var temp tempTestValidate
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "header", "query")
    if err != nil {
    	return err
    }
    t.AdditionalProperties = additionalProperties
    
    t.Header = temp.Header
    t.Query = temp.Query
    return nil
}

// tempTestValidate is a temporary struct used for validating the fields of TestValidate.
type tempTestValidate  struct {
    Header *TestValidateHeader `json:"header,omitempty"`
    Query  *TestValidateQuery  `json:"query,omitempty"`
}
