// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// TestEcho represents a TestEcho struct.
// Text to echo in the response
type TestEcho struct {
    Text                 *string                `json:"text,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for TestEcho,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (t TestEcho) String() string {
    return fmt.Sprintf(
    	"TestEcho[Text=%v, AdditionalProperties=%v]",
    	t.Text, t.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for TestEcho.
// It customizes the JSON marshaling process for TestEcho objects.
func (t TestEcho) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(t.AdditionalProperties,
        "text"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(t.toMap())
}

// toMap converts the TestEcho object to a map representation for JSON marshaling.
func (t TestEcho) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, t.AdditionalProperties)
    if t.Text != nil {
        structMap["text"] = t.Text
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for TestEcho.
// It customizes the JSON unmarshaling process for TestEcho objects.
func (t *TestEcho) UnmarshalJSON(input []byte) error {
    var temp tempTestEcho
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "text")
    if err != nil {
    	return err
    }
    t.AdditionalProperties = additionalProperties
    
    t.Text = temp.Text
    return nil
}

// tempTestEcho is a temporary struct used for validating the fields of TestEcho.
type tempTestEcho  struct {
    Text *string `json:"text,omitempty"`
}
