// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// TestValidateQuery represents a TestValidateQuery struct.
// Validation results
type TestValidateQuery struct {
    // Integer ID that was passed in the request
    Id                   int                    `json:"id"`
    // List of tags that were passed in the request
    Tag                  []string               `json:"tag,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for TestValidateQuery,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (t TestValidateQuery) String() string {
    return fmt.Sprintf(
    	"TestValidateQuery[Id=%v, Tag=%v, AdditionalProperties=%v]",
    	t.Id, t.Tag, t.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for TestValidateQuery.
// It customizes the JSON marshaling process for TestValidateQuery objects.
func (t TestValidateQuery) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(t.AdditionalProperties,
        "id", "tag"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(t.toMap())
}

// toMap converts the TestValidateQuery object to a map representation for JSON marshaling.
func (t TestValidateQuery) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, t.AdditionalProperties)
    structMap["id"] = t.Id
    if t.Tag != nil {
        structMap["tag"] = t.Tag
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for TestValidateQuery.
// It customizes the JSON unmarshaling process for TestValidateQuery objects.
func (t *TestValidateQuery) UnmarshalJSON(input []byte) error {
    var temp tempTestValidateQuery
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "id", "tag")
    if err != nil {
    	return err
    }
    t.AdditionalProperties = additionalProperties
    
    t.Id = *temp.Id
    t.Tag = temp.Tag
    return nil
}

// tempTestValidateQuery is a temporary struct used for validating the fields of TestValidateQuery.
type tempTestValidateQuery  struct {
    Id  *int     `json:"id"`
    Tag []string `json:"tag,omitempty"`
}

func (t *tempTestValidateQuery) validate() error {
    var errs []string
    if t.Id == nil {
        errs = append(errs, "required field `id` is missing for type `TestValidateQuery`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
