// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// Url represents a Url struct.
// URL object
type Url struct {
    // URL that can be used to download the unwatermarked, licensed asset
    Url                  string                 `json:"url"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for Url,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (u Url) String() string {
    return fmt.Sprintf(
    	"Url[Url=%v, AdditionalProperties=%v]",
    	u.Url, u.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for Url.
// It customizes the JSON marshaling process for Url objects.
func (u Url) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(u.AdditionalProperties,
        "url"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(u.toMap())
}

// toMap converts the Url object to a map representation for JSON marshaling.
func (u Url) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, u.AdditionalProperties)
    structMap["url"] = u.Url
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for Url.
// It customizes the JSON unmarshaling process for Url objects.
func (u *Url) UnmarshalJSON(input []byte) error {
    var temp tempUrl
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "url")
    if err != nil {
    	return err
    }
    u.AdditionalProperties = additionalProperties
    
    u.Url = *temp.Url
    return nil
}

// tempUrl is a temporary struct used for validating the fields of Url.
type tempUrl  struct {
    Url *string `json:"url"`
}

func (u *tempUrl) validate() error {
    var errs []string
    if u.Url == nil {
        errs = append(errs, "required field `url` is missing for type `Url`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
