// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// VideoDataList represents a VideoDataList struct.
// List of videos
type VideoDataList struct {
    // Videos
    Data                 []Video                `json:"data,omitempty"`
    // Error list; appears only if there was an error
    Errors               []Error                `json:"errors,omitempty"`
    // Server-generated message, if any
    Message              *string                `json:"message,omitempty"`
    // Current page that is returned
    Page                 *int                   `json:"page,omitempty"`
    // Number of results per page
    PerPage              *int                   `json:"per_page,omitempty"`
    // Total count of all results across all pages
    TotalCount           *int                   `json:"total_count,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for VideoDataList,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (v VideoDataList) String() string {
    return fmt.Sprintf(
    	"VideoDataList[Data=%v, Errors=%v, Message=%v, Page=%v, PerPage=%v, TotalCount=%v, AdditionalProperties=%v]",
    	v.Data, v.Errors, v.Message, v.Page, v.PerPage, v.TotalCount, v.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for VideoDataList.
// It customizes the JSON marshaling process for VideoDataList objects.
func (v VideoDataList) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(v.AdditionalProperties,
        "data", "errors", "message", "page", "per_page", "total_count"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(v.toMap())
}

// toMap converts the VideoDataList object to a map representation for JSON marshaling.
func (v VideoDataList) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, v.AdditionalProperties)
    if v.Data != nil {
        structMap["data"] = v.Data
    }
    if v.Errors != nil {
        structMap["errors"] = v.Errors
    }
    if v.Message != nil {
        structMap["message"] = v.Message
    }
    if v.Page != nil {
        structMap["page"] = v.Page
    }
    if v.PerPage != nil {
        structMap["per_page"] = v.PerPage
    }
    if v.TotalCount != nil {
        structMap["total_count"] = v.TotalCount
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for VideoDataList.
// It customizes the JSON unmarshaling process for VideoDataList objects.
func (v *VideoDataList) UnmarshalJSON(input []byte) error {
    var temp tempVideoDataList
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "data", "errors", "message", "page", "per_page", "total_count")
    if err != nil {
    	return err
    }
    v.AdditionalProperties = additionalProperties
    
    v.Data = temp.Data
    v.Errors = temp.Errors
    v.Message = temp.Message
    v.Page = temp.Page
    v.PerPage = temp.PerPage
    v.TotalCount = temp.TotalCount
    return nil
}

// tempVideoDataList is a temporary struct used for validating the fields of VideoDataList.
type tempVideoDataList  struct {
    Data       []Video `json:"data,omitempty"`
    Errors     []Error `json:"errors,omitempty"`
    Message    *string `json:"message,omitempty"`
    Page       *int    `json:"page,omitempty"`
    PerPage    *int    `json:"per_page,omitempty"`
    TotalCount *int    `json:"total_count,omitempty"`
}
