// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// VideoAssets represents a VideoAssets struct.
// Video asset information
type VideoAssets struct {
    // Video asset information
    M4k                  *VideoSizeDetails      `json:"4k,omitempty"`
    // Video asset information
    Hd                   *VideoSizeDetails      `json:"hd,omitempty"`
    // URL object
    PreviewJpg           *Url                   `json:"preview_jpg,omitempty"`
    // URL object
    PreviewMp4           *Url                   `json:"preview_mp4,omitempty"`
    // URL object
    PreviewWebm          *Url                   `json:"preview_webm,omitempty"`
    // Video asset information
    Sd                   *VideoSizeDetails      `json:"sd,omitempty"`
    // URL object
    ThumbJpg             *Url                   `json:"thumb_jpg,omitempty"`
    // List of URLs
    ThumbJpgs            *Urls                  `json:"thumb_jpgs,omitempty"`
    // URL object
    ThumbMp4             *Url                   `json:"thumb_mp4,omitempty"`
    // URL object
    ThumbWebm            *Url                   `json:"thumb_webm,omitempty"`
    // Video asset information
    Web                  *VideoSizeDetails      `json:"web,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for VideoAssets,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (v VideoAssets) String() string {
    return fmt.Sprintf(
    	"VideoAssets[M4k=%v, Hd=%v, PreviewJpg=%v, PreviewMp4=%v, PreviewWebm=%v, Sd=%v, ThumbJpg=%v, ThumbJpgs=%v, ThumbMp4=%v, ThumbWebm=%v, Web=%v, AdditionalProperties=%v]",
    	v.M4k, v.Hd, v.PreviewJpg, v.PreviewMp4, v.PreviewWebm, v.Sd, v.ThumbJpg, v.ThumbJpgs, v.ThumbMp4, v.ThumbWebm, v.Web, v.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for VideoAssets.
// It customizes the JSON marshaling process for VideoAssets objects.
func (v VideoAssets) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(v.AdditionalProperties,
        "4k", "hd", "preview_jpg", "preview_mp4", "preview_webm", "sd", "thumb_jpg", "thumb_jpgs", "thumb_mp4", "thumb_webm", "web"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(v.toMap())
}

// toMap converts the VideoAssets object to a map representation for JSON marshaling.
func (v VideoAssets) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, v.AdditionalProperties)
    if v.M4k != nil {
        structMap["4k"] = v.M4k.toMap()
    }
    if v.Hd != nil {
        structMap["hd"] = v.Hd.toMap()
    }
    if v.PreviewJpg != nil {
        structMap["preview_jpg"] = v.PreviewJpg.toMap()
    }
    if v.PreviewMp4 != nil {
        structMap["preview_mp4"] = v.PreviewMp4.toMap()
    }
    if v.PreviewWebm != nil {
        structMap["preview_webm"] = v.PreviewWebm.toMap()
    }
    if v.Sd != nil {
        structMap["sd"] = v.Sd.toMap()
    }
    if v.ThumbJpg != nil {
        structMap["thumb_jpg"] = v.ThumbJpg.toMap()
    }
    if v.ThumbJpgs != nil {
        structMap["thumb_jpgs"] = v.ThumbJpgs.toMap()
    }
    if v.ThumbMp4 != nil {
        structMap["thumb_mp4"] = v.ThumbMp4.toMap()
    }
    if v.ThumbWebm != nil {
        structMap["thumb_webm"] = v.ThumbWebm.toMap()
    }
    if v.Web != nil {
        structMap["web"] = v.Web.toMap()
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for VideoAssets.
// It customizes the JSON unmarshaling process for VideoAssets objects.
func (v *VideoAssets) UnmarshalJSON(input []byte) error {
    var temp tempVideoAssets
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "4k", "hd", "preview_jpg", "preview_mp4", "preview_webm", "sd", "thumb_jpg", "thumb_jpgs", "thumb_mp4", "thumb_webm", "web")
    if err != nil {
    	return err
    }
    v.AdditionalProperties = additionalProperties
    
    v.M4k = temp.M4k
    v.Hd = temp.Hd
    v.PreviewJpg = temp.PreviewJpg
    v.PreviewMp4 = temp.PreviewMp4
    v.PreviewWebm = temp.PreviewWebm
    v.Sd = temp.Sd
    v.ThumbJpg = temp.ThumbJpg
    v.ThumbJpgs = temp.ThumbJpgs
    v.ThumbMp4 = temp.ThumbMp4
    v.ThumbWebm = temp.ThumbWebm
    v.Web = temp.Web
    return nil
}

// tempVideoAssets is a temporary struct used for validating the fields of VideoAssets.
type tempVideoAssets  struct {
    M4k         *VideoSizeDetails `json:"4k,omitempty"`
    Hd          *VideoSizeDetails `json:"hd,omitempty"`
    PreviewJpg  *Url              `json:"preview_jpg,omitempty"`
    PreviewMp4  *Url              `json:"preview_mp4,omitempty"`
    PreviewWebm *Url              `json:"preview_webm,omitempty"`
    Sd          *VideoSizeDetails `json:"sd,omitempty"`
    ThumbJpg    *Url              `json:"thumb_jpg,omitempty"`
    ThumbJpgs   *Urls             `json:"thumb_jpgs,omitempty"`
    ThumbMp4    *Url              `json:"thumb_mp4,omitempty"`
    ThumbWebm   *Url              `json:"thumb_webm,omitempty"`
    Web         *VideoSizeDetails `json:"web,omitempty"`
}
