// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "errors"
    "fmt"
    "strings"
)

// VideoPreviewUrl represents a VideoPreviewUrl struct.
// Video preview information
type VideoPreviewUrl struct {
    // Direct URL to the image
    Url                  string                 `json:"url"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for VideoPreviewUrl,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (v VideoPreviewUrl) String() string {
    return fmt.Sprintf(
    	"VideoPreviewUrl[Url=%v, AdditionalProperties=%v]",
    	v.Url, v.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for VideoPreviewUrl.
// It customizes the JSON marshaling process for VideoPreviewUrl objects.
func (v VideoPreviewUrl) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(v.AdditionalProperties,
        "url"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(v.toMap())
}

// toMap converts the VideoPreviewUrl object to a map representation for JSON marshaling.
func (v VideoPreviewUrl) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, v.AdditionalProperties)
    structMap["url"] = v.Url
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for VideoPreviewUrl.
// It customizes the JSON unmarshaling process for VideoPreviewUrl objects.
func (v *VideoPreviewUrl) UnmarshalJSON(input []byte) error {
    var temp tempVideoPreviewUrl
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    err = temp.validate()
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "url")
    if err != nil {
    	return err
    }
    v.AdditionalProperties = additionalProperties
    
    v.Url = *temp.Url
    return nil
}

// tempVideoPreviewUrl is a temporary struct used for validating the fields of VideoPreviewUrl.
type tempVideoPreviewUrl  struct {
    Url *string `json:"url"`
}

func (v *tempVideoPreviewUrl) validate() error {
    var errs []string
    if v.Url == nil {
        errs = append(errs, "required field `url` is missing for type `VideoPreviewUrl`")
    }
    if len(errs) == 0 {
        return nil
    }
    return errors.New(strings.Join (errs, "\n"))
}
