// Package shutterstockapiexplorer
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
package models

import (
    "encoding/json"
    "fmt"
)

// VideoSizeDetails represents a VideoSizeDetails struct.
// Video asset information
type VideoSizeDetails struct {
    // Display name of this video size
    DisplayName          *string                `json:"display_name,omitempty"`
    // File size (in bytes) of this video size
    FileSize             *int                   `json:"file_size,omitempty"`
    // Format of this video size
    Format               *string                `json:"format,omitempty"`
    // Frames per second of this video size
    Fps                  *float64               `json:"fps,omitempty"`
    // Height of this video size
    Height               *int                   `json:"height,omitempty"`
    // Whether or not videos can be licensed in this video size
    IsLicensable         *bool                  `json:"is_licensable,omitempty"`
    // Width of this video size
    Width                *int                   `json:"width,omitempty"`
    AdditionalProperties map[string]interface{} `json:"_"`
}

// String implements the fmt.Stringer interface for VideoSizeDetails,
// providing a human-readable string representation useful for logging, debugging or displaying information.
func (v VideoSizeDetails) String() string {
    return fmt.Sprintf(
    	"VideoSizeDetails[DisplayName=%v, FileSize=%v, Format=%v, Fps=%v, Height=%v, IsLicensable=%v, Width=%v, AdditionalProperties=%v]",
    	v.DisplayName, v.FileSize, v.Format, v.Fps, v.Height, v.IsLicensable, v.Width, v.AdditionalProperties)
}

// MarshalJSON implements the json.Marshaler interface for VideoSizeDetails.
// It customizes the JSON marshaling process for VideoSizeDetails objects.
func (v VideoSizeDetails) MarshalJSON() (
    []byte,
    error) {
    if err := DetectConflictingProperties(v.AdditionalProperties,
        "display_name", "file_size", "format", "fps", "height", "is_licensable", "width"); err != nil {
        return []byte{}, err
    }
    return json.Marshal(v.toMap())
}

// toMap converts the VideoSizeDetails object to a map representation for JSON marshaling.
func (v VideoSizeDetails) toMap() map[string]any {
    structMap := make(map[string]any)
    MergeAdditionalProperties(structMap, v.AdditionalProperties)
    if v.DisplayName != nil {
        structMap["display_name"] = v.DisplayName
    }
    if v.FileSize != nil {
        structMap["file_size"] = v.FileSize
    }
    if v.Format != nil {
        structMap["format"] = v.Format
    }
    if v.Fps != nil {
        structMap["fps"] = v.Fps
    }
    if v.Height != nil {
        structMap["height"] = v.Height
    }
    if v.IsLicensable != nil {
        structMap["is_licensable"] = v.IsLicensable
    }
    if v.Width != nil {
        structMap["width"] = v.Width
    }
    return structMap
}

// UnmarshalJSON implements the json.Unmarshaler interface for VideoSizeDetails.
// It customizes the JSON unmarshaling process for VideoSizeDetails objects.
func (v *VideoSizeDetails) UnmarshalJSON(input []byte) error {
    var temp tempVideoSizeDetails
    err := json.Unmarshal(input, &temp)
    if err != nil {
    	return err
    }
    additionalProperties, err := ExtractAdditionalProperties[interface{}](input, "display_name", "file_size", "format", "fps", "height", "is_licensable", "width")
    if err != nil {
    	return err
    }
    v.AdditionalProperties = additionalProperties
    
    v.DisplayName = temp.DisplayName
    v.FileSize = temp.FileSize
    v.Format = temp.Format
    v.Fps = temp.Fps
    v.Height = temp.Height
    v.IsLicensable = temp.IsLicensable
    v.Width = temp.Width
    return nil
}

// tempVideoSizeDetails is a temporary struct used for validating the fields of VideoSizeDetails.
type tempVideoSizeDetails  struct {
    DisplayName  *string  `json:"display_name,omitempty"`
    FileSize     *int     `json:"file_size,omitempty"`
    Format       *string  `json:"format,omitempty"`
    Fps          *float64 `json:"fps,omitempty"`
    Height       *int     `json:"height,omitempty"`
    IsLicensable *bool    `json:"is_licensable,omitempty"`
    Width        *int     `json:"width,omitempty"`
}
